### ISSUE TITLE
Add demo showing built-in drawing capabilities

### ISSUE THREAD

**Issue by dumblob** [vurtun/nuklear#101]
After publishing news about Nuklear 1.0 on three IT oriented servers, I got quite a lot of feedback and one thing I noticed is, that people don't understand well the backend agnosticity.

Because of that I'm certain, we need some demo showing as many as possible built-in rendering capabilities of Nuklear to some RGB buffer and then just exporting the buffer e.g. to PNG to show an **absolutely minimal** functional program using only Nuklear and stb_image_write.h and no rendering backend.

**Comment by vurtun** [comment]
I actually wrote a 2D software renderer with SIMD support some time ago to draw basic shapes. I could spend some time and update it and create a demo out of that.

**Comment by dumblob** [comment]
Wow, I like such experiments.

On the other hand, we should consider if it's worth complicating this simpliest end-to-end example (just running the compiled binary with a filename as the only argument would produce PNG and nothing else) of all. A basic Bresenham's line algorithm and flood-fill algorithm might be more clear for newcomers than anything else.

As a side note - [Petr Kobalicek](https://github.com/kobalicek) works already several years on highly optimized SIMD-based lightweight vector graphics engine [Blend2D](http://blend2d.com/). I can recommend taking a look at the principles he's using, because they're quite new and very performance-beneficial.

**Comment by vurtun** [comment]
I don't think it is really worth it. The demos are already showing what different render backends are possible. What I can do at the moment is to do some simple porting of what I have for software rendering but I will not spend time creating a render backend for Blend2D. There are more important render backends for me at the moment (DirectX and OpenGL 2), but you are more then welcome to create one.

**Comment by dumblob** [comment]
Oh, I'm sorry for confusion. Blend2D is just totally off-topic (and is by the way not yet published, se no such backend can be currently written :)).

The request is just for the simpliest possible software rendering (disregarding it's inefficiency) in pure C89 to show Nuklear built-in "rendering" capabilities (e.g. that round corners are computed in Nuklear).

**Comment by DeXP** [comment]
Non OpenGL image examples are really needed. For example, I loaded a PNG-file across stb_image. How can I display it in Nuklear via GDI+? This question in general: I have array of pixels, how can I display it?
