### ISSUE TITLE
Restore blending equation and various caps in glfw/sdl integration

### ISSUE THREAD

**Issue by ands** [vurtun/nuklear#105]
While other state gets saved and restored, GL_BLEND, GL_CULL_FACE, GL_DEPTH_TEST and GL_SCISSOR_TEST only get set to nuklear-specific states and may mess up any further rendering.
See https://www.opengl.org/sdk/docs/man/html/glIsEnabled.xhtml.
The blend func and equation could also be saved and restored as seen in the Associated Gets section of https://www.opengl.org/sdk/docs/man/html/glBlendFunc.xhtml and https://www.opengl.org/sdk/docs/man/html/glBlendEquation.xhtml.
:)

**Comment by mmozeiko** [comment]
My opinion on this is that no GL code should have glIsEnabled or glGet calls. That can/will give performance issues. In the beginning just set the state you want, and at the end set it to default (disable blend, disable scissor, set program/vbo to 0). Whenever somebody wants to enable something, for example blending, he is also responsible setting up relevant information (blend function).

But of course, decision on this should be one app developer not nuklear.

nuklear still can have 100 and one rendering issues, if it doesn't reset some GL state that app potentially has set (what if glColorMask is set to GL_FALSE? what if GL_RASTERIZER_DISCARD is enabled? what if wrong FBO is bound? etc...)

Maybe for sake of simplicity in the demo just do glPushAttrib(GL_ALL_ATTRIB_BITS) and later glPopAttrib, with huge WARNING comment next to it - "this is not how it should be done, figure your own state caching"?

**Comment by ands** [comment]
I'd be fine with the default state too :). I've commented those glGet* out on my side anyways. But those non-default caps interfered with my own rendering...
