### ISSUE TITLE
nk_tree_push in a loop / equivalent to ImGui::PushID(...)?

### ISSUE THREAD

**Issue by ands** [vurtun/nuklear#106]
I'm trying to make an editor for a list of things.
I'm looping over my things and outputting a tree node for each of them.
Unfortunately nk_tree_push(...) uses \__FILE\__ and \__LINE\__ for its hash.
But these will be the same for each iteration.
So I've started using nk__tree_push directly, but the double underscore indicates that it's "private" and probably wasn't supposed to be used directly.
Is there a better way to solve this problem?
I'm used to using dear imgui's ImGui::PushID(...) in such a situation.

**Comment by vurtun** [comment]
Yeah that was I mistake on my part. I shouldn't have use the double underscore. I also made the mistake of not allowing non-string ids which is now possible. I also added a version which just requires an ID instead of hash + id.

**Comment by ands** [comment]
Sorry for the late response! :)
I consider this fixed for my purpose. Thanks!

But since nk_tree_push_id uses \__FILE\__ and an id for hashing, it can only be used once in a single source file, if called with the iteration variable as the id.
Example:
`for (int i = 0; i < 23; ++i) {`
`    nk_tree_push_id( ..., i);`
`    ...`
`    nk_tree_pop();`
`}`
`...`
`for (int i = 0; i < 42; ++i) {`
`    nk_tree_push_id( ..., i);`
`    ...`
`    nk_tree_pop();`
`}`

It wouldn't be obvious to a user that nk_tree_push_id can not be called that way.
I'd recommend to remove this macro to avoid confusion.
In my codebase, I directly moved to use nk_tree_push_hashed to avoid that issue.

Maybe instead add something like this:
#define nk_tree_push_unique(ctx, type, tile, category, id) nk_tree_push_hashed(ctx, type, title, state, category, nk_strlen(category), id)

**Comment by vurtun** [comment]
> It wouldn't be obvious to a user that nk_tree_push_id can not be called that way.

Yeah you are probably right

> Maybe instead add something like this:
#define nk_tree_push_unique(ctx, type, tile, category, id) nk_tree_push_hashed(ctx, type, title, state, category, nk_strlen(category), id)

My idea was to concat `__FILE__` and `__LINE__` into a string and then let the user provide an `ID`. Which would solve your problem as well?

**Comment by ands** [comment]
Alright!
\__FILE\__ and \__LINE\__ is probably \__FINE\__ ;)
