### ISSUE TITLE
nk_draw_list_push_image to an empty cmd list drops texture parameter

### ISSUE THREAD

**Issue by rsaarelm** [vurtun/nuklear#108]
Haven't tried this, just looking at the code, but shouldn't the [empty list branch](https://github.com/vurtun/nuklear/blob/87efb61a9ffecec6232cc792c96443a4d6f05bde/nuklear.h#L5661) push the parameter texture, not the empty texture?

**Comment by vurtun** [comment]
Thanks for the issue. Usually this case can never happen inside the library but it is still a bug if `draw_list` is used separately. So great find!
