### ISSUE TITLE
datatype size issues

### ISSUE THREAD

**Issue by ornitorrincos** [vurtun/nuklear#115]
although on a modern compiler these go away defining NK_INCLUDE_FIXED_TYPES, there are some issues with some data type sizes

* nk_rune is defined as nk_uint which seems to be defined as unsigned short, making it 2 bytes long

typedef int nk__check_rune[(sizeof(nk_rune) >= 4) ? 1 : -1];

* nk_ushort is also defined as unsigned short, making the following tests self contradictory

typedef int nk__check_ushort[(sizeof(nk_ushort) == 2) ? 1 : -1];
typedef int nk__check_short[(sizeof(nk_short) == 2) ? 1 : -1];
typedef int nk__check_uint[(sizeof(nk_uint) == 4) ? 1 : -1];
typedef int nk__check_int[(sizeof(nk_int) == 4) ? 1 : -1];

Additionaly there is also the issue of nk_size and nk_ptr defined as unsigned long making them 4 bytes wide on x64 windows, but can't think of a fix for that without platform flags to check for architecture

**Comment by vurtun** [comment]
Thanks for the issue, yeah you are right `short`/`unsigned short` is a copy/paste error and should have been `int` and `unsigned int` by default. `short` just does not make sense at all in this instance. I will push a fix ASAP. 
`nk_size` and `nk_ptr` are like you said a little bit more complicated to get right at least for a library. But I allow overwriting types. Fixing `nk_size` would just require #define NK_SIZE_TYPE size_t`
and would work platform independent. Without `stdint.h` I don't think there is a platform independent way of declarting `nk_ptr`, but like `nk_size` it is possible to just set `#define NK_POINTER_TYPE type`, which is not optimal but I don't think there is anything I could do without adding tons of `#ifdef` everywhere and I will not do that.
