### ISSUE TITLE
can you provide a makefile to make your header a real lib ?

### ISSUE THREAD

**Issue by malv-c** [vurtun/nuklear#122]
from asm it is not usable now :(
i want to code asm and call functions of your lib when needed
if so don't forget to support openglesv2 ;)

**Comment by dumblob** [comment]
Try to search for `gcc so lib` and you'll get tons of articles like this:

~~~~
gcc -c -fPIC calc_mean.c -o calc_mean.o
gcc -shared -Wl,-soname,libmean.so.1 -o libmean.so.1.0.1  calc_mean.o
~~~~

**Comment by malv-c** [comment]
the command is not the real problem
it's about a correct making of the lib with perfect working
so a .c file is also needed where uncomment good options for the target is manually done
dumblob use -flto as gcc and ld arg it's better ;)

**Comment by dumblob** [comment]
There is unfortunately no silver bullet in which options (assuming different `#define` statements parametrizing Nuklear) you should choose for a system-wide `.so` library. You can't even globally address decisions like whether the particular application will be run on a touch-enabled display or just plain display (as nowadays e.g. half of the notebooks on the market have touch-enabled displays, but the others not).

This would make sense only for a very specific platform, where the requirements are well-known in advance. But that's not what e.g. current Linux distributions do.

But from the technical point of view, there shouldn't be any issues with Nuklear as `.so` library.

Btw thanks for the `-flto` argument - it's definitely better than just `-fPIC`.
