### ISSUE TITLE
Multiple lines in a chart

### ISSUE THREAD

**Issue by jviki** [vurtun/nuklear#124]
Hello,

is it possible to have multiple lines in a single chart? I don't understand how could I do such a thing with the provided API.

Thanks
Jan

**Comment by vurtun** [comment]
Hey,
the `chart` API is quite limited at the moment and needs a rewrite. It is not really hard to get multiple lines/columns or even both at the same time running but it requires some modifications. But in general the whole `chart` situation is probably an interesting problem and entry to contribute to this library if anyone is interested.

**Comment by jviki** [comment]
This is a hack to extend the charts (I didn't do pull request as I think that this is not a good solution): https://gist.github.com/jviki/46a563f26cf2c3f76cb61c4b121a6824#file-0001-support-multiple-data-sets-in-a-single-chart-patch

**Comment by vurtun** [comment]
Simple solution I like it! I am quite tempted to use it. The solution is not perfect but the complete `chart` API is quite bad so this would be nice to `just get it done`. If you want you can create the PR. I will change up a few things but overall it looks good.

**Comment by dumblob** [comment]
Thanks @jviki for the contribution. Making arrays `struct nk_vec2 last[NK_CHART_MAX_DEPTH];` and `int index[NK_CHART_MAX_DEPTH];` dynamic could suffice for `just get it done` IMHO.

**Comment by dumblob** [comment]
Sorry guys, my mistake - I read it wrongly. Never mind.
