### ISSUE TITLE
Can't move a window that isn't focused (is overlapped)

### ISSUE THREAD

**Issue by 0----0** [vurtun/nuklear#131]
Normally, windows focus when you mouse over them.  However, if window A overlaps window B, and window A is above window B, then window B will not be focused when moused over.  If you try to click and drag the title bar of window B without focusing it first, it will not move the window.

Steps to reproduce:
1. Start the "extended" example.
2. Drag the Basic Demo window so it overlaps the Grid Demo window, like so.
![](http://i.imgur.com/vrQwnA4.png)
3. Click and drag the title bar of the Grid Demo window.  It will not move.

For interfaces that involve many overlapping windows, having to click a window twice to be able to drag it around is inconvenient.  I believe it is important that functions like moving, scaling, minimizing, and closing windows can be performed without an additional click on the windows in question, even if they are overlapped.

**Comment by vurtun** [comment]
Thanks this was just a small issue, I just had to change the activating behavior for windows while hopefully not introducing any bugs.
