### ISSUE TITLE
Piemenu in example is cut off on bottom

### ISSUE THREAD

**Issue by 0----0** [vurtun/nuklear#132]
When I use the piemenu in the 'extended' example, it looks kind of like the bottom's chopped off, rather than a perfect circle like in the gallery.  Can you reproduce this?

![](http://i.imgur.com/B2eQmr2.png)

**Comment by vurtun** [comment]
Thanks for noticing and opening an Issue. I forgot to set some `padding` to zero inside the example, it should now be fixed.
