### ISSUE TITLE
glScissor scaling bug in nuklear_glfw_gl3.h? With probable solution.

### ISSUE THREAD

**Issue by mhroth** [vurtun/nuklear#133]
On a Retina MBP I tried to run the `demo/glfw_opengl3` example. The example correctly displayed a window, but no content:
### What I Got

![button_480](https://cloud.githubusercontent.com/assets/25988/15291539/6183cbf8-1b76-11e6-8768-a63029f379cc.jpg)
### What I Expected

![nzn](https://cloud.githubusercontent.com/assets/25988/15291428/b5c3efaa-1b75-11e6-80cf-451e9311e0a4.jpg)

After some investigating, I _think_ the problem lies in the call to `glScissor` in [nuklear_glfw_gl3.h:264](https://github.com/vurtun/nuklear/blob/master/demo/glfw_opengl3/nuklear_glfw_gl3.h#L264). I was able to get the expected output by changing line 266 from:

``` C
(GLint)((glfw.display_height - (GLint)(cmd->clip_rect.y + cmd->clip_rect.h)) * glfw.fb_scale.y),
```

to

``` C
(GLint)((glfw.height - (GLint)(cmd->clip_rect.y + cmd->clip_rect.h)) * glfw.fb_scale.y),
```

That is, the `height` is already being scaled by `glfw.fb_scale.y`, and thus the use of `display_height` is unnecessary. Unfortunately I am not familiar enough with OpenGL to be confident in my answer, so I leave this up to you.

**Comment by vurtun** [comment]
Hey,
> Unfortunately I am not familiar enough with OpenGL to be confident in my answer, so I leave this up to you.

There is a high possibility that your solution is correct since I do not have a High DPI screen and no access to one to test it out. I will change it and see if anyone gets problems with it.

**Comment by mhroth** [comment]
Sounds good. All I can say is, "it worked for me", and "the fix makes sense to me". I'm just not sure if there would be a consequence that I am not otherwise familiar with. Thank you for your work!
