### ISSUE TITLE
nk_edit_string bugs

### ISSUE THREAD

**Issue by MusorGaming** [vurtun/nuklear#136]
Ok, this control has a lot of bugs.
If we have three lines of text, where second line is just newline:
```
line one

line three
```

1. Selecting text from first line to third line will make the second line disappear.  (text rendering bug?)
2. If the caret is positioned at the end of first line pressing DOWN_KEY will move caret directly to the start of line three
3. Home/end keys bring caret to start/end of the string instead of start/end of the line
4. nk_edit_string control can only gain focus if it's 100% not clipped. If it's clipped even slightly clicking on it won't give it focus.

**Comment by vurtun** [comment]
Thanks for the issue.
> 1) Selecting text from first line to third line will make the second line disappear. (text rendering bug?)
> 2) If the caret is positioned at the end of first line pressing DOWN_KEY will move caret directly to the start of line three

Small self inflicted bug which overstepped `\n`. Should be fixed now and hopefully does not cause any side effects.

> 3) Home/end keys bring caret to start/end of the string instead of start/end of the line

if you want to change the used key please look inside the platform library part `nuklear_xxx.h` inside the demos.

> 4) nk_edit_string control can only gain focus if it's 100% not clipped. If it's clipped even slightly clicking on it won't give it focus.

I changed the behavior, but I am not 100% sure this is a good idea. Will have to look in the future if it works out correctly and does not introduce any bugs.

**Comment by MusorGaming** [comment]
Thank you!
