### ISSUE TITLE
Bug in one of examples (opening the pie menu while having an combo box open)

### ISSUE THREAD

**Issue by Horrowind** [vurtun/nuklear#138]
To reproduce start "./extended" and click on one of the combo boxes. With the drop-down thingy open now right-click on the second window to open the pie menu. The application then asserts

extended: ../nuklear.h:18536: nk_popup_end: Assertion `popup->parent' failed.

I have not yet looked into the issue, it was just something I noticed when updating to the latest master.

Thanks for your time!

**Comment by vurtun** [comment]
Thanks for the issue. Not really I bug per se just the assert was wrong. I changed it to a `if` condition and polished the piemenu a little bit more to not crash.
