### ISSUE TITLE
Suggestion - rename function pointer "free" name in nk_allocator to resolve name collisions

### ISSUE THREAD

**Issue by MusorGaming** [vurtun/nuklear#139]
I'm using a stb_leakcheck which redefines free as a macro which conflicts with function pointer free invocations.

Name conflict:
`b->pool.free(b->pool.userdata, b->memory.ptr);`

Proposed change (or similar):
`b->pool.free_fun(b->pool.userdata, b->memory.ptr);`

```
struct nk_allocator {
    nk_handle userdata;
    void*(*alloc)(nk_handle, void *old, nk_size);
    void(*free_fun)(nk_handle, void*);
};
```

Perhaps there's another sensible workaround which doesn't involve changing nuklear?

**Comment by vurtun** [comment]
This is a special case and I would prefer not to change the API just for these cases, it is something I should have done beforehand. So I would suggest renaming it in your version.
