### ISSUE TITLE
NK_KEY_LINE_START in nk_textedit_key doesn't work if cursor is at the end of the text

### ISSUE THREAD

**Issue by MusorGaming** [vurtun/nuklear#140]
If the cursor is positioned at the end of the text when using nk_edit_string, NK_KEY_LINE_START leaves the cursor at the end of the text. Looks like bug.

**Comment by vurtun** [comment]
Depending on which demo you are using I did not set the key binding. Which one did you use?

**Comment by MusorGaming** [comment]
I changed bindings to work correctly with HOME and END buttons.
This appears to be bug in logic of nk_textedit_key, when processing NK_KEY_LINE_START when the cursor is at the end of text.

Namely nk_textedit_find_charpos is called which looks for end-of-line char, which is not found when cursor is at the end of text.
