### ISSUE TITLE
Backspace Key doesn't work with nk_filter_ascii and nk_filter_default

### ISSUE THREAD

**Issue by aestamper** [vurtun/nuklear#147]
As stated in the title, backspace does not work at all for either nk_filter_ascii or nk_filter_default. The delete key works fine however, which is strange. I have tried changing the code in nuklear.h to return nk_false when a backspace character is received, for example:

    NK_API int
    nk_filter_ascii(const struct nk_text_edit *box, nk_rune unicode)
    {
        NK_UNUSED(box);
        if (unicode > 128 && unicode == '\b') return nk_false;
        else return nk_true;
    }

Any ideas on how to fix this? For the time being I have had to just add a button that will clear the buffer.

EDIT: I also should have probably specified that I am having this issue with an edit text box using nk_edit_string.

**Comment by vurtun** [comment]
I am not 100% sure what you are doing, but backspace is handled as a key inside `nk_edit_string` and not as text input so it has to be filtered out. Do you use one of my platform demos (if so which one) or do you use your own backend?

**Comment by aestamper** [comment]
I have been using your allegro demo backend in order to implement my own custom widget for practice. The problem seems to be with the allegro implementation. I just tried it with the X11 demo backend and backspacing works as expected. You can see what I'm talking about if you try and use your overview widget with allegro and try to input normal text.

**Comment by aestamper** [comment]
That fixed it! Thanks.

**Comment by bharadwaj-raju** [comment]
This doesn't work in SFML either.

Fix:

```cpp
// nuklear_sfml_gl2.h line 338 and onward
else if(evt->type == sf::Event::TextEntered) {
        if (evt->text.unicode != 8) {
            // no backspace
            nk_input_unicode(ctx, evt->text.unicode);
        }
        return 1;
```
@vurtun I can create a pull request if you want

**Comment by dumblob** [comment]
Just make the pull and after review (e.g. from @eax0r or me) I'll merge it. It might take some time though as I'm currently out of time pretty much like @vurtun is. The good thing is, that the PR won't get forgotten, but just delayed :wink:.

**Comment by bharadwaj-raju** [comment]
@dumblob PR created. Sorry for the delay.
