### ISSUE TITLE
missing definitions

### ISSUE THREAD

**Issue by benswift** [vurtun/nuklear#148]
It looks like there are a few prototypes which are missing their implementations:

- `nk_color_hsv_b`
- `nk_color_hsva_b`
- `nk_strmatch_fuzzy_string`

Are these supposed to be user-implemented? Or am I just doing something dumb in looking for them?

**Comment by vurtun** [comment]
> Are these supposed to be user-implemented? Or am I just doing something dumb in looking for them?

Nope this is just me being an idiot while declaring and implementing functions. Should be fixed now.

**Comment by benswift** [comment]
> Nope this is just me being an idiot while declaring and implementing functions. Should be fixed now.

Ah, we've all been there :) Thanks.
