### ISSUE TITLE
ffi bindings and passing structs by value

### ISSUE THREAD

**Issue by benswift** [vurtun/nuklear#150]
I'd like to use nuklear from a (LLVM) JIT-compiled language, which requires building a shared library and dynamically linking against `libnuklear`. I realise this is a little outside the design goals of the project, so I'm willing to jump through some hoops to try and get it to work.

I've got the basic stuff working ok, but the thing which causes issues is passing structs by value. The language the bindings are in doesn't stick to the x64 ABI for passing structs by value (which involves passing small structs in registers as far as I can tell).  It's not worth the hassle to try and get it to pass things properly, since that'd be a fragile headache.

Anyway, the obvious solution is to modify the nuklear API to pass all structs by reference (it's mostly `nk_color` where this is an issue). I guess my question is: has anyone else tried to call nuklear through an FFI and run into similar problems? Any gotchas to be aware of? If I do go down this route, I'm happy to contribute the code back upstream, although since it's a bit of a strange case then maybe it's not worth the increased complexity.

**Comment by Spasi** [comment]
LWJGL 3 added nuklear bindings (Java/JNI) recently, the generated code is [here](https://github.com/LWJGL/lwjgl3-generated/blob/master/c/nuklear/org_lwjgl_nuklear_Nuklear.c).

For parameters, we pass a pointer to the struct from Java, which is then dereferenced in the JNI code.

For return values (e.g. `nk_window_get_bounds`), we generate an extra `__result` parameter, which is also a pointer to memory where the returned struct value will be stored.

**Comment by benswift** [comment]
Great, thanks for the heads up, I've been experimenting with wrappers like that. What tool do you use to generate the wrappers? The language/tooling I'm using is a little (well, a lot really) less mature than Java, so it doesn't have as nice a story for this sort of thing, but perhaps I can piggyback off those tools.

**Comment by Spasi** [comment]
It's a [custom solution](https://github.com/LWJGL/lwjgl3/tree/master/modules/generator/src/main/kotlin/org/lwjgl/generator) written in Kotlin, so probably not that useful to you. In theory you could hack it to make it generate code for your language, but it won't be easy. The inputs for nuklear are the [type definitions](https://github.com/LWJGL/lwjgl3/blob/master/modules/templates/src/main/kotlin/org/lwjgl/nuklear/NuklearTypes.kt) and the [template](https://github.com/LWJGL/lwjgl3/blob/master/modules/templates/src/main/kotlin/org/lwjgl/nuklear/templates/nuklear.kt). The outputs are the JNI code linked above and the corresponding [Java sources](https://github.com/LWJGL/lwjgl3-generated/tree/master/java/org/lwjgl/nuklear).

**Comment by benswift** [comment]
Yep, I figured.  I have an 80% solution based on semantic-mode (an emacs
lisp C parser) so I think I'll just keep working on that.

Thanks heaps for your help.
