### ISSUE TITLE
Add support for images with GDI backend

### ISSUE THREAD

**Issue by fb39ca4** [vurtun/nuklear#153]

**Comment by vurtun** [comment]
"Please add a PR for image support for the GDI backends". But seriously I am always grateful for issues but please at least conform to some basic politeness and write something like "Please add support for images with GDI backend" and then a short text (even if it is only a sentence) why you think it is important (can even be trivial like: "All other demos have it could you add it to the GDI backend as well"). Or if you want to be a little bit more helpful and are able to solve the issue provide a PR for it. 
As for image support it is probably easier for you to add then for me. I don't have a windows machine at the moment and would need to set that up. Even the problem in itself could be `googled` in a second. This is what I found for the first link: http://stackoverflow.com/questions/1748470/how-to-draw-image-on-a-window. However if you are **really** not able to do it then I will take a look.

**Comment by fb39ca4** [comment]
My apologies. At the time, whatever I wrote in the description seemed redundant, so I left it out, but now I can see that was rude.

I've made an attempt at getting it to work, although it is not very elegant. I'll eventually create a pull request for it.

**Comment by dumblob** [comment]
@fb39ca4, it looks like the support for images in the GDI backend landed (https://github.com/vurtun/nuklear/commit/5aeddddd742764fac03fe6b453b7a3508efe2642 ).
