### ISSUE TITLE
Key press typo in nuklear_glfw_gl3.h?

### ISSUE THREAD

**Issue by mhroth** [vurtun/nuklear#158]
Should [this line](https://github.com/vurtun/nuklear/blob/master/demo/glfw_opengl3/nuklear_glfw_gl3.h#L392) at `nuklear_glfw_gl3.h:392` be:

`glfwGetKey(win, GLFW_KEY_RIGHT_CONTROL) == GLFW_PRESS) {`

instead of 

`glfwGetKey(win, GLFW_KEY_RIGHT_CONTROL)) {`

**Comment by vurtun** [comment]
Thanks for the issue. It was a typo which caused the condition to fall through and execute on key repeat as well. Luckily my code only reacts on state changes so this should hopefully not have caused any bugs.
