### ISSUE TITLE
release tags?

### ISSUE THREAD

**Issue by Extrawurst** [vurtun/nuklear#160]
I just by accident found this release 1.0 commit: https://github.com/vurtun/nuklear/commit/b2c87ed7c0dd8b1fb30380eb9c6ac080c0d3523a

Do you plan to use git tags for releases anytime? These imho important messages as for 1.0 would not be as easily lost in all those commits when being a github "release"

**Comment by vurtun** [comment]
I answered the question here #157 (second reply from me). tl;dr: commit `Release Version 1` is not really a git release version but more of a indicator that Nuklear's API is now stable (the whole commit was a mistake I should have split it up but a little bit more and not called it `Release`.

**Comment by Extrawurst** [comment]
the question still stands: Do you plan to use git tags for releases at any point?

**Comment by vurtun** [comment]
I don't use releases because don't really see why.  I don't plan on adding big features or breaking changes anymore and if I encounter bugs I will fix and just push them directly.

**Comment by mdparker** [comment]
Release tags are extremely useful for those distributing projects that use Nuklear, bindings for other languages in particular (which, I believe, is what @Extrawurst is maintaining). Without release tags, maintainers either have to point users to the last known Nuklear commit hash that is known to be compatibile, or bundle it with their project. Neither is an ideal solution. Release tags simplify the process.

**Comment by dumblob** [comment]
I must agree on this with @mdparker . It also highly positively influences project's maturity perception of people not following every single commit (which is nearly noone).
