### ISSUE TITLE
Support of OpenGL ES 2.0

### ISSUE THREAD

**Issue by ytsarko** [vurtun/nuklear#162]
Hi!

Is it possible to use nuklear built-in NK_INCLUDE_VERTEX_BUFFER_OUTPUT rasterizer to support OpenGL ES 2.0 drawing? Currently I am having troubles with drawing on ES 2.0 device for currently unidentified reason (I've spent 4 days battling with this issue). I suppose it has something to do with elements/vertices lists.

What I did is took your demo for SDL+OpenGl 2 and ported it to OpenGL ES 2.0 environment. I went further and simplified fragment shader to perform only solid fill with vertex color, without texturing. In the attachment you will find the actual code.

My UI drawing function looks like following (I had to reduce it to a bare minimum to build a minimal reproducible fragment):

> 
{struct nk_panel layout;
if (nk_begin(ctx, &layout, "Demo", nk_recti(30,30,1200,700), 0))
{
    struct nk_command_buffer *canvas = nk_window_get_canvas(ctx);
    nk_fill_rect(canvas, nk_recti(100, 100, 100, 100), 0, nk_rgb(255, 0, 0));
} nk_end(ctx);}

The window itself is drawn, but 100x100 red rectangle is not.
The overall number of vertices/elements is 12/8, so I do not think that some OpenGl ES limitation on geometry size is a reason.

[nk-gl.c.txt](https://github.com/vurtun/nuklear/files/308879/nk-gl.c.txt)

**Comment by sabotage3d** [comment]
Hi is there any progress on this? I would like to use this on mobile as well.

**Comment by ytsarko** [comment]
@sabotage3d: Actually, after long and hard debug sessions I have concluded that this was an OpenGL driver bug (particularly it was Mali-400 GPU). This was confirmed by Mali team member: https://community.arm.com/message/37674?et=watches.email.thread#37674
Actually, I was able to compile and launch native C app using nuklear on Android device (PowerVR GPU) and it worked well. I am closing this ticket since it is no more relevant.

**Comment by sabotage3d** [comment]
Thanks is there an example on how to build it properly for Android?

**Comment by ytsarko** [comment]
In the initial post on provided community.arm.com topic I`ve attached workable demo program (MyApplication.tar.gz), please feel free to use it. It is Android Studio 2.0 project if I recall it correctly.

**Comment by sabotage3d** [comment]
Thanks I will try it out.

**Comment by dumblob** [comment]
@ytsarko could you please upload the demo source somewhere to your github account (e.g. as a Gist)? I was unable to find the topic you mentioned and therefore could not find `MyApplication.tar.gz`.

**Comment by ytsarko** [comment]
@dumblob sure, especially for you I`ve set up GitHub repository: https://github.com/ytsarko/nuklear-android-ndk-sample

Feel free to use it, the most interesting part is in folder MyApplication/app/src/

**Comment by sabotage3d** [comment]
Thanks. I am having problem with glBindVertexArray as it is not supported on some of the phones that I am testing on. Is there alternative?

**Comment by ytsarko** [comment]
@sabotage3d [It appears that](https://www.khronos.org/opengles/sdk/docs/man3/html/glBindVertexArray.xhtml) that **glBindVertexArray** is only supported starting from OpenGL ES 3.0. You have basically 2 options: either find out whether your phone models support ES 3.0 or rewrite that code without glBindVertexArray. [Here](http://stackoverflow.com/questions/31412773/how-to-use-vaos-in-opengl-es-2-0#comment50801632_31412773) you can find some tips.

**Comment by procedural** [comment]
@ytsarko Curious to repro your bug on my Mali-400 device, but why did you attached `MyApplication.tar.gz` on ARM forum with a `glBindVertexArray` call if Mali-400 supports only OpenGL ES 2.0?

**Comment by litlight** [comment]
Help, can anyone tell me in the  https://github.com/ytsarko/nuklear-android-ndk-sample, where should i put the main function which contains poll_event and nk_begin.
