### ISSUE TITLE
Typo: NK_EDIT_COMMITED

### ISSUE THREAD

**Issue by wasamasa** [vurtun/nuklear#166]
This should obviously be `NK_EDIT_COMMITTED` instead.

**Comment by vurtun** [comment]
Thanks for opening an issue. Another embarrassing typo which even inside the API. Problem is that changing it would cause breaking working code. I think in the future I will create one commit were I will fix all naming issues in one go.

**Comment by wasamasa** [comment]
Yeah, that's why I wasn't sure whether to bother doing a pull request.

**Comment by irtusb** [comment]
maybe you could just fix them all and add #defines to provide some kind of backward compatibility if it worries you so much. You can add some noise with #warnings or similar preprocessor instructions to indicate user that wrong verb will be removed in the future

**Comment by vurtun** [comment]
I will probably not fix this. The typo is there and it is not breaking anything so I will leave it for now.
