### ISSUE TITLE
`null` is used as a keyword in many languages

### ISSUE THREAD

**Issue by mogud** [vurtun/nuklear#170]
In struct nk_convert_config and nk_draw_list, i found fields named `null`, but it is used in many languages as a keyword. So use it as a field's name is not so good for other languages' bindings. Also, null is not good at representing something correctly.

**Comment by mogud** [comment]
Also in struct nk_command_text, `string` is used as a field name.

**Comment by vurtun** [comment]
I had some of these naming issues, but I don't want to change the API just to rename some variables/fields. It is something I should note for the future but I think I will keep it as it as for now.
