### ISSUE TITLE
Request: write both a changelog and version number in header

### ISSUE THREAD

**Issue by r-lyeh** [vurtun/nuklear#183]

**Comment by vurtun** [comment]
Yeah is probably a good idea. For now I will put the changelog and version number inside the header. But it is probably a good idea to later move the changelog into its own file if it becomes to big.

**Comment by dumblob** [comment]
Recently I noticed the versioning scheme doesn't feel intuitive at all (1.0 being followed by 1.01; [1.03 being followed by 1.031](https://github.com/vurtun/nuklear/commit/c87a55cf56e7997b2817326d797b39082bdbd095 ) - btw the commit comment says 1.04 to add to the confusion).

Would it be possible to switch to [Semver](http://semver.org/ )?

**Comment by dumblob** [comment]
@vurtun any thoughts on [Semver](http://semver.org/ )? The sooner the versioning will settle down, the better for users.
