### ISSUE TITLE
Color picker has a hole

### ISSUE THREAD

**Issue by rokups** [vurtun/nuklear#186]
Upon implementing [nuklear subsystem for urho3d](https://github.com/rokups/Urho3D-nuklear-ui) game engine i noticed color picker has 1px wide strip on the right side which cuts a hole in control and thus background is visible. Test code is copied from [demo/sdl_opengl3/main.c](https://github.com/vurtun/nuklear/blob/master/demo/sdl_opengl3/main.c)

![](https://github.com/rokups/Urho3D-nuklear-ui/raw/master/screenshot.png?raw=true)

**Comment by vurtun** [comment]
Hey thanks for the issue.
Does it stile exist after the last two commits? I tried to solve it but if still persists I need to take a secon look.

**Comment by rokups** [comment]
It is still there.

**Comment by vurtun** [comment]
Thanks, I checked again and was able to replicate the issue. Was a little bit more complex than first thought but hopefully the problem is now fixed. Could you test again and make sure it works for you as well?

**Comment by rokups** [comment]
Yes you nailed it, thanks!
