### ISSUE TITLE
instructions to compile node editor demo

### ISSUE THREAD

**Issue by no-glue** [vurtun/nuklear#187]
can you provide instructions to compile node editor demo?

**Comment by wasamasa** [comment]
- `cd demo/<implementation>`
- `vim main.c # remove comments related to node_editor.c`
- `make`
- `bin/demo`

**Comment by no-glue** [comment]
demo/<implementation>? there are library folders and .c files for demos.

**Comment by vurtun** [comment]
All directories inside the demo folder are not the actual libraries but the frontend implementation for each library. Each frontend consists of one `main.c` user code file and one nuklear frontend single header implementation file. If you run main.c you get a simple demo and like @wasamasa said if you uncomment lines `#include node_editor.c` and `node_editor(ctx)` and run the demo again you get the node editor.
I hope this helps if not feel free to ask.

**Comment by no-glue** [comment]
got it.
