### ISSUE TITLE
Gdi demo not building

### ISSUE THREAD

**Issue by varunasingh** [vurtun/nuklear#190]
Errors include: 'd311' undeclared 

Just running the build batch file. Am I supposed to test it some other way ?

**Comment by vurtun** [comment]
Thanks for create the issue, this is a stupid copy & paste error and since I don't use gdi/gdip at the moment I didn't notice. I pushed a new commit hopefully fixing the issue.

**Comment by varunasingh** [comment]
Thanks, Just pulled and checked. One small complain about warnings being treated as errors. 
In the build.bat file if you remove /WX, it builds properly (relevant: https://msdn.microsoft.com/en-us/library/ksk5k0ta.aspx) 

ie:
cl /nologo /W3 /WX /O2 /fp:fast /Gm- /Fedemo.exe main.c user32.lib gdi32.lib /link /incremental:no

Remvoe the /WX

cl /nologo /W3 /O2 /fp:fast /Gm- /Fedemo.exe main.c user32.lib gdi32.lib /link /incremental:no

**Comment by vurtun** [comment]
Good idea. I did not notice /WX is in there. I think I removed it in my own bat but did not remove from the demo. I pushed a new commit which removes the flag from d3d11/gdi/gdip bat and it everything hopefully just compile without a problem.

**Comment by dumblob** [comment]
@varunasingh wouldn't it be better to eliminate the warnings instead of ignoring them?

**Comment by vurtun** [comment]
@dumblob sure but usually /WX is not a good idea either way (except for debug mode). So yes it would be better to fix all warnings but I cannot guarantee that I will be able fix new warnings or warning from different version of visual studio.

**Comment by varunasingh** [comment]
I agree with @vurtun however it would be ideal to fix them in the future. I can have a go at it later. As of this issue, gdi is building all OK now.
