### ISSUE TITLE
How to snap nuklear windows to root (os) window?

### ISSUE THREAD

**Issue by Losiara** [vurtun/nuklear#191]
Need to resize "inner" windows when resize outer. Is there such option?

**Comment by vurtun** [comment]
At the moment there is no notion of the OS window inside nuklear so there is no direct option to react on size or position changes. It is probably a good idea to provide a way in the future as for right now you could check for a resize event in your code and directly set window positon and size corresponding to the change. It would be a quick and dirty fix atleast for now.
