### ISSUE TITLE
Lots of errors when compiling as C++

### ISSUE THREAD

**Issue by Tirus42** [vurtun/nuklear#193]
I am using nuklear in a C++ project.
Today the build with the current nuklear version breaks with
nuklear.h:2536:1: error: template with C linkage
when I try to build it.
(Last successful build was with a nuklear version from last week).

Even if I try to build a minimal example I get a lot of errors.

Minimal example:
#define NK_IMPLEMENTATION
#include "nuklear.h"

int main() {
    return 0;
}

**Comment by Tirus42** [comment]
Looks like c84b2f9a960c67196d4548a03e0964b4bed623e6
is the last working version.

**Comment by vurtun** [comment]
Thanks for the issue I just pushed a new commit that fixes the problem.
