### ISSUE TITLE
Resizing windows is hard

### ISSUE THREAD

**Issue by rokups** [vurtun/nuklear#196]
Currently when we resize windows cursor must stay within scaler rect in order for window to resize. Once cursor goes out of bounds window stops resizing even if mouse button is not released. That is not how GUI common toolkits work. Window should stop resizing only when mouse button is released not taking into account mouse position. This is way more problematic when window is constrained to being resized only horizontally or vertically as mouse cursor has to stay in narrow straight line.

**Comment by vurtun** [comment]
This is quite an old problem and a result of having no state. But I got an idea and a possible solution. I pushed a new commit hopefully fixing the issue.

**Comment by rokups** [comment]
Hmm i tried latest master.. And it still works exactly the same. But hey.. Clearly there is some state. After all windows save their sizes etc.. Heck maybe we could do something like save window that currently is being resized in a global state when mouse is clicked and is in the rect of the resize handle and clear that value only when mouse is released? Then we could easily check `if (ctx->resizing_window == current_window)` and do resizing or not. Does that make sense?

**Comment by vurtun** [comment]
Hm strange. The wrong behavior I thought you mean is now gone. What exactly did you mean? Do you mean the cursor should always hover while moving/resizing then that can be fixed by using a software cursor instead of hardware cursor.

**Comment by rokups** [comment]
I am talking about this code

        /* do window scaling */
        if (!(window->flags & NK_WINDOW_ROM)) {
            float prev_x = in->mouse.prev.x;
            float prev_y = in->mouse.prev.y;
            struct nk_vec2 window_size = style->window.min_size;
            int incursor = NK_INBOX(prev_x,prev_y,scaler_x,scaler_y,scaler_w,scaler_h);

            if (nk_input_is_mouse_down(in, NK_BUTTON_LEFT) && incursor) {
                window->bounds.w = NK_MAX(window_size.x, window->bounds.w + in->mouse.delta.x);
                /* dragging in y-direction is only possible if static window */
                if (!(layout->flags & NK_WINDOW_DYNAMIC))
                    window->bounds.h = NK_MAX(window_size.y, window->bounds.h + in->mouse.delta.y);
                ctx->style.cursor_active = ctx->style.cursors[NK_CURSOR_RESIZE_TOP_RIGHT_DOWN_LEFT];
            }
        }

Specifically `incursor` check. It checks if cursor is over the scaling handle. If i move mouse too fast while holding left button it will move out of scaling handle rect, check will fail and scaling will stop even if i did not release mouse button.

**Comment by vurtun** [comment]
OK now I now what you mean. I took the dragging hack from window moving/properties and slider and added it to the window scaler. I hopefully this is now fixed.

**Comment by rokups** [comment]
That did the trick, thank you
