### ISSUE TITLE
2 hardcoded memset() calls (in nk_clear, nk_chart_end)

### ISSUE THREAD

**Issue by floooh** [vurtun/nuklear#205]
I just stumbled over 2 hardcoded memset() calls, one is in **nk_clear()**, the other in **nk_chart_end()**, not critical, for now I'll simply include the right header before including nuklear.h :)

**Comment by vurtun** [comment]
Thanks! Fixed it in f288188a724e9c296a75119228d437266002935b. Embarrassingly overlooked these two.
