### ISSUE TITLE
Request: make varargs available without fopen etc...

### ISSUE THREAD

**Issue by floooh** [vurtun/nuklear#206]
Minor request, but useful for unusual platforms like emscripten or PNaCl:

Currently there's only the NK_INCLUDE_STANDARD_IO which is mainly useful to include or exclude the fopen etc... function (I have this undefined, because I don't want to have fopen etc... in Oryol), however if NK_INCLUDE_STANDARD_IO is disabled, all the public functions which use varargs are also disabled (e.g. nk_labelf() ).

IMHO it would be useful to move varargs out of NK_INCLUDE_STANDARD_IO (for instance NK_INCLUDE_STANDARD_VARARGS).

**Comment by vurtun** [comment]
I pushed a new commit dividing the functionality of `NK_INCLUDE_STANDARD_IO` into two by adding `NK_INCLUDE_STANDARD_VARARGS`. I probably should have done this from the start but I did not think that it would cause problems. Something to take away is probably to directly split up things from the beginning,even if it seems unlikely at the time that it is needed.

**Comment by floooh** [comment]
Works nicely, thanks!
