### ISSUE TITLE
Compiling Without NK_INCLUDE_FIXED_TYPES Fails

### ISSUE THREAD

**Issue by CaptainKraft** [vurtun/nuklear#208]
When attempting to compile without NK_INCLUDE_FIXED_TYPES defined I get the following error:

* nuklear.h:322:9: error: unknown type name 'NK_UINT32'

**Comment by vurtun** [comment]
Thanks for the issue. Hopefully is now fixed with commit e7eb3663320b22a7c4c47982c5f15c70cb30287d.
