### ISSUE TITLE
UTF-8 Support

### ISSUE THREAD

**Issue by star-tek-mb** [vurtun/nuklear#211]
Hello all! I started using this awesome toolkit. I have been looking for multilanguage text. My code:
~~~c
struct nk_panel layout;
        if (nk_begin(ctx, &layout, "Настройки", nk_rect(200, 200, 210, 150), NK_WINDOW_BORDER | NK_WINDOW_MOVABLE | NK_WINDOW_TITLE)) {
			struct nk_panel combo;
			nk_layout_row_dynamic(ctx, 20, 1);
			nk_label(ctx, "Цвет фона:", NK_TEXT_LEFT);
			nk_layout_row_dynamic(ctx, 25, 1);
			if (nk_combo_begin_color(ctx, &combo, background, 400)) {
				nk_layout_row_dynamic(ctx, 120, 1);
				background = nk_color_picker(ctx, background, NK_RGBA);
				nk_layout_row_dynamic(ctx, 25, 1);
				background.r = (nk_byte)nk_propertyi(ctx, "#R:", 0, background.r, 255, 1,1);
				background.g = (nk_byte)nk_propertyi(ctx, "#G:", 0, background.g, 255, 1,1);
				background.b = (nk_byte)nk_propertyi(ctx, "#B:", 0, background.b, 255, 1,1);
				background.a = (nk_byte)nk_propertyi(ctx, "#A:", 0, background.a, 255, 1,1);
				nk_combo_end(ctx);
            }
        }
        nk_end(ctx);
~~~

And there is screenshot:
![2016-08-13 14-14-42](https://cloud.githubusercontent.com/assets/12962448/17642432/6acbd86a-6160-11e6-9bdd-64356b1e0540.png)

Also I using ubuntu bold font.
I look for function nk_label and see - nk_utf_len havent been used.
Please help developers!

P.S: sorry for my english

**Comment by vurtun** [comment]
Hey thanks for your issue,
from what I can make out of your problem is that you tried to do `nk_font_atlas_load_from_file` or `nk_font_atlas_load_from_memory` on your font with default font configuration.

For fonts to work with other languages outside ASCII you have to fill a `nk_font_config` struct and pass it to either `nk_font_atlas_load_from_file` or `nk_font_atlas_load_from_memory` (note the default font only uses ASCII so you have to use your own font in your case the ubuntu font).
So since I know it is quite shitty to read and understand things I will just provide a simple example on how to get cyrillic font:

This example should be directly copied to your font loading code: 
```c
    struct nk_font_atlas *atlas;
    struct nk_font_config config = nk_font_config(14);
    config.oversample_h = 1;
    config.oversample_v = 1;
    config.range = nk_font_cyrillic_glyph_ranges();
    
    nk_sdl_font_stash_begin(&atlas);
    struct nk_font *ubuntu = nk_font_atlas_add_from_file(atlas, "path_to_your_font", 14, &config)
    nk_sdl_font_stash_end();
    nk_style_set_font(ctx, &ubuntu->handle);
```

In this particular case the `config.range = nk_font_cyrillic_ranges()` provides you with correct glyphs which should produces the correct output. The `range` in this case are the unicode codepoints to load from the truetype font since it does not make sense to load all glyphes out of a font (requires to much memory).

**Comment by star-tek-mb** [comment]
Thanks. I haven't spend more time on nuklear code. My bad. Can I load all printable glyphs? Memory is not problem.

**Comment by vurtun** [comment]
I don't think you want to do that. There are 2^32 possible glyphs and I would recommend using what I just showed with `nk_font_cyrillic_glyph_ranges()` which includes both ASCII as well as Cyrillic. If you _REALLY_ want to load everything (again please don't do that) you have to define your own ranges. For example ASCII + Cyrillic font ranges look like this:

```c
static const nk_rune example_range[] = {
    0x0020, 0x00FF, /* ASCII*/
    0x0400, 0x052F,
    0x2DE0, 0x2DFF,
    0xA640, 0xA69F,
    0, /* zero terminates ranges */
};
```
So you would have to set it to {0x0020, 0xFFFFFFFF,0} but this will probably create a massive font atlas texture and glyph array which I _REALLY_ cannot recommend!.

**Comment by star-tek-mb** [comment]
Thanks. Then I will depend on chosen language.

**Comment by star-tek-mb** [comment]
Sorry again **vurtun**. I need some help.
My code:
~~~c
struct nk_context *ctx = nk_sdl_init(window);
struct nk_color background = nk_rgb(28, 48, 62);
struct nk_font_atlas *atlas;
struct nk_font_config fconfig = nk_font_config(14);
fconfig.range = nk_font_cyrillic_glyph_ranges();
nk_sdl_font_stash_begin(&atlas);
struct nk_font *ubuntu = nk_font_atlas_add_from_file(atlas, "fonts/Ubuntu.ttf", 14, &fconfig);
nk_sdl_font_stash_end();
nk_style_set_font(ctx, &ubuntu->handle);
// ... cycle
	struct nk_panel layout;
        if (nk_begin(ctx, &layout, "Settings", nk_rect(200, 200, 210, 150), NK_WINDOW_BORDER | NK_WINDOW_MOVABLE | NK_WINDOW_TITLE)) {
		struct nk_panel combo;
		nk_layout_row_dynamic(ctx, 25, 1);
                nk_property_int(ctx, "Weapon", 0, &current, 9, 1, 0);
		nk_layout_row_dynamic(ctx, 20, 1);
		nk_label(ctx, "Background", NK_TEXT_LEFT);
		nk_layout_row_dynamic(ctx, 25, 1);
		if (nk_combo_begin_color(ctx, &combo, background, 400)) {
			nk_layout_row_dynamic(ctx, 120, 1);
			background = nk_color_picker(ctx, background, NK_RGBA);
			nk_layout_row_dynamic(ctx, 25, 1);
			background.r = (nk_byte)nk_propertyi(ctx, "#R:", 0, background.r, 255, 1,1);
			background.g = (nk_byte)nk_propertyi(ctx, "#G:", 0, background.g, 255, 1,1);
			background.b = (nk_byte)nk_propertyi(ctx, "#B:", 0, background.b, 255, 1,1);
			background.a = (nk_byte)nk_propertyi(ctx, "#A:", 0, background.a, 255, 1,1);
			nk_combo_end(ctx);
                }
        }
        nk_end(ctx);
	nk_sdl_render(NK_ANTI_ALIASING_ON, MAX_VERTEX_MEMORY, MAX_ELEMENT_MEMORY);
~~~
But i get:
![2016-08-14 16-43-06](https://cloud.githubusercontent.com/assets/12962448/17648875/36319732-623e-11e6-8a7f-48bcb9a8efa8.png)

I have no text also in ASCII.

**Comment by vurtun** [comment]
Ah you found a bug. This happens if you do to many changes, nothings works in the end. I found the problem and fixed hopefully fixed it.
