### ISSUE TITLE
How to correctly compute the bounds of a window? (for blocking/handling events)

### ISSUE THREAD

**Issue by ewmailing** [vurtun/nuklear#212]
I am trying to correctly handle/block input. I am building a UI on top of my main scene. What I want is when the user clicks on anything that intersects with a Nuklear widget, I want Nuklear to handle the event and block the event from being handled by the scene underneath. If the user clicks on the scene were there is no Nuklear widget, the scene should process the event as normal.

I'm not sure what the best way to do this is, but I've been using nk_window_get_bounds() to figure out if the click intersects the GUI or not. This mostly works, but I've found some edge cases:

- If the window is minimized, the bounds still reports the full window size.

- For Combo Boxes, when they are too large and go outside the window (e.g. too far below), the bounds do not reflect this and I end up failing to block the event to the underlying scene.

Also, kind of related, but I'm also wondering the best approach to dealing with edit_string fields (to decide whether my underlying scene handles or ignores the event).

**Comment by vurtun** [comment]
I anwered this question here: #189
