### ISSUE TITLE
Mouse wheel doesn't do anything for popup & combo

### ISSUE THREAD

**Issue by ewmailing** [vurtun/nuklear#223]
I expect the mouse wheel to scroll in popups and combos, but it doesn't seem to do anything.

The file browser demo respects the mouse wheel, but the image popup (with the dogs) or combo boxes with long lists do not.

**Comment by vurtun** [comment]
Thanks for the issue I added mouse scrolling to non-blocking and blocking popups, including combo boxes, contextuals and menus in commit: cf272fa2653ffaa505b1da74a7046e64c4c4eeb1.

**Comment by ewmailing** [comment]
Thank you. That is working great!

**Comment by ewmailing** [comment]
I'm not sure if this is a different issue, but I just noticed that the aforementioned filebrowser code is no longer scrolling for me via mouse wheel. I also noticed there is no scrollbar any more and the layout has changed slightly. (I am using a forked version of the browser where I added Open/Save/Cancel buttons and a textfield at the bottom. I used to have padding at the bottom for these widgets, but now they are completely on the bottom.)

**Comment by vurtun** [comment]
The last commit introduced a shit ton of bugs drawing and otherwise since I rewrote one of the more complex parts of the library. There are still some issues left to fix but commit: 550a2b03d3f3b8b114c736fd6b2109075b333ea3 should fix some of the more significant once. At least for me mouse wheel seems to work in the file browser now.

**Comment by ewmailing** [comment]
Thanks. The scrolling for the file browser is working for me again. The minor layout differences in the file browser don't concern me. (Only the cracks in the combo box mentioned in the other issue seem to be problem for me.)

**Comment by vurtun** [comment]
> (Only the cracks in the combo box mentioned in the other issue seem to be problem for me.)

Yes I am currently working on it. But I couldn't find any fast fix. Strangely enough the cracks only appear in the vertex buffer based demos and not under `xlib`. They are also all just one pixel high or long which is quite strange. I will investigate further and fix it ASAP.
