### ISSUE TITLE
Way to customize/change the Vertex Buffer packing?

### ISSUE THREAD

**Issue by ewmailing** [vurtun/nuklear#229]
I'm using Nuklear with SDL_gpu which is a SDL satellite library which provides a more powerful 2D API to the GPU than the built-in SDL 2D API. It can be thought of as an OpenGL wrapper that tries to better balance access to GPU features with the cross-platform support and simplicty found in SDL. Anyhow, I've written my own Nuklear adapter for it, but I'm trying to improve it. 

One complication I've come across is the Vertex Buffer packing. SDL_gpu provides an API for submitting vertex arrays. However, it uses all float values, including for colors. Nuklear uses bytes for colors and floats for the rest. So right now, I'm forced to iterate, convert, and copy all of Nuklear's buffers to another array of all floats. This works, but it seems like a waste of performance if I could get Nuklear to just create the format I need in the first place. I was wondering if there was a way to do this.

**Comment by vurtun** [comment]
I only interact with with a vertex in function `nk_draw_vertex` so it already relatively abstracted away. Which should make it straight forward to have user definable vertex format. I will think about the best way to create an API for it which hopefully does not take to long.

**Comment by vurtun** [comment]
I added custom vertex packing/layout in commit: 1b9779ce51adf96c482faf20b98dacaaa33ae2c8. It is a little bit experimental at the moment and does not support a big range of types but should be usable for now.

**Comment by ewmailing** [comment]
Thank you!
I just got it working as:

    {NK_VERTEX_POSITION, NK_FORMAT_FLOAT, NK_OFFSETOF(struct nk_sdl_vertex, position)},
    {NK_VERTEX_TEXCOORD, NK_FORMAT_FLOAT, NK_OFFSETOF(struct nk_sdl_vertex, uv)}, 
    {NK_VERTEX_COLOR, NK_FORMAT_R32G32B32A32_FLOAT, NK_OFFSETOF(struct nk_sdl_vertex, col)},

It seems to be working great and it simplified a great deal of code since I could get rid of an extra memory buffer + optimizations.

Ironically, SDL_gpu just implemented support for other packing too. So I am also trying to see if I can make it work with Nuklear's default format of NK_FORMAT_R8G8B8A8. So far I'm just getting white Nuklear windows. Since this is Nuklear's default format and NK_FORMAT_R32G32B32A32_FLOAT works, I'm speculating the bug is in the new SDL_gpu code path. But if you do find any problems with the new Nuklear changes, I bring this up so I hope you'll flag this thread so I know to stop hunting down that bug.

Thanks again!

**Comment by vurtun** [comment]
> It seems to be working great and it simplified a great deal of code since I could get rid of an extra memory buffer + optimizations.

Sounds like success and in after thought it really makes sense to solve the problem inside the library instead of trying to fix it in user code.

> So I am also trying to see if I can make it work with Nuklear's default format of NK_FORMAT_R8G8B8A8

`NK_FORMAT_R8G8B8A8` could be a little bit ugly in the sense that they could have a different component ordering, but I am not 100% sure. At least for me on all the examples it seems to work. correctly.

**Comment by ewmailing** [comment]
I tracked down my problem to a bug in SDL_gpu (it needed to pass the correct flag to glVertexAttribPointer to tell it to convert the byte range to normalized 0.0-1.0.). 

So the new Nuklear code is working well for me in both the NK_FORMAT_R32G32B32A32_FLOAT  and NK_FORMAT_R8G8B8A8 cases.

Thank you.
