### ISSUE TITLE
NK_MIN / NK_MAX possible issues?

### ISSUE THREAD

**Issue by icaroperseo** [vurtun/nuklear#230]
Nice day!

Reading  [21st Century C, Second Ed. (2015), Ben Klemens, O’Reilly Media, Inc.](https://www.safaribooksonline.com/library/view/21st-century-c/9781491904428/preface01.html), I found the question is located [here](https://github.com/vurtun/nuklear/blob/master/nuklear.h#L2592) and within the any sample code (e.g. [here](https://github.com/vurtun/nuklear/blob/master/demo/glfw_opengl3/main.c#L35)).

----

> Extract from work cited above; **Chapter 8: Cultivate Robust and Flourishing Macros** (_p.p. 161 - 162_).

* Avoid double usage. This textbook example is a little risky:

```c
#define max(a, b) ((a) > (b) ? (a) : (b))
```

If the user tries `int x = 1, y = 2; int m = max(x, y++);`, the expectation is that _m_ will be _2_ (the preincrement value of _y_ ), and then _y_ will bump up to _3_. But the macro expands to:

```c
m = ((x) > (y++) ? (x) : (y++))
```

which will evaluate `y++` twice, **causing a double increment where the user expected only a single**, and `m = 3` where the user expected `m = 2`.

----

Do you think this could pose a possible issue?

Best regards.

**Comment by vurtun** [comment]
I know of the issue and know how to use it. Interestingly I even read `21st Century C` some time ago. In general the proposed solution are often templated inline function which just don't exist in C. So there is no general solution in C and you have to use macros, always write the complete trinary operation or even worse write/generate a function for every version. In the end macros are the easiest solution and I know of the problems and will use it correctly.
