### ISSUE TITLE
Nuklear stack corruption with 100% repro on vs2015 x64-bit

### ISSUE THREAD

**Issue by mlabbe** [vurtun/nuklear#233]
If you aren't 100% consistently defining or not defining `NK_INCLUDE_FIXED_TYPES` in every file that includes nuklear.h, there are code generation cases where you will corrupt the stack. This was discovered on VS2015 in x64, where `nuklear.h` is implemented in one file and then used in another one.

I have isolated the problem with full repro steps and put it into a repo:
https://github.com/mlabbe/nuklear_corruption_example

Not sure what the expected thing is to do here -- definie `NK_INCLUDE_FIXED_TYPES` in ALL compilation units that includes nuklear.h?  That seems possibly error prone.  Given that the results are subtle and insidious and likely affect other platforms and compilers, we should probably take a good look at addressing it here where we have a 100% repro case.

**Comment by vurtun** [comment]
Thanks for the issue.
The described behavior is correct even it is cumbersome. You basically have to define everything for the header as well as implementation. By that I mean:

header.h
```c
#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_STANDARD_IO
/* ... */
#include "nuklear.h"
```

source.c
```c
#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_STANDARD_IO
/* ... */
#define NK_IMPLEMENTATION
#include "nuklear.h"
```
For `NK_INCLUDE_FIXED_TYPES` the behavior if not defined in both source and header is more silent but if you wouldn't have the same defines in the source and header you would get compilation errors. I know this behavior is not perfect but I don't think there is anything I could do about it,

**Comment by irtusb** [comment]
i have a nuklear_defines.h header that is included in all my .c files including the two liner that has NK_IMPLEMENTATION. This way i only define nuklear settings y only one place

**Comment by mlabbe** [comment]
I am still extremely new to the library (the very first thing I did with it was encounter and debug stack corruption in a demo), but I can say that there needs to be a better-than-documentation catch in there for this. 

Stack corruption is way too subtle to rely on documentation or best practices like including header files in header files.

**Comment by vurtun** [comment]
I added some warning to `README.md` and `nuklear.h`. Otherwise there are type checks inside `nuklear.h` to make sure that all types are at least correct in the source file. Need to think about if there is a way to do the same in the header part.

**Comment by mlabbe** [comment]
Are you willing to have it fail on link with a function name that describes the misconfiguration?  I have an idea for a "link time assert" approach to validating argument consistency across comp units.

**Comment by vurtun** [comment]
In general I am for everything that stops bad or unwanted behavior from happening either in compile,link or runtime as long as it is not single compiler or platform specific and not to complex or ugly to implement.

**Comment by mlabbe** [comment]
It is possible to do it in full compliance with C89.  Ugly is subjective, but it is fairly invasive:

 1. Using the C preprocessor, concatenate a macro with an 'o' or 'O' for off or on for each option.  Append a descriptive error message like `_options_mismatch_read_docs_asap`.
 2. Declare an inline (if your compiler has inline) function in the decl section of nuklear.h.
 3. Implement the inline function as an empty void, inlined function under `NK_IMPLEMENTATION`.  This is a noop and the compiler will remove it, but the linker still requires the symbol.
 4. (this is the invasive part).  Wrap each public `nk_*` function call in a call that first calls the link checker, and then, secondarily, calls the actual function that does the work.  This can be made succinct through another C macro.

The last step may be less invasive than it seems at first, because option validation can be disabled in release builds, so a debugger wouldn't have to go through an extra step.

**Comment by mlabbe** [comment]
The main alternative I would suggest is, as the library maintainer with intimate knowledge, deeply consider the ramifications of options mismatch across compilation units across additional compilers.  Maybe it's trivial except for `NK_INCLUDE_FIXED_TYPES`?  In the `NK_INCLUDE_FIXED_TYPES` case, it should be possible to just correct the types being included to match stdint.h if _MSC_VER is defined in 64-bit builds.

**Comment by vurtun** [comment]
I don't really like the linking error version. I sounds extremely ugly. But like you said since it mainly just the types a decided to add the default types for GCC, clang and MSVC for x64 and x86. It is not perfect since all the other platforms and compilers are not directly supported. Still the behavior is now documented and should not happen even if used wrong under default platforms/compiler.

Side note: I did not know that MSVC defines `signed long` and `unsigned long` as a 4 byte integer, while GCC and clang define it as 8 byte. While certainly correct still it is surprising.
