### ISSUE TITLE
NK_SYMBOL_RECT and NK_SYMBOL_RECT_FILLED are conceptually reversed.

### ISSUE THREAD

**Issue by mlabbe** [vurtun/nuklear#238]
The image produced by NK_SYMBOL_RECT_FILLED isn't filled, and th image produced by NK_SYMBOL_RECT is filled.  Reading the code, it seems that NK_SYMBOL_RECT_FILLED fills the rectangle with background colour, which means, that yes, a fill did happen in code, but conceptually, it's unfilled.

`NK_SYMBOL_RECT`
![nk_symbol_rect](https://cloud.githubusercontent.com/assets/1283217/18236354/046bc4d2-72da-11e6-9f45-e14cc010091b.png)

`NK_SYMBOL_RECT_FILLED`
![nk_symbol_rect_filled](https://cloud.githubusercontent.com/assets/1283217/18236361/09ee62d4-72da-11e6-983c-38efe59255ff.png)

**Comment by vurtun** [comment]
OK sorry but I really don't get what you mean. For me the first one is just a rectangle inside a button. So it is a button with a symbol: `NK_SYMBOL_RECT`. If you want that symbol to be filled with another rectangle comparable to how the checkbox is drawn you have `NK_SYMBOL_RECT_FILLED`. I have to admit that `FILLED` is probably not the best name, but I am not really able to see what's wrong at the moment.

**Comment by mlabbe** [comment]
It depends on your perspective, and I found it surprising.  To a viewer who doesn't know how it's programmed:

The first one is clearly a rectangle that has been filled. 

The second one is clearly an outline of a rectangle.

**Comment by dleslie** [comment]
If I am to understand it, NK_SYMBOL_RECT draws a solid rectangle using only the foreground colour, whereas NK_SYMBOL_RECT_FILLED draws a solid rectangle with the foreground colour as the edging and the background colour as the fill. So does one draw an outline-only rectangle by using NK_SYMBOL_RECT_FILLED with a full-alpha background colour? If so, that's confusing as all hell.

**Comment by zhouxs1023** [comment]
NK_SYMBOL_RECT_FILLED  should show a rectangle that has been filled with foreground color as checked;

NK_SYMBOL_RECT should only show an outline of a rectangle as unchecked.

**Comment by vurtun** [comment]
If it causes so much confusion it is probably I good idea to rename it altogether. How about filled rectangle and rectangle outline?

**Comment by mlabbe** [comment]
This is one of those cases where I think breaking code compilation is superior to reversing them and silently accepting that people who upgrade the library would exhibit a bug.  Your library breakage policy would dictate when this is a good idea (maybe on a major version increment?)

`NK_SYMBOL_RECT_SOLID` and `NK_SYMBOL_RECT_OUTLINE` would address the complaint and allow autocompletion engines to list SOLID and OUTLINE choices next to each other, as they are this-or-that choices.

Note that `NK_SYMBOL_CIRCLE` appears to have the same confusion about it.
