### ISSUE TITLE
Build fails if NK_INCLUDE_COMMAND_USERDATA is enabled

### ISSUE THREAD

**Issue by snuk182** [vurtun/nuklear#239]
As of 
https://github.com/vurtun/nuklear/blob/929d74a3381a0e383e02d3c5079a100bdd3b0687/nuklear.h
the compilation errors out:
```
nuklear.h:6004:59: error: 'struct nk_draw_list' has no member named 'null'
         nk_draw_list_push_command(list, nk_null_rect, list->null.texture);
```
I suggest it should have **list->config.null.texture** there.

**Comment by vurtun** [comment]
Thanks for the issue, missed that while rewriting parts of the vertex buffer code.
