### ISSUE TITLE
Golang bindings are there

### ISSUE THREAD

**Issue by xlab** [vurtun/nuklear#247]
Hi! I've created Golang bindings for this library, they seem to be working fine. GLFW OpenGL 3 only for now, but I can add more backends if needed.
https://github.com/golang-ui/nuklear

Could you update the readme please? I'll do my best to support these bindings and improve the quality. Generation has beed done 99% automatically, so I can update the code base daily.

**Comment by xlab** [comment]
Forgot to mention: very cool project, I'll use it instead Qt for my multimedia apps now. I'm going to think about auto-generation of NK command pipelines and layouts based on YAML, should feel like QML, but that's out of scope of that issue of course.

**Comment by vurtun** [comment]
> Could you update the readme please? I'll do my best to support these bindings and improve the quality. Generation has beed done 99% automatically, so I can update the code base daily.

Thanks for your bindings. I added them as a Readme link entry. It probably won't be easy to keep bindings up to date since I change, add and remove a lot to and from nuklear, but I completely let you decide.

**Comment by snuk182** [comment]
Same for the Rust programming language :)
https://github.com/snuk182/nuklear-rust

**Comment by xlab** [comment]
@snuk182 I'm jealous of gfx 3d backend.

**Comment by vurtun** [comment]
@snuk182 I added your binding to the README.

**Comment by wasamasa** [comment]
I also wrote bindings for CHICKEN: https://github.com/wasamasa/nuklear

**Comment by vurtun** [comment]
@wasamasa thanks I added your binding along side the others.
