### ISSUE TITLE
Weird text editor behavior while typing non-latin (cyrillic) symbols

### ISSUE THREAD

**Issue by snuk182** [vurtun/nuklear#248]
I have updated the extended.c example to add cyrillic symbols baked to the font (the included Roboto font has them) and added another TextEditor to the Grid Demo. Observing a weird glitch there: when I type latin symbols, all displayed and deleted fine. However if i type cyrillic symbol (russian kb layout), the first char displayed fine, the following deletes the first and stops displaying. If I move focus somewhere else and then get back to the cyrillic editor, it shows me single symbol, which again disappears when I start typing. Tried both with cyrillic-only filter and with no filter at all.
Changed example here: https://gist.github.com/snuk182/5dc023971db18b60e3e1fa861518592d

**Comment by vurtun** [comment]
Thanks for the issue. Seems like UTF-8 is completely broken at the moment for edit boxes. I will try to fix it.

**Comment by vurtun** [comment]
OK I fixed every bug I could find inside the edit widget code. Hopefully UTF-8 now works correctly. There still could be some bugs. If you find any don't hesitate to post it. I removed all that I could find, but there are always test cases I did not think of.

**Comment by snuk182** [comment]
@vurtun thanks, I'll check shortly

**Comment by snuk182** [comment]
Input UTF8 works!
But now both Delete and Backspace delete the whole editbox contents at once, not the single character.

**Comment by vurtun** [comment]
Strange. Does this happen for you for both ANSI as well as cyrillic symbols? I tested with ASCII as well as what I have in german `äüö` and for me deleting and removing works correctly. Furthermore which edit widget did you use and which flags did you pass?

**Comment by snuk182** [comment]
Just recompiled the modified extended.c from my gist above using the new lib version.

**Comment by snuk182** [comment]
However, just updated the library for my Rust bindings - everything works there charmingly. I think this ticket may be closed.
