### ISSUE TITLE
Crash when aligning destination

### ISSUE THREAD

**Issue by JesseRMeyer** [vurtun/nuklear#249]
I use the default allocator. I've set nuklear's types to what's appropriate for my project. The crash occurs even if I define NK_INCLUDE_FIXED_TYPES.

The following crashes:

nk_context *Context;
nk_init_default(Context, 0);

The crash happens deep inside the library, inside NK_MEMSET(ptr, 0, size); The exact code phrase where the crash occurs is 

    if ((t = NK_PTR_TO_UINT(dst) & nk_wmask) != 0) {
        t = nk_wsize -t;
        size -= t;
        do {
            *dst++ = (nk_byte)c0; // <--- This line. It reads past the bytes.
        } while (--t != 0);
    }

I don't see any open issues on this. Any ideas?

**Comment by vurtun** [comment]
Thanks for the issue.
Small thing I see right away. I am not sure if this is a typo from you but it should be:

```c
struct nk_context ctx;
nk_init_default(&ctx, 0);
```

You are providing an empty pointer instead of an object. This in term calls the `memset` function with a random address which causes a segmation fault.

**Comment by JesseRMeyer** [comment]
That's what I deserve working on this too late at night. Thanks vurtun!
