### ISSUE TITLE
SDL1.2 demo crash

### ISSUE THREAD

**Issue by homelee** [vurtun/nuklear#251]
the new nuklear.h file can't build demo of sdl1_2，fix the main.c with line 98,111 so can build success，but run will crash with line 12327:
      text_width = f->width(f->userdata, f->height, (const char*)string, len);
on nuklear.h

**Comment by vurtun** [comment]
Thanks for the issue I will look into it.

**Comment by coderobe** [comment]
This is fixed with https://github.com/vurtun/nuklear/pull/254
