### ISSUE TITLE
Integration woes

### ISSUE THREAD

**Issue by JesseRMeyer** [vurtun/nuklear#252]
This is not a bug report. I am doing something wrong. Any help in getting nuklear properly working is greatly appreciated.

Below is an image that showcases the problem.
http://imgur.com/3eAZIIk

RenderDoc shows a lot of NaNs in the vertex transformations through the vertex shader. I am using the demo vertex and fragment shader. It's not clear texture data is being properly uploaded. So I must be missing a function call or something.

Below is a very quick basic overview of how I'm using nuklear. Anything behind comments are really hiding large swathes of code. I'm hoping I'm missing something basic, and easily identifiable (like my issue last time). I've combed through the demo again and again (which helped a lot in getting this far). But now I'm bashing my head against the wall.

https://gist.github.com/JesseRMeyer/deca46b75cef3d3984499a3f287d1eef

Any ideas?

**Comment by vurtun** [comment]
Hey,
as far as I can tell from a quick peek is the problem inside the font atlas code. You are calling `nk_font_atlas_end` twice. Which could be a problem. You can remove the second one. If this wasn't the problem I will have to take a deeper look.

**Comment by vurtun** [comment]
Not sure if this is fixed or not so I will close it for now. If you have any updates just reopen it.
