### ISSUE TITLE
How to change widget focus?

### ISSUE THREAD

**Issue by Lusito** [vurtun/nuklear#258]
I'd like to be able to focus an nk_edit_string somehow, but couldn't find any way to do it.
This usually happens when a window is shown.
It would also be nice to change focus by pressing tab, but I could manage that myself once I have some way to change the focus.

Offtopic: You really need some documentation & tutorials.. browsing through the demos & nuklear.h is a lot of work to find out simple things.

**Comment by vurtun** [comment]
There is no official API to activate an `nk_edit_string` widget. But it is possible to do if you know how focus is managed for edit widgets. Edit widget focus is managed by using a sequential incremented number (found in `ctx->current.edit.seq`) to identify a edit widget. This incremental ID is compared to the currently active edit widget (found inside the current window `ctx->current->edit.name`). So you only have to set the the active widget ID to the sequential number before calling the edit widget. But setting the name is not enough you also have to activate it by setting `ctx->current->edit.active` to `true`. Enough talk time for an example (this is out of my head but should work):

```c
struct nk_context ctx;
nk_init_fixed(&ctx, ...)
if (nk_begin(...)) {
    if (nk_button(ctx, "focus")) {
        /* clicking the button will focus the edit widget */
        NK_ASSERT(ctx.current);
        ctx.current->edit.active = nk_true;
        ctx.current->edit.name = ctx.current->edit.seq;
    }
    static int len; 
    static char buffer[256];
    nk_edit_string(ctx, NK_EDIT_FIELD, buffer, &len, 256, 1, 0);
}
nk_end(...);
```
You can exchange the button against your check to manually provide focus for the edit widget, I only used a button for better clearance.

**Comment by Lusito** [comment]
Thanks for the quick reply.
I've tried the code you've supplied, but it does not work. The cursor is shown as if the widget has focus, but I can't actually type any text.

As for the documentation: What would really help a lot is just a simple overview of the available widgets and the flags. Just one or two lines for what it does, and if there is some variation, give a hint that this variation exists. For example:

### nk_text
* Displays some text in the default color.
* Difference to nk_label: I have no idea.
* Use **nk_text_colored** to use a custom color.

No need to explain the function parameters, those I can figure out by searching the api. But if you have no idea what a widget is named, it's a lot of work to find the starting point.

**Comment by vurtun** [comment]
> I've tried the code you've supplied, but it does not work. The cursor is shown as if the widget has focus, but I can't actually type any text.

I checked it and it does work but not like I would like it (just press 'i' for insert mode). Basically it gets focused but not with correct flags. So the correct way would be:

```c
NK_API void
nk_edit_focus(struct nk_context *ctx, nk_flags flags)
{
    /* flags are the same as given to `nk_edit_string` */
    nk_hash hash;
    struct nk_window *win;

    NK_ASSERT(ctx);
    NK_ASSERT(ctx->current);
    if (!ctx || !ctx->current) return;

    win = ctx->current;
    hash = win->edit.seq;

    win->edit.active = nk_true;
    win->edit.name = hash;

   const enum nk_text_edit_type type = (flags & NK_EDIT_MULTILINE) ?NK_TEXT_EDIT_MULTI_LINE: NK_TEXT_EDIT_SINGLE_LINE;
    nk_textedit_clear_state(edit, type, filter);
    if (flags & NK_EDIT_ALWAYS_INSERT_MODE)
        edit->mode = NK_TEXT_EDIT_MODE_INSERT;
   if (flags & NK_EDIT_AUTO_SELECT)
       select_all = nk_true;
   if (flags & NK_EDIT_GOTO_END_ON_ACTIVATE) {
       edit->cursor = edit->string.len;
       in = 0;
   }
}
```
I will write an API for it later this day and push it up.

**Comment by vurtun** [comment]
Added function `nk_edit_focus` in commit: 867b3359b92b07e85b687b0fe0c4b533a9c85ed1. I wrote a small text for it and it seems to work for me.

**Comment by Lusito** [comment]
Thanks, this seems to work just fine.

**Comment by Sceleris** [comment]
Sorry if it's out of place, closed issue and all, but I have a couple of questions regarding this `nk_edit_focus` mechanism. Basically, I have a toggleable window (i.e. call `nk_begin` depending on flag) with an edit box, and I want the edit box to get focus each time the window is in a showing state.

Using a `nk_edit_string` works, but the focus seems to ignore the `NK_EDIT_GOTO_END_ON_ACTIVATE` flag I passed the `nk_edit_string`: each time I re-show the window, the input cursor is at the beginning. Is this intended?

But actually, I wanted to use a `nk_edit_buffer` with `nk_text_edit`, but then the behavior is completely different. Even without `nk_edit_focus` (`nk_edit_focus` seems not to have any effect), after I manually focus (i.e. mouse click) on the edit box, it's focused each time the window is toggled. But what I also wanted was to be able to replace the `nk_text_edit` passed to the `nk_edit_buffer`, and when I do that, focus is lost again, forcing a manual refocusing. Is a `nk_edit_buffer` not intended to be programmatically focusable?

**Comment by vurtun** [comment]
Hey,
could you please open a new issue. Just copy and paste everything and I will take a look.
