### ISSUE TITLE
Window Vanish

### ISSUE THREAD

**Issue by PhilCK** [vurtun/nuklear#266]
Maybe I not doing something correct.

if i setup a window with a minimise and close button I can get the window to vanish.
- click 'x' window disappears and reapears
- click '-' window minimises.
- click 'x' window vanishes never to be seen again.

if I force the situation by `nk_window_show(...)` I get an assert in `nk_panel_layout` at `NK_ASSERT(!(layout->flags & NK_WINDOW_CLOSED));`

I can repo in demo by giving a window a minimise and close button.

**Comment by PhilCK** [comment]
as a work around I'm doing this.
```
    // .. code
    nk_end(ctx);
    
    if(nk_window_is_closed(ctx, "Entity List"))
    {
      nk_window_find(ctx, "Entity List")->flags &= ~NK_WINDOW_CLOSED;
      nk_window_show(ctx, "Entity List", NK_SHOWN);
    }
```

**Comment by vurtun** [comment]
Hey, could you check if this problem still persists after commit: 69b13a008d58deb5d43fa82560caca53b6698fd4

**Comment by nsawa** [comment]
Excuse me for cutting in.
I checked this problem in the latest commit [67ad444](https://github.com/vurtun/nuklear/commit/67ad444adfd86224c256d58834065c87d43b60bc). It seems that the problem still persists. See below for the reproduction method.
Thanks.

![1](https://cloud.githubusercontent.com/assets/18512546/20515873/e8e0ff94-b0d6-11e6-865a-1c1edda37056.png)
![2](https://cloud.githubusercontent.com/assets/18512546/20515875/eb85561e-b0d6-11e6-888f-e139113b3656.png)
![3](https://cloud.githubusercontent.com/assets/18512546/20515889/f4e07932-b0d6-11e6-86bb-3744f1a4087d.png)
![4](https://cloud.githubusercontent.com/assets/18512546/20515890/f69778f2-b0d6-11e6-9f79-b09ac29451d2.png)
![5](https://cloud.githubusercontent.com/assets/18512546/20515894/f8d0daa0-b0d6-11e6-86ae-00036850ca10.png)
![6](https://cloud.githubusercontent.com/assets/18512546/20515895/fa4a4ace-b0d6-11e6-9777-3b3ea87b6336.png)
![7](https://cloud.githubusercontent.com/assets/18512546/20515897/fb9c3b30-b0d6-11e6-9ead-742c9f61dfde.png)
![8](https://cloud.githubusercontent.com/assets/18512546/20515899/fcf2a672-b0d6-11e6-841a-4b2202673e2a.png)
![9](https://cloud.githubusercontent.com/assets/18512546/20515901/fe721e7e-b0d6-11e6-8bcf-03ec76434605.png)

**Comment by vurtun** [comment]
Thanks for the steps to reproduce the problem. I was able to find a solution to it. I will push the fix ASAP. It was really trivial. If you already want to test it out  just add the following line to `nk_panel_begin` at line 16502:

```c
/* ... */
layout->flags |= NK_WINDOW_HIDDEN;
layout->flags |= NK_WINDOW_CLOSED;
layout->flags &= ~NK_WINDOW_MINIMIZED; // new line
/* ... */
````

**Comment by nsawa** [comment]
Thanks. I tried it. It worked well.
