### ISSUE TITLE
menu item's text not show

### ISSUE THREAD

**Issue by mumin16** [vurtun/nuklear#267]
previous build showed it. but current release is not show submenu item's text.

`	/*mainmenu*/
	struct nk_panel menubar,filemenu;
	static int  show_newdlg, show_opendlg, show_help, show_about = nk_false;

	nk_begin(ctx, &menubar, "MENUBAR", nk_rect(0, 0, WindowWidth, 25), 0);
	

	nk_menubar_begin(ctx);
	nk_layout_row_begin(ctx, NK_STATIC, 10, 1);
	nk_layout_row_push(ctx, 60);
	if (nk_menu_begin_label(ctx, &filemenu, "File", NK_TEXT_LEFT, nk_vec2(100, 150)))
	{

		nk_layout_row_dynamic(ctx, 20, 1);
		if (nk_menu_item_label(ctx, "New", NK_TEXT_LEFT))
			show_newdlg= nk_true;
		if (nk_menu_item_label(ctx, "Open", NK_TEXT_LEFT))
			show_opendlg= nk_true;
		if (nk_menu_item_label(ctx, "Help", NK_TEXT_LEFT))
			show_help = nk_true;
		if (nk_menu_item_label(ctx, "About", NK_TEXT_LEFT))
			show_about = nk_true;
		if (nk_menu_item_label(ctx, "Exit", NK_TEXT_LEFT))
			exit(EXIT_SUCCESS);

		nk_menu_end(ctx);
	}`

**Comment by vurtun** [comment]
I wrote an example here: #262. But from a quick glance on your code your row height of `10` in `nk_layout_row_begin` and `20` for row height in `nk_layout_row_dynamic` is way be to small. Could you make it bigger (around 25-30px) and check if it is showing again if not I will take another look.

**Comment by mumin16** [comment]
[http://i67.tinypic.com/9a1sex.png](url)

**Comment by mumin16** [comment]
it's ok with last release

**Comment by vurtun** [comment]
Thanks forgot to check the C++ version. All `nk_panel` cast are now fixed in commit: 69b13a008d58deb5d43fa82560caca53b6698fd4
