### ISSUE TITLE
FIFO_INCLUDE_FIXED_TYPES

### ISSUE THREAD

**Issue by nsawa** [vurtun/nuklear#268]
In revision 69b13a0, isn't it a bug?

line 315:

> # ifdef FIFO_INCLUDE_FIXED_TYPES

correct:

> # ifdef NK_INCLUDE_FIXED_TYPES

Thanks.

**Comment by vurtun** [comment]
Thanks for noticing looks like a really stupid copy & paste bug. Should be fixed with b280370fc8e89bfc835ca99d16c3298d2e7af6a8.
