### ISSUE TITLE
Rendering huge lists

### ISSUE THREAD

**Issue by ytsarko** [vurtun/nuklear#269]
@vurtun Hi! Is there any way to deal with very huge data sets (list views) containing hundreds of thousands elements (or may be more)? Currently established approach in desktop/mobile is to use "virtual list view" approach where the list shows only few screens of elements and when user scrolls to the either end of that range silently fetches more data to it (for example Qt`s [QAbstractItemModel::fetchMore](http://doc.qt.io/qt-4.8/qabstractitemmodel.html#fetchMore) approach). The main difficulty here is that list view must show its scrollbar rendered as if there are all data available by drawing very small scroll bar handle but when user drags it (or otherwise initiates scrolling behavior) it silently load more data before user will see it.

May be currently is it possible to imitate this behavior by directly setting scroll bar properties to desired values and doing all the other stuff on user`s side (I mean watch for scroll bar position and trigger fetching of data when it moves to the position where new data must be shown)?

**Comment by vurtun** [comment]
Hey @ytsarko. Rendering huge list is possible. You need to create a group and then access the groups internal scrollbar values and before calling `nk_group_end` get the internal `nk_panel` and update `at_y` to your desired height (number_of_items * height_of_row). Biggest problem in my library is that scrollbar values are `nk_short` to take up less space inside state tables. So you probably have to update internal table element size from 32-bit to 64-bit to store x- as well as y-axis scrollbar offset. For windows it is easier you can directly modify scrollbar offsets but again you have to change `nk_short` to your desired bigger type.

**Comment by dumblob** [comment]
@vurtun we should add this note about handling huge lists to documentation (maybe even with an example pseudo code) as it's expected to be a common issue.

**Comment by ytsarko** [comment]
@vurtun Thank you for reply. It appears that to accomplish that one need to directly manipulate with scrollbar`s internal state. I`ll give it a try when I`ll get back to my dev computer.

**Comment by vurtun** [comment]
I will write up an example as soon as possible. Will probably also add a new define to optionally support 64-bit state table values. But depending on your use cases `nk_ushort` could even be already sufficient if you have less then 2621 elements with row height of 25 px.

**Comment by vurtun** [comment]
OK I added `nk_list_view_begin` and `nk_list_view_end` to support huge lists (42efd8214fee786c41ff533bc7f08ab28d7d0b11):
```c
static const char *list[1024] = {
    /* .... */
};
struct nk_list_view view;
nk_layout_row_dynamic(ctx, 400, 1);
if (nk_list_view_begin(ctx, &view, "test", NK_WINDOW_BORDER, 25, 1024)) {
    nk_layout_row_dynamic(ctx, 25, 1);
    for (int i = 0; i <= view.count; ++i) {
        nk_label(ctx, list[view.begin + i], NK_TEXT_CENTERED);
    nk_list_view_end(&view);
}
```
Note: `struct nk_list_view` is a temporary object and does not have to be persistent.
 I will add an optional define supporting bigger scrollbar offsets later, but for now it is limited to `nk_ushort`.

**Comment by inolen** [comment]
Just wanted to say, `nk_list_view_begin` is very helpful and much appreciated.

With that said, having the ability to scroll more than 16-bits would be fantastic.
