### ISSUE TITLE
clang error is "assertion_failed_ declared as an array with a negative size"

### ISSUE THREAD

**Issue by mumin16** [vurtun/nuklear#275]
clang error is "assertion_failed_ declared as an array with a negative size"

**Comment by vurtun** [comment]
I am not 100% sure but this sounds like one of my static asserts to make sure all basic types have the correct size. Did you forget to define `NK_INCLUDE_FIXED_TYPES` or if you don't want to use it set the correct types sizes?

**Comment by mumin16** [comment]
solution define FIFO_INCLUDE_FIXED_TYPES
