### ISSUE TITLE
Tooltips flicker

### ISSUE THREAD

**Issue by keharriso** [vurtun/nuklear#278]
Tooltips flicker constantly for me. I have tried x11 and x11_opengl3 on Debian and d3d11 on Windows 10. Is there a way to solve this?

**Comment by nsawa** [comment]
I figured out the tentative way to solve this.

```
NK_API void
nk_tooltip_end(struct nk_context *ctx)
{
    NK_ASSERT(ctx);
    NK_ASSERT(ctx->current);
    if (!ctx || !ctx->current)
        return;
    ctx->current->seq--; /* add this line */
    nk_popup_close(ctx);
    nk_popup_end(ctx);
}
```

**Comment by vurtun** [comment]
I added a commit using @nsawa solutions (c490e80f014e563aade24fbaadfee0677685ba05).
