### ISSUE TITLE
warning 'incompatible types'

### ISSUE THREAD

**Issue by nsawa** [vurtun/nuklear#279]
In revision 1acb7ba, now a warning is generated. (using VisualStudio2015)

> CD demo\d3d11
> build.bat
> nuklear.h(18433): warning C4133: incompatible types - from 'nk_uint *' to 'nk_collapse_states *'.

In addition, when the nuklear.h is included from C++ source, this warning will result in an error.

> nuklear.h(18433): error C2664: cannot convert argument 5 from 'nk_uint *' to 'nk_collapse_states *'.

I think the explicit type cast is needed.

**Comment by vurtun** [comment]
Thanks I hopefully fixed it all warnings and errors in 02fb0193746cee010175d8077b37fca0a20e6201
