### ISSUE TITLE
Allow NK_API to be overwritten

### ISSUE THREAD

**Issue by Wizzard033** [vurtun/nuklear#281]
I use the Nuklear library in a few different processes.
Naturally, I want to share the code between these processes.
To do this on Windows, I need to export everything.

    #define NK_API __declspec(dllexport)

However, NK_API will just be overwritten by the library.
Instead, I replaced it with the following:

    #ifndef NK_API
    #ifdef NK_PRIVATE
    #define NK_API static
    #else
    #define NK_API extern
    #endif
    #endif

**Comment by vurtun** [comment]
Makes sense, I changed it.
