### ISSUE TITLE
Lone color picker in combobox closes on first mouse press

### ISSUE THREAD

**Issue by keharriso** [vurtun/nuklear#282]
In the following simple example, the color picker closes at the first mouse press (instead of staying open for multiple clicks/drags):
```
static struct nk_color color = {255, 0, 0, 255};
if (nk_begin(ctx, "Test Combo", nk_rect(100, 100, 200, 200), NK_WINDOW_NO_SCROLLBAR)) {
    nk_layout_row_dynamic(ctx, 25, 1);
    if (nk_combo_begin_color(ctx, color, nk_vec2(200, 200))) {
        nk_layout_row_dynamic(ctx, 120, 1);
        nk_color_pick(ctx, &color, NK_RGB);
        nk_combo_end(ctx);
    }
}
nk_end(ctx);
```
Oddly enough, this can be worked around by either adding additional widgets to the combobox or calling `nk_layout_row_dynamic(0, 0)` after `nk_color_pick`.

Here is a possible solution to the problem (add `nk_layout_row_dynamic` to `nk_contextual_end`), but it seems hackish, so I am opening this issue instead of initiating a pull request.
```
--- a/nuklear.h
+++ b/nuklear.h
@@ -20974,6 +20974,7 @@ nk_contextual_end(struct nk_context *ctx)
     panel = popup->layout;
     NK_ASSERT(popup->parent);
     NK_ASSERT(panel->type & NK_PANEL_SET_POPUP);
+    nk_layout_row_dynamic(ctx, 0, 0);
     if (panel->flags & NK_WINDOW_DYNAMIC) {
         /* Close behavior
         This is a bit hack solution since we do not now before we end our popup
```

As a side note, this issue affects not just color pickers, but sliders, progress bars, and likely other widgets as well.

**Comment by vurtun** [comment]
Thanks for the issue it should not be fixed with issue 6a374eabb1d8ace7e79c7562522cd435a3859393.
