### ISSUE TITLE
High CPU usage of demo/x11 on Linux Mint

### ISSUE THREAD

**Issue by adel-mamin** [vurtun/nuklear#288]
I have checked the demo/x11 and noticed that CPU usage is quite high:
%CPU %MEM     TIME+ COMMAND
26,5  2,5 156:57.88 Xorg
18,2  5,4 182:11.23 cinnamon
 1,7  0,1   0:00.90 zahnrad
So zahnrad process does not spend much time, but Xorg and cinnamon do. Once I close zahnrad, both Xorg and cinnamon processes stop eating CPU time.
Is this something that is expected and by design? If not, then could the CPU usage be reduced anyhow?

**Comment by vurtun** [comment]
Hey thanks for the issue. If you have performance or energy problems please first give #225 a try. Basically you check every frame if anything has changed and only draw frames which did.
