### ISSUE TITLE
nk_popup_begin() leaks memory

### ISSUE THREAD

**Issue by nsawa** [vurtun/nuklear#289]
Thank you for the fixing of the https://github.com/vurtun/nuklear/issues/287. I confirmed that the problem was fixed.

Unfortunately, I noticed that there is another situation which memory leak is occurred in. Closing a popup by clicking the close button will result in a memory leak. The way to reproduce the problem is as follows:

1. Change the demo source code a bit so that we can monitor the status of memory allocation.
![1](https://cloud.githubusercontent.com/assets/18512546/20452609/4fe0e462-ae51-11e6-8257-daff4423012e.png)

2. Run the overview demo and click the "About" item.
![2](https://cloud.githubusercontent.com/assets/18512546/20452610/562e2a82-ae51-11e6-928e-27f63cdafa30.png)

3. Click the close button, popup is closed.
![3](https://cloud.githubusercontent.com/assets/18512546/20452615/5f2ab1b4-ae51-11e6-87ed-c13de4818e12.png)

4. When you do 2. and 3. repeatedly, memory allocating is occurred every 16 times. And memory freeing is not occurred.
![4](https://cloud.githubusercontent.com/assets/18512546/20452617/64b208ee-ae51-11e6-90eb-90c46cbac8a4.png)

**Comment by vurtun** [comment]
Thanks again. Sorry seems like I missed that. Hopefully everything is now fixed with commit: (e7c06e027a7b7ad931e49654a9247705ca1e6c35)
