### ISSUE TITLE
Would you give some examples about displaying CJK characters?

### ISSUE THREAD

**Issue by tinnnysu** [vurtun/nuklear#290]
I can't find examples about displaying CJK characters. Would you give some tips or links for that. Thanks

**Comment by vaiorabbit** [comment]
These links may help:
https://gist.github.com/vaiorabbit/e36c7c04f7f3dddadf14653f31eb3faf
https://github.com/vaiorabbit/ruby-nuklear/tree/master/demo
http://www.unicode.org/charts/

**Comment by tinnnysu** [comment]
Thanks
