### ISSUE TITLE
Omitting nk_begin() for the minimized window results in the incorrect rendering

### ISSUE THREAD

**Issue by nsawa** [vurtun/nuklear#291]
It seems that omitting nk_begin() for the minimized window results in the incorrect rendering. The steps to reproduce this problem is as follows:

![1](https://cloud.githubusercontent.com/assets/18512546/20550044/239033f0-b175-11e6-8651-acae3736d054.png)
![2](https://cloud.githubusercontent.com/assets/18512546/20550045/265bfd30-b175-11e6-8ceb-4eed9f185380.png)
![3](https://cloud.githubusercontent.com/assets/18512546/20550046/2888e80c-b175-11e6-8005-8f075e74d3b5.png)
![4](https://cloud.githubusercontent.com/assets/18512546/20550048/2ac04cc8-b175-11e6-87e5-5e97018975b6.png)
![5](https://cloud.githubusercontent.com/assets/18512546/20550050/2c900480-b175-11e6-9172-316fa0eac711.png)
![6](https://cloud.githubusercontent.com/assets/18512546/20550051/2ee89b3e-b175-11e6-9478-fd9453ffca06.png)
![7](https://cloud.githubusercontent.com/assets/18512546/20550052/30d3ab64-b175-11e6-8ba0-e5090a768dd5.png)
![8](https://cloud.githubusercontent.com/assets/18512546/20550053/32cbbe8e-b175-11e6-9bfe-6001b8bcc1dd.png)

I came up with a solution. However, I'm not confident whether this solution always works correctly.

![9](https://cloud.githubusercontent.com/assets/18512546/20550057/3d4ee3b8-b175-11e6-8c23-8cd9af040eed.png)
![10](https://cloud.githubusercontent.com/assets/18512546/20550063/40457e60-b175-11e6-9a50-69026a4ac5cf.png)
![11](https://cloud.githubusercontent.com/assets/18512546/20550064/4207706e-b175-11e6-8853-e5f3557fef82.png)

Thanks.

**Comment by vurtun** [comment]
Thanks for the issue again even if it took me a little longer but it should now be fixed in commit: 020a562c2ec5e7cd3b5be7fd6f03f34cb7b9f45b. Your solution was almost correct at least from code location to change. The bug is actually one line below where I check if a window is minimized and do not close it even if it was closed before.
