### ISSUE TITLE
Wrap text based on words, and not characters

### ISSUE THREAD

**Issue by Wizzard033** [vurtun/nuklear#292]
The text currently
 wraps like this b
ut I'd like it to wr
ap like below

The text should
wrap like this
because its way
easier to read

**Comment by dumblob** [comment]
@Wizzard033 please define what is a word boundary for you. For me it might be anything which is not visible when printed. So if this is being implemented, then it must be configurable (probably using a callback).

**Comment by Wizzard033** [comment]
Words are separated by either a delimiter or by not fitting on a single line
Traditionally, the delimiter seems to be just the space character
A callback is not necessary, and I'd be fine if it was just the space character

**Comment by Wizzard033** [comment]
The Wikipedia page for word wrap is a good reference for implementation
https://en.wikipedia.org/wiki/Line_wrap_and_word_wrap

**Comment by dumblob** [comment]
There are 2 important things to keep in mind.

1. automatical hyphenation shall be supported (it should suffice to have it just in the word wrapping interface, but not internally implemented)
1. support for character based wrapping must still be available as an option (e.g. for cases with ultra low widths like in case of translated strings in narrow widgets)

Based on the complexity (wrapping algorithms, hyphenation, etc.), I would not abandon the solution of providing just a minimal interface for handling of line wrapping while by default splitting at the last character (i.e. the current behavior).

**Comment by Wizzard033** [comment]
Hyphenation is way beyond my expectations for the provided label widget.
For this, it'd probably be best to use a custom widget.
I don't want to see the interface complicated by requiring a callback.
Word wrap is a basic feature provided by GWEN, SFGUI, and TGUI.
Only terminals use the current type of wrapping - it's basically deprecated by word wrap.
I feel you're right that it may look better for ultra low widths, but word wrap would still suffice.

**Comment by dumblob** [comment]
>I don't want to see the interface complicated by requiring a callback.

It might be necessary, because not everybody will be OK with O(n^2) algorithm just for word wrapping (the O(1) algorithm does not produce nice enough results) or with equivalent algorithm, which is though quite complicated (uses dynamic programming if I'm not mistaken and thus needs also quite some memory).

Anyway, adding a callback (or similar) to `ctx` and setting it to `wrap_on_character()` function by default should maintain backwards compatibility while allowing the complex handling.

>I feel you're right that it may look better for ultra low widths, but word wrap would still suffice.

No, word wrap is not sufficient in such cases. Character-wise wrapping is unfortunately needed for these.

**Comment by Wizzard033** [comment]
I think you're mistaken if you think the O(1) algorithm does not produce good results.
Microsoft Word is the current standard for written reports, and it uses that algorithm.

For the character-wise wrapping, I guess we'll just have to agree to disagree.
I have the opinion that no user would ever miss that type of wrapping.

**Comment by dumblob** [comment]
>I have the opinion that no user would ever miss that type of wrapping.

**Comment by Wizzard033** [comment]
I'm not going to report on the performance of word wrapping algorithms.
I don't advocate use of the O(n^2) algorithm because it's highly unnecessary.
It is harder to implement, requires more memory, and only looks marginally better.

Custom widgets exist for fancy options; the default widgets should be simple.
Where would we even draw the line? Justified alignment? Hyphenation? In-line color/bold/italic?
I just want the default widgets to look and feel right, and word wrap is necessary for that.

This is the first GUI library I've taken a look at that does not have word wrap.
It's such a basic feature that I believe performance measurements mean nothing.
It's intrinsic to what should be in a GUI library, and so it should be put in as at least an option.

**Comment by vurtun** [comment]
Hey thanks for the issue. I changed it to wrap on words instead of characters in commit: https://github.com/vurtun/nuklear/commit/ebe516c37b16d74381c1532f48d24a5dccd4c235.
As for additional codepoints to split on I have an array in function `nk_widget_text_wrap` which can be filled to fit any single codepoint splitting needs.

**Comment by Wizzard033** [comment]
This looks great so far. I really appreciate the work that went into this!

One issue: it needs to split words if the entirety of the word cannot fit on one line.
Currently, it seems that words that are too big to fit on one line just disappear (aren't displayed).
Words that are too big should be split by character just as they were before.

**Comment by vurtun** [comment]
Thanks I missed and failed to test that use case. Hopefully is now fixed with commit:  ca1c9b3275cf8e31b01fcd61c4d5116f88d4e24d.

**Comment by Wizzard033** [comment]
I also recommend that space characters not be able to be put on a line by themselves.
This is just an idea I had to improve the cosmetic for small width windows.

However, it works great for my purposes as is. Thanks for the great library!

**Comment by Wizzard033** [comment]
Here are a couple of comparison screenshots of different widths to highlight the problem
![screenshot 2016-12-03 10 14 30](https://cloud.githubusercontent.com/assets/721311/20861296/4b59f0d2-b941-11e6-82c5-c4e1669b6359.png) ![screenshot 2016-12-03 10 14 34](https://cloud.githubusercontent.com/assets/721311/20861297/4d60aaf6-b941-11e6-9354-1ce531cb7cce.png)
