### ISSUE TITLE
The font display is partially missing？

### ISSUE THREAD

**Issue by actboy168** [vurtun/nuklear#293]
1.Using d3d11 demo
2.Using nk_font_atlas_add_from_file load any font
![3](https://cloud.githubusercontent.com/assets/1836844/20797064/3de81682-b814-11e6-87b4-dc1c25235c46.png)
3.Many character is missing 1px in bottom.
![2](https://cloud.githubusercontent.com/assets/1836844/20797150/86e8f324-b814-11e6-9fb8-acf23099c518.png)
4.If the font size to 20, will see more clearly.
![1](https://cloud.githubusercontent.com/assets/1836844/20797140/814aca50-b814-11e6-8605-c1e249f498ff.png)

**Comment by Kuldra** [comment]
Having the same issue with nk_font_atlas_add_from_memory. 
Using the default works fine though but not much use for custom fonts.

**Comment by Kuldra** [comment]
Fixed. If you increase the font **oversample_v** it'll grab the whole thing (we are using 4).
