### ISSUE TITLE
Use font character as alternative for nk_image in nk_button_image_label() etc

### ISSUE THREAD

**Issue by Dodzey** [vurtun/nuklear#294]
I am currently using Font-Awesome as an icon font for symbols on buttons. This works great when I want a button which is just an icon - I push a new user font onto the font stack, create a button with nk_button(...) and pass in the unicode for the character I want.

I'd like to be able to use an icon-font as an alternative to the nk_image parameter to the functions which allow both an image and a label.

I guess one way to achieve this would be a way to fully populate an nk_image struct with the handle/width/height for the font texture, and also populate the region with the pixel coordinates for a particular unicode character. This can just be passed into the widget functions which are already there. Would this be a good approach to take? How would this work in practice?
Is there a more obvious/better solution that I missed??

Thanks

**Comment by vurtun** [comment]
Hey, what you could do is merge to fonts one with ASCII characters and the other one would be Font-Awesome. Of course this requires Font-Awesome to not use the ASCII codepoint ranges.
Other then that like you said you could use `nk_subimage_xxx` to directly draw the glyph to screen.
