### ISSUE TITLE
window image background?

### ISSUE THREAD

**Issue by tinnnysu** [vurtun/nuklear#298]
Is there a example about using an image as window background?
Would some one give me some tips. Thanks

**Comment by vurtun** [comment]
Hey, you only can change the background to an image for non-dynamic size panels, which also includes normal windows by changing:
```c
ctx->style.window.fixed_background = nk_style_item_image(nk_image_xxx(your_image_texture));
````
For more information I would recommend looking at `demo/skinning.c` to get an overview on how skinning works in nuklear.
