### ISSUE TITLE
Add extra info to assert message in nk_begin_titled()

### ISSUE THREAD

**Issue by Saticmotion** [vurtun/nuklear#301]
I'm currently adding Nuklear to an existing project, and was adding code from the glfw_opengl3/main.c example line by line. After getting to nk_begin and nk_end Nuklear was asserting that I had two windows with the same name[0]. I was quite puzzled by this assert, since I was barely doing anything. Turns out I forgot to actually draw the window. So it might be a good idea to add a message about this to the assert.

Apart from this I've been very happy with how good the asserts are! Really helps you to set up Nuklear quickly.

[0] line 17250 in nk_begin_titled() at time of writing: `NK_ASSERT(win->seq != ctx->seq && "if this triggers you probably have two windows with same name!");`

**Comment by vurtun** [comment]
Thanks for your issue and feedback I am always grateful asserts and their explanation can be extended. I added another comment to also describe your case. This hopefully makes it easier if some else encounters the same problem.
