### ISSUE TITLE
Why GLFW_KEY_P for paste? 

### ISSUE THREAD

**Issue by xlab** [vurtun/nuklear#311]
Hi! I stumbled upon this key binding:
https://github.com/vurtun/nuklear/blob/master/demo/glfw_opengl3/nuklear_glfw_gl3.h#L413

```
nk_input_key(ctx, NK_KEY_COPY, glfwGetKey(win, GLFW_KEY_C) == GLFW_PRESS);
nk_input_key(ctx, NK_KEY_PASTE, glfwGetKey(win, GLFW_KEY_P) == GLFW_PRESS);
nk_input_key(ctx, NK_KEY_CUT, glfwGetKey(win, GLFW_KEY_X) == GLFW_PRESS);
```

Any rationale behind `Ctrl+P` for paste instead `Ctrl+V`? I just wondering, this looks like a typo.

**Comment by vurtun** [comment]
Yeah this is a typo looks like for some reason I thought in terms of vim which uses `p` for paste, but it actually should have been `GLFW_KEY_V`. I will fix it.

**Comment by xlab** [comment]
👍 thanks! 
happy new year
