### ISSUE TITLE
add option to allow scrolling more than 16-bits

### ISSUE THREAD

**Issue by inolen** [vurtun/nuklear#312]
Creating a new issue about this since https://github.com/vurtun/nuklear/issues/269 is closed.

What's your idea around making this option? I got stuck at the value cache all being nk_uint, aka not big enough to hold two scrollbar offsets larger than nk_ushort. Should both scrollbar offsets be separate values, or should the value object size be configurable as well in this case?

**Comment by vurtun** [comment]
Hm, it might be a good idea to separate both offset values. So you would basically hash the identifier and use the hash for the y-offset and add one and store the x-offset. This would require the least amount of code changes while still solving the problem.

**Comment by inolen** [comment]
Thanks a lot!
