### ISSUE TITLE
Nuklear with Android NDK, EGL, OpenGL ES 2.0 and OpenGL ES 3.0

### ISSUE THREAD

**Issue by xlab** [vurtun/nuklear#320]
This isn't an issue but a tip for those who are searching.

There is GLES2 and GLES3 backends implemented in Go for Android NDK platform, 
so for anyone interested it can be a source of a working implementation.

### OpenGLES3

Implementation copied from Nuklear OpenGL3 with little changes for ES3

https://github.com/golang-ui/nuklear/blob/master/nk/impl_android_gles3.go

Input, etc: https://github.com/golang-ui/nuklear/blob/master/nk/impl_android_common.go

### OpenGLES2

https://github.com/golang-ui/nuklear/blob/master/nk/impl_android_gles2.go

Implementation copied from this example https://github.com/vurtun/nuklear/issues/162

It's a messy example just to test out an alternative way, I advise you to see ES3 first.

**Comment by mumin16** [comment]
for es2 , any c/c++ sample?

**Comment by xlab** [comment]
@mumin16 implementation is almost identical with C version see

> Implementation copied from this example #162
