### ISSUE TITLE
way to manually modify NK_EDIT_ACTIVATED / NK_EDIT_DEACTIVATED

### ISSUE THREAD

**Issue by seibelj** [vurtun/nuklear#321]
As mentioned here https://github.com/vurtun/nuklear/pull/315 it would be nice to be able to modify these properties / flags directly. I do not believe it is currently possible. With a soft keyboard on iOS / Android, my strategy is to simulate a mouse click event somewhere off screen to tell nuklear to remove the edit cursor, but this is a hack.

**Comment by vurtun** [comment]
While you can manually focus a edit widget your are right it is not possible to manually remove the focus. But correct me if I am wrong but the behavior you described of first having to click a way to remove focus sound correct to me. Is there any case where it makes sense to manually remove the edit widget focus?

**Comment by seibelj** [comment]
When on mobile devices, the user can manually dismiss the keyboard, at which point text entry should stop. Having to simulate a tap somewhere that I have to make sure does nothing is a bit of a hack.

**Comment by dumblob** [comment]
>Having to simulate a tap somewhere that I have to make sure does nothing is a bit of a hack.

I think the idea is quite the opposite - namely to make sure, it's clear to the programmer (and also the end user), that there has to be always something activated. There shouldn't be any "unknown" state between activated and non-activated. Or am I missing something?

**Comment by seibelj** [comment]
The way nuklear currently is, the only way to have the cursor exit a text entry widget is to click off, tab off, or do something that nuklear knows to move or hide the text entry cursor. This assumes that the keyboard is always active. On a mobile device, the user can do things (hide the keyboard) that nuklear is not innately aware of. The cursor will still be displayed, but the keyboard is hidden, so there should be no cursor. With standard UI elements on iOS or Android, the operating system will hide the text entry cursor when the user manually dismisses the keyboard.

What I am requesting is the ability to notify nuklear to stop text entry. Nuklear tries to be clever about knowing how to handle the cursor, but giving the programmer the ability to fully control it will stop all edge cases, no matter the platform.

**Comment by dumblob** [comment]
>The cursor will still be displayed, but the keyboard is hidden, so there should be no cursor.

I know it might be subjective, but I find exactly this behavior totally misleading. This is one of those many things I dislike on Android :cry:. What happens in Android after connecting e.g. a bluetooth keyboard? The cursor magically appears somewhere? Where? And why exactly there? Why shouldn't be the user responsible for hiding of the keyboard and therefore precisely know where she/he tapped and therefore what is activated? In my very own opinion, there shouldn't be any "hide keyboard" button, but rather "focus/activate widget XYZ" button.

On the other hand I agree, there should be a way to fully control this behavior programatically, so this Nuklear issue is valid and should get resolved.

**Comment by vurtun** [comment]
Yeah just like @dumblob said ugly but needed. I will write the counter version to `nk_edit_focus` this weekend which will unfocus the currently focused edit widget.
