### ISSUE TITLE
X11 demos do not handle closing of X11 window

### ISSUE THREAD

**Issue by DeXP** [vurtun/nuklear#331]
The process is not finishing when closing X11 window. The program still works in background.
There are a lot of examples ([link1](http://stackoverflow.com/questions/19305982/xlib-closing-window-always-causes-fatal-io-error), [link2](https://cboard.cprogramming.com/linux-programming/60466-xwindows-close-window-event.html) etc), they all use `XSetWMProtocols` to add new `Atom` to X11 window. But, they all using `XNextEvent`, not `XCheckWindowEvent` as in demos... 
My skills are not good enough to add this functionality into demos.

**Comment by vurtun** [comment]
Thanks for the issue, I fixed it. `XCheckWindowEvent` did not work but I use `XPending` in combination with `XNextEvent`. So far it seems to work.
