### ISSUE TITLE
How to Compile using Microsoft Build Tools 2015?

### ISSUE THREAD

**Issue by reymarbc** [vurtun/nuklear#338]
How to Compile using Microsoft Build Tools 2015? 
the build.bat inside demo folder doesn't work using this compiler release.
thank you for the answer.

**Comment by mmozeiko** [comment]
Does it install cl.exe? If yes, then simply put full path to cl.exe inside build.bat.

**Comment by vurtun** [comment]
The build.bat requires Visual studio 14 in path:
`C:\Program Files (x86)\Microsoft Visual Studio 14.0` so please make sure that either you have
the correct path. If you have a different visual studio make sure to change it to your version and path.
