### ISSUE TITLE
Which operating systems are compatible?

### ISSUE THREAD

**Issue by omerfeyyaz** [vurtun/nuklear#343]
I wonder which operating systems are compatible with what?

**Comment by vurtun** [comment]
There is no platform specific code inside the core library `nuklear.h`. Furthermore it is written in ANSI C (C89) so there is nothing that should keep you from either using one of my demo backends or write your own for your specific platform. There are some backends like GDI, GDIP and DirectX which are only usable under Windows provided they are supported and X11 which is only supported under linux as far as I know. There shouldn't be a problem to use nuklear on mobile but you probably would need to write your own backend.

**Comment by omerfeyyaz** [comment]
Thanks for information
