### ISSUE TITLE
NK_WINDOW_TITLE flag can not hide windows titlebar?

### ISSUE THREAD

**Issue by zhouxs1023** [vurtun/nuklear#345]
I use overview demo,but find NK_WINDOW_TITLE flag can not hide windows titlebar as below pics?
select flag: NK_WINDOW_TITLE
![titlebar](https://cloud.githubusercontent.com/assets/905931/22861689/968e4a16-f15a-11e6-96ca-3b5c59bd0684.PNG)
usselect flag: NK_WINDOW_TITLE ,but can hide titlebar
![notitlebar](https://cloud.githubusercontent.com/assets/905931/22861697/b2d74312-f15a-11e6-80bf-9e6b7bfa5eaf.PNG)

**Comment by vurtun** [comment]
The `NK_WINDOW_TITLE` flag does not hide the header by itself. It is mainly a helper flag if you don't have `NK_WINDOW_CLOSABLE` or `NK_WINDOW_MINIMIZABLE` defined but still want to display a title. So if you want to remove the titlebar in the overiew demo remove the `NK_WINDOW_CLOSABLE`, `NK_WINDOW_MINIMIZABLE` and `NK_WINDOW_TITLE` flag.
