### ISSUE TITLE
Help with Nim bindings

### ISSUE THREAD

**Issue by zacharycarter** [vurtun/nuklear#348]
Hello,

I've created bindings to nuklear for the Nim programming language. They can be found here - https://github.com/zacharycarter/nuklear-nim

The bindings are not complete and there are still a few constructs in nuklear.h I have yet to figure out how to port to nim. Regardless, they're mostly complete and I'm trying to work up a small example based on the Opengl 3 GLFW3 demo.

I'm running into a problem though. When I call - nk_begin (https://github.com/zacharycarter/nuklear-nim/blob/master/testNuklear.nim#L85) - in my program, the following assertion fails :

Assertion failed: (!ctx->current && "if this triggers you missed a `nk_end` call"), function nk_begin_titled, file ./nuklear.h, line 17271.

Here's some output from lldb
```Process 14487 stopped
* thread #1: tid = 0x14966, 0x0000000100001116 testNuklear`main_mgJNO5hlIp1wZRNie7UREA + 1094 at testNuklear.nim:85, queue = 'com.apple.main-thread', stop
reason = breakpoint 3.1
    frame #0: 0x0000000100001116 testNuklear`main_mgJNO5hlIp1wZRNie7UREA + 1094 at testNuklear.nim:85
   82       glfw.PollEvents()
   83       #nk_glfw3_new_frame()
   84       ##  GUI
-> 85       if nk_begin(ctx, "Demo", nk_rect(50, 50, 230, 250), nk_flags NK_WINDOW_BORDER.cint or
   86           NK_WINDOW_MOVABLE.cint or NK_WINDOW_SCALABLE.cint or NK_WINDOW_MINIMIZABLE.cint or
   87           NK_WINDOW_TITLE.cint) == 1:
   88           discard
(lldb) frame variable ctx0->current
(nkwindow_F8W9asuU9aVqgjmJLA5nrAQw *) ctx0->current = 0x0000000000000000
(lldb)
```

I'm not sure why when the C code is invoked - this is no longer the case...

I've added some printf statements to nuklear.h to ensure that the method isn't being called twice and failing on a subsequent invocation - it's failing on the first call.

I've been tearing my hair out over this - I can't figure out why the context isn't null. Is there anything that needs to be done initialization wise, besides calling nk_init and setting a default font? I'm reaching for help here as I'm guessing most folks here don't know nim, but any suggestions would be greatly appreciated!

**Comment by zacharycarter** [comment]
Here's a discussion on the nim forums that I just posted regarding this issue - https://forum.nim-lang.org/t/2807

**Comment by vurtun** [comment]
Hm ... so if the assert was hit it basically means that `ctx->current` is not null which it should be. Does it assert the first time the function is executed or later? This is important since if it is hit the first time it mean that `nk_context` was not correctly initialized to zero by one of the `nk_init` functions. The other possible reason is that not all `nk_begin` calls have a later `nk_end' call.
Furthermore did you make sure you called `nk_clear` after the UI has been rendered? All of my demos to it automatically, but if you write your own backend or version you still have to call it.

**Comment by zacharycarter** [comment]
I modified nuklear.h and added some debug print statements to figure out whether it was failing the first time or on subsequent calls, and it's definitely the first call to it.

Does nuklear do any threading? I was talking to the creator of nim and he suggested - 

> callback that are passed to C and then invoked on a different thread needs the .gcsafe annotation and also call  setupForeignThreadGc

I tried adding this pragma / annotation to nk_init and a few other Nim binding functions, but no luck. Even if I explicitly set ctx->current = nil in Nim before calling nk_begin, the assert fails. I'm guessing something funky is going on with Nim's garbage collector and the C interop.

**Comment by vurtun** [comment]
Nuklear has no threading. It does not interact with any platform specific stuff at all. It is just pure C code. I just saw that your printf even shows `ctx->current` as `0x0000000000000000`. If everything fails you can overwrite `NK_ASSERT` to an empty define before including:

```c
#define NK_ASSERT(a)
#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#define NK_IMPLEMENTATION
#define NK_SDL_GL3_IMPLEMENTATION
#include "../../nuklear.h"
#include "nuklear_sdl_gl3.h"
```
Of course this also removes all assert handling, but it is better than not having a running version at all.

**Comment by zacharycarter** [comment]
Thank you for the suggestion. I'll see if this doesn't get me any further.

**Comment by vurtun** [comment]
You could also just remove the specific assert. It is mainly just a helper assert to make sure that nuklear is used correctly.

**Comment by zacharycarter** [comment]
I was able to get passed the problem I was describing earlier. I believe it was caused by me copying the demo example / glfw3 backend and your use of static structs there and me not accounting for that.

I'm facing a new challenge now specifically in my call to - nk_convert.

The assert - 
Assertion failed: (0 && "wrong element attribute"), function nk_draw_vertex, file ./nuklear.h, line 6945.

Keeps failling. I ran a printf on - 
printf("%d\n", elem_iter->offset);

and it results in - 1536

I have absolutely NO idea why. My enum definitions are standard for Nim and if I print out the enum value prior to passing it to C it is equal to 0.

**Comment by zacharycarter** [comment]
I'm getting there... 
(http://imgur.com/a/17871)

**Comment by zacharycarter** [comment]
Currently I'm having to hardcode two draw commands instead of being able to iterate over them. Nim is initializing all my structs and zeroing them out inside the draw command list, so I can't do a simple check of = 0 like you do in your C code. I'll figure out how to do something similar in Nim, but for now I think these bindings work. I still have to add the userdata stuff, and clean up a lot of things and port the defines over so users can specify what functionality they want / don't want like you do. 

I also plan on adding a backend for https://github.com/Halsys/nim-bgfx. I'll be using both of these projects in my game engine.

Thank you for your help, and if you feel like it, feel free to let others know about the bindings - https://github.com/zacharycarter/nuklear-nim (I understand if you want to wait for them to mature a bit - just posting this now so I don't forget).
