### ISSUE TITLE
NK_COMMAND_CUSTOM

### ISSUE THREAD

**Issue by ClaasJG** [vurtun/nuklear#352]
Good evening,

It is easy to extend this library (#265 as example) as long as you are working with nuklear.h but pretty hard when using a binding to use the provided functionality in an other language.

A custom command type would be useful, one that simply calls a callback that can be used to populate the  draw_list.

I made a small 'implementation mockup' here: https://github.com/ClaasJG/nuklear/commit/4c25cd34f5ef83b2bdf403ec332fdd159347e332

Have a nice day,
ClaasJG

**Comment by vurtun** [comment]
No problem. Just create a PR. I see no reason to not add a custom command type. It does not break any existing code or prevents someone to just add his own command version in C.
