### ISSUE TITLE
Center widgets in nk_layout_row_static

### ISSUE THREAD

**Issue by fr500** [vurtun/nuklear#355]
```
            nk_layout_row_static(ctx, 220, 280, items);
            for (int i=0; i < history_entries.count; i++)
               content_entry_widget(ctx, &history_entries.entry[i], 0, items, history_entry_cb);
```

I have this code, content_entry_widget is a custom button.

![screenshot 2017-02-25 11 47 33](https://cloud.githubusercontent.com/assets/1721040/23333818/b5512e22-fb60-11e6-9acd-9052835e2792.png)

I want to center the whole row into the window (right pane is a different borderless window), how do I achieve this?

**Comment by vurtun** [comment]
Not 100% sure what you mean. Do you mean `nk_spacing` to offset a row?

**Comment by fr500** [comment]
Hmm I guess I picked the wrong screenshot and wording. I don't want to center the widgets inside the row.
I want center the row inside the window

![image](https://cloud.githubusercontent.com/assets/1721040/23334331/4865de0c-fb6a-11e6-8bcd-f7eaa3102044.png)

**Comment by vurtun** [comment]
Hm. So you don't want the change the spacing between your widgets to fill out the row. Instead you want to basically keep the current spacing but move all six widget a little to the right to center them inside the window?

**Comment by fr500** [comment]
yes, exactly

**Comment by vurtun** [comment]
Basically how I would do it is a combination of the row template layouting API and `nk_spacing`. Basically something like this:

```c
/* setup row layout */
nk_layout_row_template_begin(ctx, 220);
nk_layout_row_template_push_dynamic(ctx);
for (int i=0; i < history_entries.count; i++)
    nk_layout_row_template_push_variable(ctx, 280);
nk_layout_row_template_push_dynamic(ctx);
nk_layout_row_template_end(ctx);

/* do your widgets */
nk_spacing(ctx, 1);
for (int i=0; i < history_entries.count; i++)
    content_entry_widget(ctx, &history_entries.entry[i], 0, items, history_entry_cb);
nk_spacing(ctx, 1);
```

**Comment by fr500** [comment]
Wow, that did the trick perfect (for one row).

```
         int i;
         /* setup row layout */
         nk_layout_row_template_begin(ctx, 220);
         nk_layout_row_template_push_dynamic(ctx);
         for (i=0; i < items; i++)
            nk_layout_row_template_push_variable(ctx, 280);
         nk_layout_row_template_push_dynamic(ctx);
         nk_layout_row_template_end(ctx);

         /* do your widgets */
         i = 0;
         for (int j=1; j <= 1 + history_entries.count / items; j++)
         {
            nk_spacing(ctx, 1);
            for (; i < items * j && i < history_entries.count; i++)
               content_entry_widget(ctx, &history_entries.entry[i], content_current_id, activate && nk_window_is_active(ctx, "Content"), items, history_entry_cb);
            nk_spacing(ctx, 1);
         }

         content_entries = history_entries.count;
```

**Comment by fr500** [comment]
Oh I guess you edited it retroactively I hadn't noticed, I'll test your solution later today

**Comment by vurtun** [comment]
Yeah I fucked up a little. I though you already calculated the number of columns and rows beforehand. So I had to divide up the space first to make sure it would work with just your `history_entries.count` value.

**Comment by fr500** [comment]
Thanks, I really appreciate all the help.
I have a followup question.

In the same window, particularly on the main menu, I might have another section (per-google guidelines)
Like this (this is a static row layout):
![image](https://cloud.githubusercontent.com/assets/1721040/23344715/08f9b19a-fc4f-11e6-9ba3-6fad3896d53f.png)

So if I add a second area with the same layout template things get screwy, like this:
![image](https://cloud.githubusercontent.com/assets/1721040/23344708/fac2bad6-fc4e-11e6-8c24-9ca13f510b40.png)

**Comment by fr500** [comment]
Follow up
Maybe it's a compiler issue?

The issue manifests itself differently depending on the optimization level, with O0 this happens:
![screenshot 2017-02-26 19 30 24](https://cloud.githubusercontent.com/assets/1721040/23345324/4720fa5e-fc5a-11e6-86c6-bdb79799066a.png)

**Comment by fr500** [comment]
~~erased comments, issue on my end~~
