### ISSUE TITLE
Closing "Window" and title collision?

### ISSUE THREAD

**Issue by Chillance** [vurtun/nuklear#361]
Hey,

I love this library. I'm actually using the Go wrapper: https://github.com/golang-ui/nuklear/

So, looking at https://github.com/vurtun/nuklear/blob/master/demo/node_editor.c I was wondering how exactly would I be able to know that the "Close" button was pressed on a node?

I use the NK_WINDOW_CLOSABLE flag to show the "x" there.

Looking at the code, the nk_window_is_closed function looked useful, but that didn't work because it looks up the title on NK_WINDOW_TITLE...

I haven't dived into what the difference is, but I noticed this:

nk_begin : title_hash = nk_murmur_hash(name, (int)title_len, NK_WINDOW_TITLE);
nk_group_begin : title_hash = nk_murmur_hash(title, (int)title_len, NK_PANEL_GROUP);

Meaning, nk_group_begin will save the title with NK_PANEL_GROUP, which the search isn't using. And, nk_window_is_closed returns 1 all the time, so it's hard to tell if it was because it was actually closed or not found...

Also, what if two nodes use the same title, but I just wanted to close one of them? Nodes may want to have the same title, so some internal unique ID would help here, although I suppose for now I could just have a counter in the title and call it "Node1" and "Node2" to separate them.

Thanks!

**Comment by vurtun** [comment]
Thanks for the issue. Under normal circumstance you could just check the result from `nk_group_begin`. If it is zero the close button was pressed. But then I noticed that I fucked up while rewriting `nk_group_begin`. I will fix it ASAP. As for the group title as long as you don't need the scrollbar offsets you can use the same name for every group with `nk_group_begin` or if you do you can either use `nk_group_scrolled_offset_begin` or `nk_group_scrolled_begin`.

**Comment by Chillance** [comment]
Thanks for quick response. However, now I get:

nuklear.h:20646: nk_group_scrolled_end: Assertion `g->parent' failed.

**Comment by Chillance** [comment]
So, I added your little code snippet, and that makes it work as I want. :)

**Comment by vurtun** [comment]
> Not sure if that is a "workaround" though, as one would think that the nk_begin_group should take care if it

First of read this: https://github.com/vurtun/nuklear/issues/350 since I already talked about it a little bit.
Short version I could store the state (hidden/closed) of the group in the library but then each title would has to be unique. Furthermore it does not make sense to duplicate the state since your node already has the state by pure existence. If a node exist the group exists. If the node was closed the node will be removed.

> it need to know it was closed, so I can remove it from the list I have keeping track of the nodes

```c
static int show_group =  1;
if (show_group) {
    nk_layout_row_dynamic(ctx, 100, 1);
    int res = nk_group_begin(ctx, "Node", NK_WINDOW_CLOSABLE|NK_WINDOW_BORDER);
    show_group = res != NK_WINDOW_CLOSED;
    if (res && show_group) {
        /* ... */
        nk_group_end(ctx);
    }
}
```
If you want to know if the close button was pressed check variable `res` for `NK_WINDOW_CLOSED`. If closed was pressed remove your node from the list.

**Comment by Chillance** [comment]
Ok, great! Thanks, and yes, I use this logic now to remove the node from the list and it works great.

I hope there will be more documentation about this very cool library.
