### ISSUE TITLE
Text editor filters don't work sometimes

### ISSUE THREAD

**Issue by jpcima** [vurtun/nuklear#362]
Sometimes the text edit lets any character go through without applying the filter.
I don't know what condition causes this, it has happened to me by pure luck but you may be able to reproduce it with perseverance, by quickly mashing a pair of keys, one which is valid and one which is not.
Look at the text boxes in the screenshot for the bug in action. This is extended.c running on amd64 Linux in case this matters.

![nuklear-bug](https://cloud.githubusercontent.com/assets/17614485/23565462/fd8fa01e-004d-11e7-828d-a4b68ddd9c87.png)

**Comment by vurtun** [comment]
Commit: d5ea545a2be6412c5147581a21d66ce378d892f3 hopefully fixes that issue, but I am not 100% sure. I tried some button mashing but at least in this version I was not able to get bad input.

**Comment by jpcima** [comment]
This seems to work for me as well. 👍
