### ISSUE TITLE
Example of use of 'rounding' attribute of styles

### ISSUE THREAD

**Issue by thomasarnbjerg** [vurtun/nuklear#365]
I assume that the 'rounding' attribute for the edit field, window and button styles related to the corner appearance. 
However I can't make it work.

Is there an example somewhere?

br
Thomas

**Comment by vurtun** [comment]
Hey,
just set the value in `ctx->style.xxxx.rounding `to a rounding number.
For example to set button rounding:

```c
/* after this all buttons use rounding */
ctx->style.button.rounding = 8;
```
