### ISSUE TITLE
Menubar without a window

### ISSUE THREAD

**Issue by codecat** [vurtun/nuklear#370]
In dear imgui it is possible to create a menubar globally, without it being attached to any window. This doesn't immediately seem possible with nuklear, or maybe I'm overlooking something. I'd love to have this feature.

**Comment by rokups** [comment]
Did you try creating a window that is just as big as menu bar?

**Comment by skyhisi** [comment]
If you create a window with only the flags `NK_WINDOW_NO_SCROLLBAR | NK_WINDOW_BACKGROUND` then it won't look like a window, you only get a box to draw in.
