### ISSUE TITLE
Multi-level submenus possible?

### ISSUE THREAD

**Issue by rokups** [vurtun/nuklear#372]
Is it possible to create multi-level submenus like here?
![](https://raw.githubusercontent.com/wiki/ocornut/imgui/web/v140/test_window_05_menus.png)

I tried following:

        nk_menubar_begin(nk);
        {
            nk_layout_row_dynamic(nk, 40, 1);
            if (nk_menu_begin_symbol_label(nk, "Foo", NK_TEXT_ALIGN_LEFT, NK_SYMBOL_TRIANGLE_RIGHT, nk_vec2(110,120)))
            {
                nk_layout_row_dynamic(nk, 40, 1);
                nk_menu_item_label(nk, "Bar", NK_TEXT_RIGHT);
                if (nk_menu_begin_symbol_label(nk, "Baz", NK_TEXT_ALIGN_LEFT, NK_SYMBOL_TRIANGLE_RIGHT, nk_vec2(110,120)))
                {
                    nk_layout_row_dynamic(nk, 40, 1);
                    nk_menu_item_label(nk, "Zap", NK_TEXT_RIGHT);
                    nk_menu_end(nk);
                }
                nk_menu_end(nk);
            }
        }
        nk_menubar_end(nk);

However clicking on "Baz" crashes with `int nk_nonblock_begin(nk_context*, nk_flags, nk_rect, nk_rect, nk_panel_type): Assertion !(panel->type & NK_PANEL_SET_POPUP)' failed.`

**Comment by zhouxs1023** [comment]
@ropups pls ref  comment#346(https://github.com/vurtun/nuklear/issues/346)

**Comment by rokups** [comment]
Thank you. Should have searched although this was unexpected.
