### ISSUE TITLE
Overflowing long window titles

### ISSUE THREAD

**Issue by borodust** [vurtun/nuklear#375]
Long window titles are not clipped when width of the titlebar is less than the width of the text.
From demo:
```c
        /* GUI */
        if (nk_begin(ctx, "Very long name for the window it is indeed", nk_rect(50, 50, 230, 250),
            NK_WINDOW_BORDER|NK_WINDOW_MOVABLE|NK_WINDOW_SCALABLE|
            NK_WINDOW_MINIMIZABLE|NK_WINDOW_TITLE|NK_WINDOW_CLOSABLE))
        {
```
Result:
![unclipped](https://cloud.githubusercontent.com/assets/2681281/24075269/fbe4ce74-0c28-11e7-8634-facad69f083d.png)

Lib version: 1.33.0

**Comment by vurtun** [comment]
Thanks for the quite embarrassing issue. Should be hopefully fixed now.
