### ISSUE TITLE
Horizontal scroll by mouse wheel / touch not possible

### ISSUE THREAD

**Issue by seibelj** [vurtun/nuklear#377]
I do not see a way to send horizontal scroll events. Some mice have a horizontal wheel like this:

![image](https://cloud.githubusercontent.com/assets/1383154/24084922/65eaf528-0cc9-11e7-9aee-a2c2acab9c63.png)

And touch screens make it very easy to scroll horizontally. But `nk_input_scroll()` seems to only handle vertical scrolling. Is there some modifier I can set to enable this? or maybe `nk_input_scroll` should take an argument for the scrolling direction?

**Comment by vurtun** [comment]
OK that is hilarious. I have never seen a mouse like that. Is that even comfortable at all? As for horizontal scrolling. It should be quite easy to add. Preferably without breaking any existing code. So in general to fix this code I either could create two additional functions `nk_input_scrolls(enum scroll_direction, float) and `nk_input_scrollh`. Or I could change the current function `nk_input_scroll` like you said.

**Comment by dumblob** [comment]
I'm raising my hand for:
>Or I could change the current function `nk_input_scroll` like you said.

**Comment by seibelj** [comment]
Haha, I had a mouse with a horizontal scroll many years ago, but mostly I want to handle the touch screen case, as it's very easy to scroll horizontally and is a common UI situation on mobile devices. I will be issuing a PR for allegro5 backend once this is implemented with proper touch-screen scrolling and some other fixes.

However you think is best is good with me. I would recommend not breaking previous code, if possible, as that will require all backends that handle scrolling to change.

**Comment by vurtun** [comment]
I added horizontal scrolling in commit: 45af48aab37474cc0db1d985edf02bd61f6a5e48. I did some testing but implementation could contain bugs. I changed all platform backends to now provide a `nk_vec2` for scrolling.
