### ISSUE TITLE
Reopening windows

### ISSUE THREAD

**Issue by rokups** [vurtun/nuklear#379]
I am trying to make a file selection widget.

I tried rendering window only when needed, but when i am done with it if i do not call `nk_begin`/`nk_end` on next frame - it crashes.

I tried creating window `NK_WINDOW_HIDDEN` but it crashes immediately due to missing layout.

I tried creating window with `NK_WINDOW_CLOSABLE`, however there seems to be no function that reopens a closed window. Clicking `x` also immediately reopens window instead of closing it.

So what is the right way to close/reopen a window?

**Comment by vurtun** [comment]
Thanks for the issue. Looks like at some point I added `NK_WINDOW_CLOSED` for no reason and it broke the close button. Hopefully should be fixed in commit: 944af0eb4cd02d6ec9f6527d3d698aed619ebe87.

**Comment by rokups** [comment]
Thank you for the fix. For the next poor soul looking for information this is how it is done:

```cpp
static bool is_open = false;
if (is_open)
{
    if (nk_begin(ctx, ...))
    {
    }
    else
        is_open = false;
    nk_end(ctx);
}
is_open |= nk_button_label(ctx, "Open Window");

**Comment by vurtun** [comment]
For normal window hiding behavior with `NK_WINDOW_CLOSABLE` this should be sufficient:
```c
if (nk_begin(ctx, ..., ...|NK_WINDOW_CLOSABLE)) {
    /* ... */
}
nk_end(ctx);
```

**Comment by rokups** [comment]
Can such window be reopened after closing?

**Comment by vurtun** [comment]
Yes I even wrote the function name in the last comment. You can use `nk_window_show` to make it visible again.
