### ISSUE TITLE
Multi-line comment in nuklear_sfml_gl3.h

### ISSUE THREAD

**Issue by JayhawkZombie** [vurtun/nuklear#380]
This is just small thing, but on line 295 of [sfml_nuklear_gl3.h](https://github.com/vurtun/nuklear/blob/master/demo/sfml_opengl3/nuklear_sfml_gl3.h), a multi-line comment is started but it isn't properly terminated.  
For some compilers it might not be an issue, but Visual Studio is unhappy (I'm using 2015 here).  It's ignoring the \#if0 on line 294 and interpreting every line from 295 - 314 as one huge comment, thus ignoring the \#endif and removing the declaration of nk_sfml_clipboard_copy.    
Changing line 299 from  

    if(text) nk_textedit_paste(edit, text, nk_strlen(text));  

to  

    if(text) nk_textedit_paste(edit, text, nk_strlen(text)); */  

resolved the issue.

**Comment by vurtun** [comment]
Thanks for the issue should be fixed in commit: 1a87c13d84f0f67171aa4b014ca9433eaf1dfd38.
