### ISSUE TITLE
Rendering text with no window

### ISSUE THREAD

**Issue by rokups** [vurtun/nuklear#386]
Is it possible to render text without a window somehow? Think FPS counter in the corner, just plain non-interactive text on whatever background is behind. Or maybe it is possible to have window without background and not receiving any input? Quick look at the code revealed `nk->style.window.background` but it is not used anywhere in code. Please advise.

Thank you.

**Comment by vurtun** [comment]
Yes. Create a window and set `nk->style.window.fixed_background` to `nk_style_item_hide`.

**Comment by rokups** [comment]
Thanks! But what about no input? Clicking on such transparent window would bring it to the front. Naturally clicking on such window would block input to any thing else visible on the screen.
