### ISSUE TITLE
Drawing without vertex

### ISSUE THREAD

**Issue by ktb92677** [vurtun/nuklear#394]
Hi, back in the day when this project was originally being developed there was a feature where I could draw the entire UI just using nice shapes like triangles and squares. Is this feature still here? If so which of the examples models this? My graphics capabilities unfortunately don't go beyond drawing squares, circles, triangles and text.

Thank you for your time

**Comment by ktb92677** [comment]
Let me be a little bit more clear. So my graphics capabilities are limited to drawing squares, triangles, circles etc of one solid color only. It used to be that the entire UI could be draw with just these types of elements (with a little bit of scissoring). Is this still possible as I noticed in all the examples this feature isn't here anymore.

**Comment by ktb92677** [comment]
As an example of what I want take a look at this file: https://github.com/vurtun/nuklear/blob/307a94b499bf032b5d3045c50058ecc577da510c/example/demo/demo.c

Look at the "draw" function

**Comment by vurtun** [comment]
Shape draw commands still exist. On how to use look at  `nk_xlib_render` inside `demo/x11/nuklear_xlib.h`. Just iterate over each draw command and call your own drawing functions. Some time ago I however changed it so the default library requires you to be able to draw shape outlines as well (mainly just rectangle shape outline). Main reasoning was that some drawing operation involving alpha were not possible by just drawing solid shapes.
