### ISSUE TITLE
Heap corruption issue

### ISSUE THREAD

**Issue by LennertSchneider** [vurtun/nuklear#395]
Hello,

this took me quite a while to figure out, but here it goes:
I get a heap corruption with my program and so far I've tracked it down to the function
```c
NK_INTERN void*
nk_buffer_alloc(struct nk_buffer *b, enum nk_buffer_allocation_type type,
    nk_size size, nk_size align)
```
the parameters look like this
> b = {
>   marker = 0x0026e9e0 {{active=0x00000000 offset=0x00000000 }, {active=0x00000000 offset=0x00000000 }}
>   pool = {userdata={ptr=0x00000000 id=0x00000000 } alloc=defaultAllocator}
>   type = NK_BUFFER_DYNAMIC (0x00000001)
>   memory = {ptr=0x2e792ff8 size=0x00002000 }
>   grow_factor = 2.00000000
>   allocated = 0x00000000
>   needed = 0x00001ff8
>   calls = 0x0000058b
>   size	 = 0x00000008
> }
> type = NK_BUFFER_BACK
> size = 0x00000018
> align = 0x00000004

the offending code appears to be
```c
/* check if buffer has enough memory*/
if (type == NK_BUFFER_FRONT)
    full = ((b->allocated + size + alignment) > b->size);
else full = ((b->size - (size + alignment)) <= b->allocated);
```
which wrongly results in full==false because of unsigned types and consequently no memory is allocated resulting in insufficient storage at the address being returned and therefore in a buffer overrun later on.

after nk_buffer_alloc returns the buffer b looks like this
> b = {
>   marker	0x124c6cb8 {{active=0x00000000 offset=0x00000000 }, {active=0x00000000 offset=0x00000000 }}
>   pool = {userdata={ptr=0x00000000 id=0x00000000 } alloc=defaultAllocator}
>   type = NK_BUFFER_DYNAMIC (0x00000001)
>   memory = {ptr=0x2e792ff8 size=0x00002000 }
>   grow_factor = 2.00000000	
>   allocated = 0x00000000
>   needed = 0x00002010
>   calls = 0x0000058c
>   size = 0xfffffff0
> }
which is bogus, if I'm not mistaken.
`nk_buffer_alloc` called internally via
```c
nk_buffer_alloc(nk_buffer * b, nk_buffer_allocation_type type, unsigned int size, unsigned int align) 
nk_draw_list_push_command(nk_draw_list * list, nk_rect clip, nk_handle texture) Line 6732	C++
nk_draw_list_add_clip(nk_draw_list * list, nk_rect rect) Line 6780	C++
nk_convert(nk_context * ctx, nk_buffer * cmds, nk_buffer * vertices, nk_buffer * elements, const nk_convert_config * config) Line 7761	C++
```
Cheers.

**Comment by vurtun** [comment]
> which wrongly results in full==false because of unsigned types and consequently no memory is allocated resulting in insufficient storage at the address being returned and therefore in a buffer overrun later on.

Do you mean you had an overflow since I used `unsigned` instead of `nk_size`?

**Comment by LennertSchneider** [comment]
yes, it appears so.

changing

>else full = ((b->size - (size + alignment)) <= b->allocated);

to

> else full = ((int)(b->size - (size + alignment)) <= (int)b->allocated);

solves the problem. then, full == true for the supplied buffer, a larger memory block is allocated and everything appears fine.

**Comment by vurtun** [comment]
Ah ok but casting to int is not a good idea here. Rather I would propose using `NK_MAX` to make sure it does not underflow:
```c
    if (type == NK_BUFFER_FRONT)
        full = ((b->allocated + size + alignment) > b->size);
    else full = ((b->size - NK_MIN(b->size,(size + alignment))) <= b->allocated);

```

**Comment by LennertSchneider** [comment]
great. thanks for the quick fix...
