### ISSUE TITLE
Graceful failure for nk_convert()

### ISSUE THREAD

**Issue by rokups** [vurtun/nuklear#396]
It would be great if we could have `nk_convert()` return a status and fail gracefully when there is not enough space in `vertices` or `elements` (fixed) buffers. Currently we are forced to allocate max possible amount for containing all GUI data, but once we hit the limit application crashes. If we had this change we could just enlarge buffers on failure and retry.

**Comment by vurtun** [comment]
I will add a result flag. You can already check all three buffers if full by checking if `needed` is greater than `allocated`.
