### ISSUE TITLE
Please add NK_WINDOW_NO_INPUT flag

### ISSUE THREAD

**Issue by rokups** [vurtun/nuklear#399]
ImGui has [ImGuiWindowFlags_NoInputs ](https://github.com/ocornut/imgui/blob/master/imgui.h#L490) flag which prevents window from receiving focus or any keyboard or mouse input. Could we get such flag? 

I previously asked about rendering text with no window (#386). Since we can render transparent windows all we need is a way to get rid of input to create an illusion of free-floating widgets.

Thank you

**Comment by vurtun** [comment]
> window from receiving focus or any keyboard or mouse input. Could we get such flag?

So this is window but not widgets specific? Or in other words the window itself does not get input for scaling, moving or focus but the widgets inside the window still get input?

**Comment by rokups** [comment]
Actually i am not entirely sure how ImGui does it. My usecase is just to display text so i would take no input for entire window and it's widgets.

However if it is not much trouble i believe people would certainly make use of two flags that provide both behaviors.

How about..
`NK_WINDOW_NO_INPUT` - window itself would not get any input and stay in the background while widgets may be interacted with.
`NK_WINDOW_NO_INPUT_ALL` - neither window nor it's widgets can get any input and window is always in the background.

Though flags could use better names..

**Comment by vurtun** [comment]
The `NK_WINDOW_NO_INPUT_ALL` behavior would be a combination of `NK_WINDOW_ROM` and `NK_WINDOW_NO_INPUT` so not really needed (probably still a good idea to define it as combination).

**Comment by rokups** [comment]
I made a quick testcase:

```cpp
    auto bg = nk->style.window.fixed_background;
    nk->style.window.fixed_background = nk_style_item_hide();
    if (nk_begin(nk, "Static Window", nk_rect(0, 0, 100, 100), NK_WINDOW_ROM))
    {
        nk_layout_row_dynamic(nk, 20, 1);
        nk_label(nk, "asdasd", NK_TEXT_ALIGN_LEFT);
        static float val = 0;
        val = nk_propertyf(nk, "#",-1000, val, 1000, 1, 1);
    }
    nk_end(nk);
```

This actually yields a transparent window whose widgets can not receive any input, but clicking that window still brings it in front of other free-floating windows. Ill try your changes in a second (that was fast).

**Comment by rokups** [comment]
Creating window with both `NK_WINDOW_NOT_INTERACTIVE` and `NK_WINDOW_NO_INPUT` makes window no longer react to any input. Its perfect for me but i guess one of them was meant to still allow widget interaction right?

**Comment by rokups** [comment]
Also something funky going on here:

```cpp    auto bg = nk->style.window.fixed_background;
    nk->style.window.fixed_background = nk_style_item_hide();
    if (nk_begin(nk, "Static Window 1", nk_rect(100, 100, 100, 100), NK_WINDOW_NOT_INTERACTIVE | NK_WINDOW_BACKGROUND))
    {
        nk_layout_row_dynamic(nk, 20, 1);
        nk_label(nk, "asdasd", NK_TEXT_ALIGN_LEFT);
        static float val = 0;
        val = nk_propertyf(nk, "#",-1000, val, 1000, 1, 1);
    }
    nk_end(nk);
    if (nk_begin(nk, "Static Window 2", nk_rect(200, 100, 100, 100), NK_WINDOW_NO_INPUT | NK_WINDOW_BACKGROUND))
    {
        nk_layout_row_dynamic(nk, 20, 1);
        nk_label(nk, "asdasd", NK_TEXT_ALIGN_LEFT);
        static float val = 0;
        val = nk_propertyf(nk, "#",-1000, val, 1000, 1, 1);
    }
    nk_end(nk);
    nk->style.window.fixed_background = bg;

    if (nk_begin(nk, "Floating Window", nk_rect(50, 50, 100, 100), NK_WINDOW_BORDER | NK_WINDOW_SCALABLE | NK_WINDOW_MOVABLE | NK_WINDOW_TITLE))
    {
        nk_layout_row_dynamic(nk, 20, 1);
        nk_label(nk, "asdasd", NK_TEXT_ALIGN_LEFT);
        static float val = 0;
        val = nk_propertyf(nk, "#",-1000, val, 1000, 1, 1);
    }
    nk_end(nk);
```

Only one of these two static windows may exist. If they are both present then nothing is rendered at all. `nk_convert()` simply does not produce any vertices or indices. Is this related?

**Comment by vurtun** [comment]
Hm not sure does it still render ok if you remove `NK_WINDOW_BACKGROUND` from one of them?

**Comment by rokups** [comment]
Only first window is visible when:
```cpp
    if (nk_begin(nk, "Static Window 1", nk_rect(100, 100, 100, 100), NK_WINDOW_NOT_INTERACTIVE | NK_WINDOW_BACKGROUND))
    if (nk_begin(nk, "Static Window 2", nk_rect(200, 100, 100, 100), NK_WINDOW_NO_INPUT))
```
Windows seem to be visible on first frame only and disappear completely when:
```cpp
    if (nk_begin(nk, "Static Window 1", nk_rect(100, 100, 100, 100), NK_WINDOW_NOT_INTERACTIVE))
    if (nk_begin(nk, "Static Window 2", nk_rect(200, 100, 100, 100), NK_WINDOW_NO_INPUT | NK_WINDOW_BACKGROUND))
```

Getting rid of `NK_WINDOW_NO_INPUT` or `NK_WINDOW_NOT_INTERACTIVE` makes them appear though.

Looks like this is solved however:

`NK_WINDOW_NOT_INTERACTIVE | NK_WINDOW_BACKGROUND` - yields a window that is always in the background and clicking it's widgets does nothing.
`NK_WINDOW_BACKGROUND` - yields a window that is always in the background but interaction with it's widgets is possible.

This is exactly what i asked for. Thank you very much!
