### ISSUE TITLE
Recursively nesting widgets

### ISSUE THREAD

**Issue by LennertSchneider** [vurtun/nuklear#400]
Hello,

I'm really struggling to understand nesting of widgets and get them to work properly.
Basically all I want is to create a custom widget within which I declare some desired layout and create my sub-widgets (either standard or more custom; it should be possible to recursively nest widgets of course).
Then I want to place multiple of these custom widgets into my window with a certain layout which should not be affected by the layout the custom widget uses within itself for its sub-widgets. The layouts on the different levels seem to interfere with each other. How can this be avoided ?

I would have guessed, that nk_widget will use the space of the current layout and pushes a new layout on the stack, but since there is no nk_widget_end or something like this, how can it know when to pop the layout from the stack, so that's not how it works apparently...
Should I just call  nk_layout_space_end after I'm done with layouting the widget (after nk_widget) ? And if so, should this be done regardless if nk_widget returned true or not ?

What's the proper way of doing so ? Can somebody enlighten me on this ?

Cheers.

**Comment by vurtun** [comment]
Do you mean `nk_group_begin` and `nk_group_end`?

**Comment by LennertSchneider** [comment]
so nk_group_begin and nk_group_end is supposed to handle exactly this ?
i started with those, but had trouble, so I wasn't sure if those are supposed to be nested and solve the problem I have. 
I will use those again and report on weirednesses once I figured them out in more detail.

**Comment by LennertSchneider** [comment]
And one other question: Using groups, what's the proper way of retrieving the current space for the group ? I though it would be "nk_layout_space_bounds", but that's not really working, as can be demonstrated in this simple example:

```
struct nk_rect clientRect = nk_rect(0, 0, 800, 600);
if (nk_begin(ctx, "MainFrame", clientRect, NK_WINDOW_NO_SCROLLBAR))
{
	// let's try a 3 column layout with each row being 200px in height
	nk_layout_row_dynamic(&ctx, 200, 3);

	// insert 4 widgets to advance to the central (2x2) layout slot
	struct nk_rect widgetRect;
	for (int i = 0; i < 4; i++) nk_widget(&widgetRect, ctx);

	// *** PROBLEMATIC GROUP STARTS HERE (should be placed at the 2x2 layout slot)
	if (nk_group_begin(ctx, "GraphEditor", NK_WINDOW_NO_SCROLLBAR))
	{
		struct nk_rect rc = nk_layout_space_bounds(ctx);

		// PROBLEM HERE: rc=={272.000000, 204.000000, 256.000000, 4.000000}, WHY IS THE HEIGHT 4 instead of 200 ?

		nk_group_end(&m_nkCtx);
	}
}
nk_end(ctx);
```

What's wrong here ?

**Comment by LennertSchneider** [comment]
nk_window_get_content_region appear to do the job... hmm, i guess i'm a little confused about the names "nk_window_get_content_region" and "nk_layout_space_bounds"; it's not entirely self-explanatory ;)

**Comment by LennertSchneider** [comment]
okay, thank you for clearing this up.
