### ISSUE TITLE
Support to 9-sliced scaling skin?

### ISSUE THREAD

**Issue by eduardodoria** [vurtun/nuklear#402]
I'm trying use texture skin to resize like Unity does on UI.
If I use Nuklear with skin button and resize it, all image will be resized.
I would like to resize part of image (9-sliced way).

![9-sliced](https://cloud.githubusercontent.com/assets/11426911/24870843/079c44be-1dee-11e7-8baf-33e6b947a89b.jpg)

Does have any support for this with Nuklear or addon?

Thanks in advance.

**Comment by dumblob** [comment]
No, there is no such support - you have to add it yourself (it's not so difficult). Note though, that the 9-sliced scaling goes against independency of the triple `physical_screen_height_and_width, vertical_and_horizontal_DPI, viewing_distance` as discussed e.g. in https://github.com/vurtun/nuklear/issues/123#issuecomment-260666623 and a heuristics library interface proposal in https://github.com/vurtun/nuklear/issues/283#issuecomment-271161978 .

**Comment by eduardodoria** [comment]
Ok, I will try to do it.
If anybody is doing similar job, please help me.

**Comment by mario-deluna** [comment]
@eduardodoria Hello, have you been able to implement the slicing? And if so would you mind sharing some information about the implementation?

**Comment by eduardodoria** [comment]
Sorry, @mario-deluna, I have not done it yet.
