### ISSUE TITLE
nk_widget() wrongly returning NK_WIDGET_ROM

### ISSUE THREAD

**Issue by LennertSchneider** [vurtun/nuklear#403]
Hello,

there are situations where nk_widget() will wrongly return NK_WIDGET_ROM causing e.g. buttons not to respond to input at all.
It happens when multiple columns are used in the layout and each column gets a non-integer width. That, plus no padding anywhere leads to the following problem:

```
/* allocate space  and check if the widget needs to be updated and drawn */
    nk_panel_alloc_space(bounds, ctx);
    win = ctx->current;
    layout = win->layout;
    c = &layout->clip;
```

bounds will have non-integer positioning and/or sizes; in my case bounds={x=374.666656, y=260.000000, w=60.0000000, h=12.0000000}
c will have that same value

then this code comes into play

```
/* need to convert to int here to remove floating point error */
    bounds->x = (float)((int)bounds->x);
    bounds->y = (float)((int)bounds->y);
    bounds->w = (float)((int)bounds->w);
    bounds->h = (float)((int)bounds->h);
```

and finally the problem happens here

```
if (!NK_CONTAINS(bounds->x, bounds->y, bounds->w, bounds->h, c->x, c->y, c->w, c->h))
        return NK_WIDGET_ROM;
```

where the condition evaluates to FALSE, and therefore into returning NK_WIDGET_ROM preventing all input from being processed even though the button is fully visible and the mouse is hovering over it or even clicking it - nothing.

What's the best solution here ? Also round c ? Round neither ? Hmmm...

Cheers.

**Comment by vurtun** [comment]
OK this is quite a shitty situation. The reason why I have to convert to int at that position is #207. So the best idea probably would be to cast the clipping rectangle to int as well.

**Comment by LennertSchneider** [comment]
that's what i tried and it seems to solve at least my shitty situation. ;)

**Comment by vurtun** [comment]
OK than I will changes it as well hopefully not causing any problems.

**Comment by LennertSchneider** [comment]
great.
