### ISSUE TITLE
Memory allocation and nk_foreach infinite loop bug

### ISSUE THREAD

**Issue by seibelj** [vurtun/nuklear#406]
This is related to https://github.com/vurtun/nuklear/issues/376

I have got into a situation where `nk_foreach` loops forever, thus hanging the program in the backend render.

`nk__next` is supposed to return 0 on this line:

`if (cmd->next >= ctx->memory.allocated) return 0;`

In my backend, I added these lines of code inside of the `nk_foreach` of the `render()` method:

```
printf("COMMAND TYPE: %d\n", cmd->type);
printf("NEXT COMMAND: %lu\n", cmd->next);
printf("MEMORY ALLOCATED: %lu\n", (&allegro5.ctx)->memory.allocated);
```

When entering the infinite loop case, it prints out this:

```
[...]
COMMAND TYPE: 16
NEXT COMMAND: 720
MEMORY ALLOCATED: 1008
COMMAND TYPE: 5
NEXT COMMAND: 752
MEMORY ALLOCATED: 1008
COMMAND TYPE: 4
NEXT COMMAND: 784
MEMORY ALLOCATED: 1008
COMMAND TYPE: 16
NEXT COMMAND: 856
MEMORY ALLOCATED: 1008
COMMAND TYPE: 1
NEXT COMMAND: 880
MEMORY ALLOCATED: 1008
COMMAND TYPE: 2
NEXT COMMAND: 912
MEMORY ALLOCATED: 1008
COMMAND TYPE: 2
NEXT COMMAND: 0
MEMORY ALLOCATED: 1008
COMMAND TYPE: 5
NEXT COMMAND: 32
MEMORY ALLOCATED: 1008
COMMAND TYPE: 16
NEXT COMMAND: 96
MEMORY ALLOCATED: 1008
[...]
```

Notice how `cmd->next` never surpasses `(&allegro5.ctx)->memory.allocated`, and then gets reset to 0.

I'm not sure why this happens. I would appreciate if @vurtun or someone else with deep knowledge of the nuklear internals can give some insight.

For now, I'm going to put a hack into my backend that breaks from the loop if `cmd->next` resets back to 0. I believe that in special edge-cases `cmd->next` is either going to 0, or it isn't correctly exceeding `(&allegro5.ctx)->memory.allocated` when it should be.

**Comment by vurtun** [comment]
Sounds like a bit harder to debug bug to track down. The problem if originating in nuklear is probably located inside `nk_build` which fixes and builds up the internal command list. Do you use nuklears mouse pointer?

**Comment by seibelj** [comment]
I have seen this randomly, but the 100% reproducible case was caused by resizing the window, and then clicking the second button in a window containing 3 buttons. The other 2 buttons didn't cause the issue. So strange. I'm not sure what you mean by "nuklears mouse pointer", I do send mouse events to nuklear via the backend.

**Comment by vurtun** [comment]
> 'm not sure what you mean by "nuklears mouse pointer", I do send mouse events to nuklear via the backend.

This already shows me you are not using it :smiley:. Does this only happen in your specific backend or can you reproduce it in any other backend as well? That would at least help me further limit the possible solution.

**Comment by seibelj** [comment]
Unfortunately I can't test my specific issue with other backends, because my code is so tightly coupled to allegro, without some significant refactoring. It could just be mine, I very easily could have introduced a bug somewhere

**Comment by Visse** [comment]
Hello, I think I hit the same bug. In my case I managed to track it down to closing a window, causing the next frame to loop forever in nk_foreach. After some debugging I came up with a test case, but unfortunately I'm not familiar enough with the internals of nuklear to fix it.
I couldn't figure out how to attach a file with the test case, but here is the code (excluding initialization code) that triggers the bug.
```
    { // Frame 1
        nk_begin(&ctx, "Window", nk_rect(20,20,20,20), 0);
        nk_end(&ctx);

        nk_convert(&ctx, &cmds, &vertices, &elements, &config);
        nk_clear(&ctx);
    }
    { // Frame 3 - Show a popup
        nk_begin(&ctx, "Popup window", nk_rect(20,20,20,20), NK_WINDOW_TITLE);
        nk_end(&ctx);

        nk_begin(&ctx, "Window", nk_rect(20,20,20,20), 0);
        nk_end(&ctx);

        nk_convert(&ctx, &cmds, &vertices, &elements, &config);
        nk_clear(&ctx);
    }
    { // Frame 3
        nk_begin(&ctx, "Window", nk_rect(20,20,20,20), 0);
        nk_end(&ctx);

        // This function never returns - loops forever in nk_foreach
        nk_convert(&ctx, &cmds, &vertices, &elements, &config);
        nk_clear(&ctx);
    }
```

**Comment by vurtun** [comment]
@Visse Thanks for your test case I found the bug. Basically all windows that are not updated each frame are garbage collected by `nk_clear`. However the conversion from primitives to vertexes happens before that. So I tried to access a window that no longer is in existence but created an infinite loop. The bug is hopefully now fixed.

**Comment by seibelj** [comment]
Wow! Good catch @vurtun and @Visse
