### ISSUE TITLE
Font is too smooth

### ISSUE THREAD

**Issue by AlesTsurko** [vurtun/nuklear#408]
Not sure if it's a bug of `nuklear` or if it's a bug at all, but... It's tedious to read the text in the examples on macOS because of the font smoothness. Is it possible to control/disable this smoothness?
![screen shot 2017-04-13 at 02 45 32](https://cloud.githubusercontent.com/assets/8686568/24984837/bc0d5742-1ff8-11e7-989e-21ab5fdf441b.png)

**Comment by DmitryHetman** [comment]
Disable rainbow (RGB subpixel antialiasing) in OS.

**Comment by DmitryHetman** [comment]
Install Gentoo and use bitmap font.

**Comment by vurtun** [comment]
@AlesTsurko you could try playing around with  `oversample_v` and  `oversample_h` inside `struct font_config`. Or even set both to `1` and set `pixel_snap` to `nk_true`.

**Comment by AlesTsurko** [comment]
Thanks! The native-like result is the one with oversampling factor equals to `4`. With factor of `1` and `pixel_snap = nk_true` it's still hard to read.
