### ISSUE TITLE
bgfx example

### ISSUE THREAD

**Issue by hsdk123** [vurtun/nuklear#410]
Hi, this is a great library - fast, easy to use UI with customisable skinning really opens up possibilities. I was wondering if it might be possible to provide an example using bgfx in order to leverage it's abstraction over different renderers (and hence extended portability).

**Comment by vurtun** [comment]
Sorry but  have no time at all besides work, fixing 50+ issues, writing documentation and the next [GUI](https://gist.github.com/vurtun/65977fcff17e413721dbd1191cda719d) library to work myself into other frameworks or libraries. I am already at my limit here and need to watch out not to burnout. However if you want to provide an example as PR I will pull it.

**Comment by dumblob** [comment]
Googles first result: https://github.com/bkaradzic/bgfx/issues/1047

**Comment by Qix-** [comment]
Why not re-open this and tag it as "help wanted"? The link @dumblob provided is not an example by any measure as it shows non-working code and the user never showed how they fixed it.

**Comment by revolucas** [comment]
https://gist.github.com/carloscm/36324265dd14b7934f1fef5ccf977e26

**Comment by dumblob** [comment]
@revolucas looks instructive - would you be willing to make a PR, so that it can be included in this repo? Note though, it might get some time to get reviewed - see https://github.com/vurtun/nuklear/pull/913#issuecomment-544428265
