### ISSUE TITLE
Double Click support

### ISSUE THREAD

**Issue by LennertSchneider** [vurtun/nuklear#412]
Hello,

is it planned to add double-click support ? Or do you have recommendations on how to handle double-clicks with the current system ?

Cheers.

**Comment by rokups** [comment]
Maybe something like:
```c
int was_selected = selected;
if (nk_selectable_label(nk, "label", NK_TEXT_ALIGN_LEFT, &selected))
{
    if (was_selected && selected)
    {
        // double-clicked
    }
}
```
You should better describe what you are trying to achieve.

**Comment by dumblob** [comment]
I would guess @LennertSchneider would want to employ some "better" handling of the timeout between clicks and not rely on exactly the time between two consecutive frames. On the other hand it should be dead easy to store the value of a kernel monotonic counter at the last mouse click and always just subtract it from a newly read value of the counter. This could be even embedded into `ctx` as user data.

**Comment by vurtun** [comment]
Hm I already have a delta time value inside `nk_context` with `delta_time_seconds` which is currently optional for scrollbar hiding after timeout. Should be possible to internally have a fixed time a click has to happen after a previous click to be registered as a double click.

**Comment by LennertSchneider** [comment]
ah, i missed the delta_time_seconds. yeah, that should do the job nicely. thank you.

**Comment by vurtun** [comment]
Like I said currently it doesn't do much at the moment but I think I can write a commit to support double click with it.

**Comment by vurtun** [comment]
I added double-click support to a number of platforms. However currently missing are all the windows specific platforms (@mmozeiko I would be grateful if you could help me out), allegro and sfml 
(@ricanteja would be cool if you could help me out). I decided not directly pull double-click behavior into nuklear and instead pushed it into platform specific code. They main reason is that different platforms have different double-click behavior glfw/glfw#462 or even worse none at all like X11.

**Comment by mmozeiko** [comment]
Sure, I'll update Windows platform demo code.

**Comment by mmozeiko** [comment]
If user double clicks mouse button, what kind of events nuklear expects to be generated? From x11 demo it looks like it will receive - left down, double up, left up, double down, left down, double up, left up. Can double up event can be passed to nk_input_button even if it doesn't happen? And is it ok to pass double down before second left down event?

For SDL it looks like it will happen like this - left down, left up, double down, left down, double up, left up.
For glfw it looks like there will be only - double down, double up. Without any left down/up events. Is this ok behavior?

**Comment by vurtun** [comment]
>  Can double up event can be passed to nk_input_button even if it doesn't happen? And is it ok to pass double down before second left down event?

`nk_button` only keeps track of and reacts to state changes and does not care if `left down` is before `double down`. So the desired sequence in all demos should be registered in nuklear as: 
>left down, left up, left down, double down, left up, double up

or valid as well is:

>left down, left up,  double down, left down, left up, double up

or finally:

> left down, left up,  double down, left down,double up, left up

The GLFW demo keeps track of both single mouse click as well as double. But only double click is handled inside the button callback. Normal button clicks are handled in `nk_glfw3_new_frame`.
The SDL automatically as correct behavior and keeps track of double-click up and down internally.

**Comment by mmozeiko** [comment]
Go it. That makes sense. Thanks.
