### ISSUE TITLE
Cannot create a subwindow

### ISSUE THREAD

**Issue by bkeys** [vurtun/nuklear#414]
Lets say I want to create a subwindow in nuklear, and my logic is like this (I know my example's code is not 
valid Nuklear code), but hopefully my example will show what is going on.
```
nk_begin(...)
// Widgets . . .
nk_begin(...)
// more widgets
nk_end()
nk_end()
```
Now this works if the windows are not "nested" in eachother, Is this the intended way to use Nuklear? Or am I doing something wrong? None of the provided examples seem to use nested windows in the way I am talking about.

**Comment by vurtun** [comment]
You probably want to look at `nk_group_begin` and `nk_group_end`.
