### ISSUE TITLE
nk_property expected behaviour

### ISSUE THREAD

**Issue by mhalber** [vurtun/nuklear#416]
Hi,

I have just started experimenting with nuklear, but I am finding that nk_property_<...> class of functions is behaving oddly. This might be a bug or I am doing something incorrectly.

1. When editing value backspace press seem to be registering multiple event often deleting 3-5 characters with single press
2. Is drag event supposed to happen? When trying to drag I often get the value changing once, using **inc_per_pixel** increments.
3. Is NK_BUTTON_REPEATER supposed to allow hold down events? I seem to be unable to have that working using either **nk_button_set_behavior** or **nk_button_push_behavio**r

Those are observed when running the included example code for glfw3. I am running mac os.

Thanks!

**Comment by vurtun** [comment]
Thanks for the issue.
> When editing value backspace press seem to be registering multiple event often deleting 3-5 characters with single press

On which backend does this happen. I tested X11 and SDL2 and Backspace seems to work for me correctly.

> Is drag event supposed to happen? When trying to drag I often get the value changing once, using inc_per_pixel increments.

Not sure what you mean. Dragging the label will cause the value to be changed by `pixel_dragged * inc_per_pixel`. At least that is what it is supposed to be doing.

> Is NK_BUTTON_REPEATER supposed to allow hold down events? I seem to be unable to have that working using either nk_button_set_behavior or nk_button_push_behavior

This is a mistake on my end. I will push my commit that will let you use `nk_button_push_behavior` to change button behavior. I also added selection, clipboard and select all support in edit mode.

**Comment by mhalber** [comment]
Oh ok, my bad - i've only checked the glfw3 backend. Checking with sdl2 the dragging and backspace work as intended. 

So basically the issue is that in the glfw3 backend the nk_property functions do not work correctly.
- Backspace registered multiple times per key press
- Dragging the label does not work

Thanks!

**Comment by vurtun** [comment]
OK I get the same Backspace behavior in GLFW. In seems like `glfwGetKey` returns the current state as `GLFW_PRESS` in repeating fashion. I will take a closer look. As for dragging, just to make sure horizontally dragging the label does not work?. If so could you try deactivating the optional dragging behavior inside `nk_nuklear_glfw_gl3.h` (should be `if` conditions inside `nk_glfw3_new_frame`.

**Comment by mhalber** [comment]
I do not think the optional behaviour is the main issue here. I think it has to do more with the lines:
~~~~~~~
if (ctx->input.mouse.grabbed) {
        glfwSetCursorPos(glfw.win, ctx->input.mouse.prev.x, ctx->input.mouse.prev.y);
        ctx->input.mouse.pos.x = ctx->input.mouse.prev.x;
        ctx->input.mouse.pos.y = ctx->input.mouse.prev.y;
   }
~~~~~~~
It seems that if mouse is grabbed we continuously reset mouse position to previous, effectively disabling any mouse movement. Commenting our optional dragging behaviour to make mouse visible and above lines get the same behavior in glfw3 as in sdl2 backend.

**Comment by vurtun** [comment]
That was what I meant. Seems like I fucked up I wanted to write "the two optional dragging behavior". Does it work now?

**Comment by mhalber** [comment]
Yes, the dragging works after removing these lines. 
Also, in the new commit the editing of the label(backspace issue) seems to be fixed as well!

Thanks for the help!

**Comment by vurtun** [comment]
Good to hear. There is still one behavior I do not like which is overflowing the editing space seems to be broken but that is not as essential as your three issues so I will close this issue and if someone wants to see that fixed should open a new issue.
