### ISSUE TITLE
Button should be clicked on mouse up event

### ISSUE THREAD

**Issue by mrDIMAS** [vurtun/nuklear#417]
Hi!

I'm porting my project from imgui to nuklear, and mouse click behaviour of nuklear is different from imgui.
This is quite annoying, that when I pressing mouse button, the hovered gui button immediately becomes clicked. 

This behaviour is annoying for other widgets too. Can you do something with that?

**Comment by vurtun** [comment]
Could you clarify what you mean. Do you want click behavior to happen on button up (release) instead of button down (pressed)? If so then look at define `NK_BUTTON_TRIGGER_ON_RELEASE`.

**Comment by mrDIMAS** [comment]
Thanks! That is exactly what I want. Next time I should read documentation more carefully.
