### ISSUE TITLE
Erratic behaviour rendering plenty of elements

### ISSUE THREAD

**Issue by LennertSchneider** [vurtun/nuklear#419]
Hello,

I'm using Win/OpenGl backend, use the same openGl interface code as your filebrowser demo (just cranking up vertex- and element-buffer sizes to 10MB (10 * 1024 * 1024)) and get a really weired effect drawing a large number of elements (this should draw a grid of 200x200 red dots):

```
	struct nk_rect rc = nk_rect(0, 0, 800, 600);
	nk_begin(ctx, "MainFrame", rc, NK_WINDOW_NO_SCROLLBAR);
	for (int y = 0; y < 200; y++)
	{
		for (int x = 0; x < 200; x++)
		{
			nk_stroke_line(nk_window_get_canvas(ctx), x<<1, y<<1, x<<1, (y<<1) + 1.0f, 1.0f, nk_rgba(255, 0, 0, 255));
		}
	}
	nk_end(ctx);
```

This will result in a screwed up rendering and erratic behaviour (like hangs, sometimes crashes). I suppose some heap corruption takes place. Unofrtunately I lack the proper tools to locate it :/

Using 100x100 will result in a proper rendering, though. But still sometimes it will hang. Do you maybe have some tools to detect heap corruptions you can try on this example ?

Cheers.

**Comment by vurtun** [comment]
What type is your `nk_draw_index` typedef? By default it is `nk_ushort` so just two bytes. Try changing it to `nk_uint` and don't forget to also change your vertex layout. If the wrong behavior still shows itself I need to take another look.

**Comment by LennertSchneider** [comment]
ah, that's a good hint. i wasn't aware of this default. could well be the reason. i'll give it a try.
though, maybe an assertion when exceeding this limit would be useful in any case.
i'll let you know how the test turns out...

**Comment by LennertSchneider** [comment]
hmm, just setting the nk_draw_index type to nk_uint won't do the job. still screwed. you said "don't forget to also change your vertex layout", but i don't see were it depends on the index type. what do you mean exactly ?

**Comment by vurtun** [comment]
>  maybe an assertion when exceeding this limit would be useful in any case

I would love to do that. But `nk_draw_index` is a typedef and I don't have templates.
So I have no way of finding out the correct type maximum values to check against.

> "don't forget to also change your vertex layout"

You right my mistake not vertex layout I meant:
`glDrawElements(GL_TRIANGLES, (GLsizei)cmd->elem_count, GL_UNSIGNED_SHORT, offset);`
needs to be changed to:
`glDrawElements(GL_TRIANGLES, (GLsizei)cmd->elem_count, GL_UNSIGNED_INT, offset);`
if not  changed already.

**Comment by LennertSchneider** [comment]
ah, right. i'm not used to OpenGL. I'm more of the D3D kinda person, but I need this project to be cross-platform for mac ;)

you can close this then. rendering glitch fixed now. thank you !
