### ISSUE TITLE
Initialize nk_edit_string with value

### ISSUE THREAD

**Issue by kns1966** [vurtun/nuklear#421]
First, no doubt I'm missing the obvious.

I'm using nk_edit_string to collect parameters (integers). I would also like to read existing parameters from a configuration file.  To that end, can I initialize the text box - make it visible - with a known value?  I've used sprintf to copy values to the third parameter but these values don't appear.

I guess the same question applies to nk_propertyi.

Thanks.

**Comment by vurtun** [comment]
Hm not really sure what you mean. Basically you have a already filled buffer, a length parameter and want to use `nk_edit_string`? So then you just need to set the `length` parameter to the length of your buffer content:

```c
char buffer[256];
strcpy(buffer, "This is some content");
int len = strlen(buffer);
/* ... */
if (nk_begin(...)) {
    /*...*/
    nk_edit_string(&ctx, NK_EDIT_FIELD, buffer, &len, sizeof(buffer),0)
}
nk_end(...);
/*...*/
```

**Comment by kns1966** [comment]
Thank you.  The length parameter was wrong.
