### ISSUE TITLE
Issues compiling for IOS in 64 bits

### ISSUE THREAD

**Issue by Fra-Ktus** [vurtun/nuklear#426]
While I was able to get the SFML example to run I had to overwrite the definitions of those 2 types

#define NK_POINTER_TYPE unsigned long
#define NK_SIZE_TYPE unsigned long

I think the 64 bit IOS is not correctly detected.

**Comment by vurtun** [comment]
You could just define `NK_INCLUDE_FIXED_TYPES` which includes `stdint.h` and directly set correct types size for your specific platform. I have no intention to specific each type size directly in nuklear. If you do not want nuklear to include any standard library header you should also be ok with directly defining specific types sizes.

**Comment by Fra-Ktus** [comment]
Thanks for the help, I didn't know that. I will use NK_INCLUDE_FIXED_TYPES from now on.
Congratulations for the great work!
