### ISSUE TITLE
Correct method for stopping UI passthrough?

### ISSUE THREAD

**Issue by jediminer543** [vurtun/nuklear#428]
How do I determine wether events passed to nuklear are actually used by nuklear? In other gui libraries, the event handling functions return a boolean as to wether the event was used or not. Is there a similar feature in nuklear, I.e. to stop you clicking on an in-game-world thing behind a gui? The same for key press events.

**Comment by vurtun** [comment]
Thanks for your issue. Please have a look at `nk_item_is_any_active`.

**Comment by jediminer543** [comment]
Thanks, thats what I was looking for; sorry I had to raise it here, but couldn't find what function to use.

**Comment by vurtun** [comment]
Hm. ` nk_item_is_any_active` is actually one of the already documented functions. I just don't have any "soft" documentation for it at the moment.
