### ISSUE TITLE
Font rendering (in label): characters not crisp and rendered inconsistently

### ISSUE THREAD

**Issue by LennertSchneider** [vurtun/nuklear#429]
Hi,

I#m using RobotoLight as my font, but font rendering generally looks not very crisp and the weired thing is that the same char will be rendered inconsistently even within the same label.

E.g. check out the three one's here:
![test_render](https://cloud.githubusercontent.com/assets/26762650/25785706/74d78c88-3387-11e7-9794-d0a55783999c.png)

Do you have any idea what could cause this ? Is there any quick way to get it more consistent and less blurry ?

Cheers.

**Comment by vurtun** [comment]
Hey, similar to this: #408 you can try playing with `oversample_v` and `oversample_h`.

**Comment by LennertSchneider** [comment]
okay, thank you. I'll give this a try...

**Comment by LennertSchneider** [comment]
much better now !

though i was wondering why at pixel_snap there is this comment
"// align every character to pixel boundary (if true set oversample (1,1))"
while it does look MUCH BETTER ignoring this requirement and set oversample to 7 nevertheless... is the comment outdated ? has it drawbacks ?
