### ISSUE TITLE
Add a license file to the project repository

### ISSUE THREAD

**Issue by zaolin** [vurtun/nuklear#430]
Hey,

could you please add a license file to your project. We are trying to use your 
library in our free and open source project: www.coreboot.org
It's not clear which license is used. Otherwise we will get in big trouble using it.

Best Regards, Zaolin

**Comment by zaolin** [comment]
Also using public domain is really bad for companies to use it. Maybe you want to change it to BSD / MIT license instead of public domain https://en.wikipedia.org/wiki/BSD_licenses

**Comment by dumblob** [comment]
https://github.com/vurtun/nuklear/issues/94#issuecomment-212524042
