### ISSUE TITLE
add nk_separator() and nk_separator_line()

### ISSUE THREAD

**Issue by jube** [vurtun/nuklear#435]
Would you mind adding `nk_separator()` (which would add an empty vertical space between two widgets) and `nk_separator_line()` (same but with a line drawn)?

For now, I use `nk_layout_row_dynamic(ctx, height, 0);` to achieve `nk_separator()` but I do not really know if `nk_layout_row_dynamic()` can be used safely for that.

Dear imgui has (respectivelly) `Spacing()` and `Separator()` for this purpose.

**Comment by vurtun** [comment]
Thanks for the issue. Hm I already have `nk_spacing`. Adding a `nk_separator()` which also draws a visible line should be possible to add. Will take a look tomorrow should be easy to add `nk_separator()`

**Comment by jube** [comment]
`nk_spacing()` takes a number of column but you would want a height. In fact, the ideal behavior would be to keep the current layout. For example:

```
nk_layout_row_dynamic(ctx, 20, 3);
// three widgets
nk_vspacing(ctx, 20);
// the layout is still "row dynamic 20 3"
// three other widgets on another line, separated from the previous widgets by an empty line of height 20
```

Anyway, thanks a lot for this great library!

**Comment by vurtun** [comment]
Unless I misunderstand that should be possible with `nk_spacing` since it can go over rows (at least with layouts that support it).
```c
nk_layout_row_dynamic(ctx, 20, 3);
widget(...);
widget(...);
widget(...);
nk_spacing(ctx, 3);
widget(...)
widget(...)
widget(...)
```

**Comment by jube** [comment]
Maybe I was not really clear. `nk_spacing` is more for horizontal spacing than vertical spacing. In your first example, I would like the "3" argument in the `nk_spacing` call to be determined automatically, if possible. Anyway, your solution is a good workaround for now (it is more flexible too). Thanks.

**Comment by hbiblia** [comment]
void nk_separator(struct nk_context *ctx)
{
    float height = ctx->current->layout->row.height;
    nk_layout_row_dynamic(ctx, 1, 1);
    nk_spacing(ctx, 1);
    ctx->current->layout->row.height = height;
}
