### ISSUE TITLE
Impose framerate for rendering ?

### ISSUE THREAD

**Issue by DerouineauNicolas** [vurtun/nuklear#437]
Hello,
Thank you for this nice tool that is nuklear. I'm very new to opengl, so maybe my question is completely offtopic. I'm monitoring cpu usage of the glfw_opengl2 example and it seems that rendering is done at best effort (as fast as possible). My question is the following: Is it possible to limit Cpu usage by using the display callback internally ? Is there a specific option to do that ?

**Comment by vurtun** [comment]
Not 100% what you mean. If you have a desktop application and you want to run only on user input then you should take a look inside `nuklear.h`s documentation. More specifically under drawing, where I have an example how to achieve less drawing overhead. If your program already has a continuous drawing loop then  you can freely dictate a framerate for nuklear to update.

**Comment by DerouineauNicolas** [comment]
Cool ! Thank you for taking the time to answer me !
