### ISSUE TITLE
Align rows at bottom

### ISSUE THREAD

**Issue by winghim** [vurtun/nuklear#438]
Hello, first of all thank you for this great library.
So i have a question regarding the position of rows inside a window.
For each command entered by the user i create a row containing a text field, like this:

            for(int i = history.size() - 1; i >= 0; i--) {
                auto cmd = history[i];
                nk_layout_row_dynamic(ctx, 15, 1);
                nk_label(ctx, cmd->command, NK_TEXT_LEFT);
            }

This works but new labels will be added at the top of the window. I want new items to be added at the bottom, just like in a real terminal emulator.
So my quiestion is: how do i align all rows inside a window at the bottom?

**Comment by winghim** [comment]
Am i missing something or this this currently not possible?

**Comment by vurtun** [comment]
The row layout API only works from top to bottom (it is actually not possible to grow from bottom to top because of how pure immediate mode works).  However you can use API `nk_layout_space_xxx` to allocate the complete window space an do layouting yourself and control everything.

**Comment by winghim** [comment]
Alright i see, thank you.
