### ISSUE TITLE
Possible issue in nk_font_atlas_cleanup

### ISSUE THREAD

**Issue by godlikepanos** [vurtun/nuklear#439]
From what I understand from the documentation we can call `nk_font_atlas_cleanup` to clean the caches if there is no further font backing. And then we can call `nk_font_atlas_clear` to fully destroy the atlas.

Is this how `nk_font_atlas_cleanup` is expected to be used? 

If yes then `nk_font_atlas_cleanup` should zero the `config` member var else there will be a double free on `nk_font_atlas_clear` where `nk_font_atlas_cleanup` is called again.

**Comment by vurtun** [comment]
Thanks for the issue. Should be fixed in d4f518168b5781756cc54091c6c698a7a1545a16.
