### ISSUE TITLE
nk_image function in odd place

### ISSUE THREAD

**Issue by wheybags** [vurtun/nuklear#440]
Is there any reason the nk_image function is in the TEXT section of the header? (https://github.com/vurtun/nuklear/blob/master/nuklear.h#L1762). Instead of here: https://github.com/vurtun/nuklear/blob/master/nuklear.h#L2141

I could move it and open a pr if not? Also, it'd be nice to have an explanation that that function actually draws the image, as it took me a while to figure out how to do that.

**Comment by vurtun** [comment]
No direct reason. It just did not fit any where so I put it into the text section since it is an output widget only as well. You can create a PR if you want to move it. As for explanations so far did not get to this point. There are still a lot of other subsystems and functions to document.
