### ISSUE TITLE
segfault with text with characters which are not in the font

### ISSUE THREAD

**Issue by malytomas** [vurtun/nuklear#445]
Hi, I get a segfault when trying to print following text:
"Wat Prah Buddhabat, Kingkitsarath Road, ບ້ານຊ່າງຄ້ອງ, ຫຼວງພະບາງ, ເມືອງຫຼວງພະບາງ, ຫລວງພະບາງ, 06000, ປະເທດລາວ"

The crash happens in function nk_font_text_width
on line text_width += g->xadvance * scale;
because the g (acquired by nk_font_find_glyph) is null.

The characters certainly are not in the font. But the application cannot fail on it anyway.
Instead, it should render some unknown-character-glyph.

**Comment by malytomas** [comment]
I have been using these unicode ranges:
const nk_rune FontUnicodeRanges[] = {
    0x0020, 0x007F, // Basic Latin
    0x00A0, 0x00FF, // Latin-1 Supplement
    0x0100, 0x017F, // Latin Extended-A
    0x0180, 0x024F, // Latin Extended-B
    0x0300, 0x036F, // Combining Diacritical Marks
    0x0400, 0x04FF, // Cyrillic
    0
};
When I tried it with unicode range 0x001 to 0x5000, the application did not crash, although the characters were rendered as empty space.
I am using the roboto-regular font, which seems to contain these characters (Lao, U+0E80 – U+0EFF).

**Comment by vurtun** [comment]
> The crash happens in function nk_font_text_width
on line text_width += g->xadvance * scale;
because the g (acquired by nk_font_find_glyph) is null.

OK that is quite strange. Under normal circumstances `nk_font_find_glyph` should return either
the requested glyph or a fallback glyph. By default `nk_font` uses glyph `'?'`. Could you check for me in `nk_font_find_glyph` if `font->fallback` is `NULL` for you?

**Comment by malytomas** [comment]
I see it now. I have had an error in my font initialization code. I memset it to zero, rather than initialize it with the defaults function. I wonder in which example have I found it.
Anyway, thank you for your quick response :D
