### ISSUE TITLE
D3D9 & D3D10 support

### ISSUE THREAD

**Issue by Spiderboi** [vurtun/nuklear#448]
Are you thinking of adding a demo with d3d9 & d3d10 support?
Just found this amazing piece of art.

Thanks a bunch.

**Comment by Spiderboi** [comment]
I can pay for this, since I really need it.

**Comment by Spiderboi** [comment]
I have ported it to d3d10, however d3d9 is really an obstacle for me, can anyone do this?

**Comment by vurtun** [comment]
You can take a look at https://github.com/ocornut/imgui/tree/master/examples/directx9_example which is similar to nuklear.

**Comment by Spiderboi** [comment]
I'm not that great with Direct3D, that's why I use premade GUI's in the first place.
Is it really not possible for you to add the d3d9 demo?

**Comment by vurtun** [comment]
I personally don't have a windows machine. All windows demos were written by @mmozeiko, not me.

**Comment by mmozeiko** [comment]
I don't really see need for D3D10 demo, because the API is almost exactly the same to D3D11. And almost everywhere where you can run D3D10 you can also run D3D11 (with just a small Windows udpate).

Btw current D3D11 demo should run on machines who have only D3D9 class GPU. The shaders are compiled with 9.x support. Only requirement is Windows Vista+.

I can make D3D9 example if you want to have that in repo. Do you want one, @vurtun?

**Comment by vurtun** [comment]
> I can make D3D9 example if you want to have that in repo. Do you want one, @vurtun?

@mmozeiko This is entirely your call, you already did so much for this project and can probably access the required time and effort way better than I could. @Spiderboi do you have a specific reason Directx 9.x support or does    

> Btw current D3D11 demo should run on machines who have only D3D9 class GPU. The shaders are compiled with 9.x support. Only requirement is Windows Vista+.

already meet your requirements?

**Comment by Spiderboi** [comment]
@vurtun I really need a d3d9 implementation like the d3d11 one.

@mmozeiko if you have somewhere where I can donate for your work after you're done please let me know.

**Comment by mmozeiko** [comment]
Allright, I'll do it.
No worries, I like doing this for free :)
I just need a day or two, its been a while since last time I touched D3D9.

**Comment by Spiderboi** [comment]
@mmozeiko thank you so much!

Do you also have some D3D12 knowledge?
(I don't want to seem like those people that just want more and more tbh)

**Comment by mmozeiko** [comment]
Yes, I know some of d3d12. But there is no reason to use d3d12 just for nuklear. It has no advantages over d3d11 api. It would just add more complexity without any benefits.
