### ISSUE TITLE
NK_BUFFER_DYNAMIC and nk_convert

### ISSUE THREAD

**Issue by wheybags** [vurtun/nuklear#453]
Hey, so I'm creating a buffer with nk_buffer_init_default, which should make a dynamic buffer I believe, and then using it in the nk_convert function (or rather, three buffers, cmds, vbuf, ebuf).
I would expect that since the buffer is dynamic, that the nk_convert function would dynamically resize it to fit the data it is outputting. However, this is not happening, and I'm getting a retval of NK_CONVERT_COMMAND_BUFFER_FULL.
Is this expected behaviour? I want to avoid specifying a fixed size for my buffers, and have them automatically resize to the needed dimensions.

**Comment by vurtun** [comment]
> However, this is not happening, and I'm getting a retval of NK_CONVERT_COMMAND_BUFFER_FULL.

This is definitely wrong behavior on the flag side of things. Internally resizing works without problems. These flags are only really necessary for fixed size memory buffer. However I still have to fix this. Will take a look.

**Comment by wheybags** [comment]
Nope, no clearing, should I be?

**Comment by wheybags** [comment]
Tried doing the clear, same result

**Comment by vurtun** [comment]
Just to be sure. I mean cleaning the buffer with `nk_buffer_clear`.

**Comment by wheybags** [comment]
Yup, that's what I tried

**Comment by vurtun** [comment]
A OK I am an idiot. I just remembered that `nk_buffer` is a double-buffer and specifically the command buffer is used as double buffer unlike vertex and element buffer. So if I allocate from both buffer sides each add to `needed`. However allocating from the back of the buffer decrements the internal size and does not increment the `allocated` attribute. But I use `allocated` to check if more memory was requested than provided. Should be easy to fix.
