### ISSUE TITLE
nk_property_int text input bug

### ISSUE THREAD

**Issue by wheybags** [vurtun/nuklear#458]
Hey, so input in nk_property_int widgets seems to be pretty wonky.
In the gif below I try to select the etxt and input numbers. It works the first time, but doesn't the second. In general I've found that it normally doesnt seem to work, but very occasionally does.
To clarify, I'm spamming number keys all throughout that gif.

![nk_inpu](https://user-images.githubusercontent.com/1093274/26967282-8fce7394-4cf5-11e7-98bf-2460cc4d1ed9.gif)

**Comment by vurtun** [comment]
Thanks for the issue. Real fucking nasty bug caused by past changes to `nk_widget`. While correct it brought in stated behavior because of properties internal complexities. Hopefully should be fixed now.

**Comment by wheybags** [comment]
Great, thanks!
