### ISSUE TITLE
sdl without opengl

### ISSUE THREAD

**Issue by laoshaw** [vurtun/nuklear#459]
can this work with just SDL2 on top of framebuffer for embedded devices? if so an example will be nice.

**Comment by vurtun** [comment]
You presume you mean using `SDL_Renderer` to draw primitives and SDL_TTF for font or optional directly using nuklears font baker, yes it should be possible. However I personally have no interest in writing another backend. Especially if almost everything SDL2 outside actual renderer can be copied from already existing SDL2 backends.
