### ISSUE TITLE
have more demo on windows ?

### ISSUE THREAD

**Issue by sgf** [vurtun/nuklear#460]
have saw the d3d and gdi demo,
But it seems too simple.
was there more demos on win32 ?
like the image on project home:
![Image on HomePage](https://cloud.githubusercontent.com/assets/8057201/13538240/acd96876-e249-11e5-9547-5ac0b19667a0.png)

**Comment by vurtun** [comment]
I think having backends for gdi, gdip, DirectX 9, DirectX 10 and DirectX 11 is more than enough. Your referenced screenshot can be recreated with each one of these backends.

**Comment by sgf** [comment]
ok,thanks reply
