### ISSUE TITLE
nk_edit_string bug ?

### ISSUE THREAD

**Issue by sgf** [vurtun/nuklear#463]
![textedit_string](https://user-images.githubusercontent.com/2557696/27182207-02839790-520d-11e7-95d9-f63dbd8ec16b.gif)

when press "BackSpace"
cant clear the text ,just always placed by ‘t’ ?

**Comment by sgf** [comment]
ok,know why.need:
``buffer[len] = 0x00;

**Comment by vurtun** [comment]
Side note there is also another edit widget: `nk_edit_string_terminated` which already handles zero terminated strings.

**Comment by sgf** [comment]
thank you.
