### ISSUE TITLE
How to hide the console window

### ISSUE THREAD

**Issue by testcheng307** [vurtun/nuklear#467]
On windows 10 platform,when I build some project,like nuklear-master\demo\gdi project ,build and run it ,found there always has a console window behind the main window. How to hide it or get rid of it?

thanks!

**Comment by fr500** [comment]
trye adding -mwindows to the linker flags

**Comment by testcheng307** [comment]
the build.bat file use cl.exe for compiler, it is MSVC compiler,it seems there is no -mwindows option.

**Comment by testcheng307** [comment]
at last,I find a method:
`//in the main function,before running the event loop,insert it:
ShowWindow(GetConsoleWindow(),SW_HIDE);
`
it is not very perfect,the console will twinkle and hide,but work.

**Comment by paulsapps** [comment]
for MSVC its /subsystem:windows

**Comment by ASHIT-AXAR** [comment]
i could get rid of console with this command:
```/link/subsystem:windows /entry:mainCRTStartup
```
in case of failure:
```/link /subsystem:windows /entry:mainCRTStartup user32.lib
```
(altering sequence may cause failure)
