### ISSUE TITLE
Window dragging does not match up with cursor position

### ISSUE THREAD

**Issue by EternityX** [vurtun/nuklear#470]
Hi there,

Whenever dragging a window, it will lag way behind the cursor.
Any ideas what would cause this?

Small video demonstrating the issue: 
https://www.youtube.com/watch?v=d6M_yXTib8c

**Comment by dumblob** [comment]
Duplicate of https://github.com/vurtun/nuklear/issues/297 (there is a software cursor available for this reason).

**Comment by xissburg** [comment]
@dumblob this is not a related issue. In this case it seems the cursor displacement is being scaled down, perhaps because of a high dpi/retina screen.
