### ISSUE TITLE
line_thickness<=0

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [vurtun/nuklear#472]
I'm trying to remove border from Button or Window. I know I can do this with:
```c
style.border=0;
style.border_color=nk_color(0,0,0,0);
```
But I don't understand why draw commands like `nk_stroke_line, nk_stroke_curve, nk_stroke_rect, nk_draw_list_stroke_poly_line, ...` is drawing with `line_thickness<=0`. Shouldn't it skip drawing it shuch situation?
```c
if(line_thickness<=0) return;  // ignore drawing when line_thickness<=0 - invisible
```
Then I could just write:
```c
style.border=0;
```
and it would work without drawing invisible (transparent) lines - less drawing commands and more logic (I think).

**Comment by vurtun** [comment]
Hey, while for windows you can just specify no border by not passing in `NK_WINDOW_BORDER` it is definitely a problem of unneeded draw calls. I will push a commit disregarding zero lines.
