### ISSUE TITLE
How to create an nk_image from scratch

### ISSUE THREAD

**Issue by valera-rozuvan** [vurtun/nuklear#476]
I am generating a 3D fractal, and want to output it as a 2D image inside a nuklear window. The 2D image in my program is represented as a 1D array. Each pixel gets 4 values (RGBA).

Looking at the definition of struct `nk_image`, I see:

```
struct nk_image { nk_handle handle; unsigned short w, h; unsigned short region[4]; };
```

What's the purpose of `region`? What should be the format of my data, if I want to place a pointer to it in the variable `handle`? Also, how should I format my data for the function `nk_draw_image` to work correctly with my image?

```
NK_API void nk_draw_image(
    struct nk_command_buffer*,
    struct nk_rect,
    const struct nk_image*,
    struct nk_color
);
```

**Comment by vurtun** [comment]
To provide nuklear with a 2D image use one of:

```c
NK_API struct nk_image nk_image_handle(nk_handle);
NK_API struct nk_image nk_image_ptr(void*);
NK_API struct nk_image nk_image_id(int);
NK_API int nk_image_is_subimage(const struct nk_image* img);
NK_API struct nk_image nk_subimage_ptr(void*, unsigned short w, unsigned short h, struct nk_rect sub_region);
NK_API struct nk_image nk_subimage_id(int, unsigned short w, unsigned short h, struct nk_rect sub_region);
NK_API struct nk_image nk_subimage_handle(nk_handle, unsigned short w, unsigned short h, struct nk_rect sub_region);
```
As for the region member variable. You can specify a image subsection to draw instead of drawing the whole image.

**Comment by valera-rozuvan** [comment]
Looking at the implementation of `NK_API struct nk_image nk_image_ptr(void *ptr)`, I see the line:

```
s.handle.ptr = ptr;
```

What should the pointer be pointing to in my case? The 1D array? Or to some complex structure?

**Comment by vurtun** [comment]
Are you using any graphics API? For example in OpenGL you just pass in a texture handle as int and it generates and bufffers 4 vertexes and 6 indexes internally. Finally in nuklears drawing loop the passed texture handle will be binded and the your texture will be blitted to screen. For DirectX you would just pass a texture pointer. However currently I only support 2D textures.

**Comment by valera-rozuvan** [comment]
I am using GLFW + GLEW.

**Comment by valera-rozuvan** [comment]
So using the function *nk_draw_image* is not suggested? The best approach is to render the 1D array (full of RGBA pixels) to an OpenGL 2D texture, and then let nuklear handle that? How do I make sure that the texture gets rendered only in a specific nuklear window?

**Comment by valera-rozuvan** [comment]
OK. So I am trying to render a texture inside a nuklear window. So far I was not able to achieve this using the snippet you provided above. Here is the code I have: https://github.com/mandelbulb-4d/mandelbulb-4d/blob/91c3d3ea4ea74ecb7dd2a2e5bbbe3be43466d3d1/src2/simple_window/drawing.cpp .

Please note that the current version of the code draws a line using `nk_stroke_line` function, then creates a texture from a 1D array, and then I am at a loss of how to output this texture to the current nuklear window.

Can you please help me?

**Comment by valera-rozuvan** [comment]
This is how I am trying to draw the texture: https://github.com/mandelbulb-4d/mandelbulb-4d/blob/a3b9ee89a5ed3f3046204bcaa3e8a6a9c52f7a0c/src2/simple_window/drawing.cpp#L51 . But I am getting some weird results:

![image](https://user-images.githubusercontent.com/2273090/27911284-34ed78d6-6261-11e7-938a-f48bc9987a0a.png)

**Comment by valera-rozuvan** [comment]
I found what the problem was. I was deleting the texture before `nuklear` had a chance to use it. So it was drawing garbage data from memory :)
