### ISSUE TITLE
Should this link using -lglfw or -lglfw3 on macOS Sierra (10.12.5)?

### ISSUE THREAD

**Issue by rdmello** [vurtun/nuklear#484]
From the instructions on the [wiki page for macOS](https://github.com/vurtun/nuklear/wiki/Getting-Started-on-Mac), I used `$ brew install glfw3` to install `glfw3` and also installed `glew`. However, when running `make`, I get the following error: 

    $ make
    rm -f bin/demo 
    cc main.c -std=c99 -pedantic -O2 -o bin/demo -lglfw3 -framework OpenGL -framework Cocoa -framework IOKit -framework CoreVideo -lm -lGLEW -L/usr/local/lib
    ld: library not found for -lglfw3
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [demo] Error 1

This seems to be fix itself when I replace `-lglfw3` in the above command with `-lglfw`.

Any idea what's going on here? is my system configuration messed up, or is Homebrew installing a different version of `glfw3`?

**Comment by dumblob** [comment]
The related [homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/glfw.rb ) provides all answers :wink:.

**Comment by rdmello** [comment]
thanks for that...so if I use `$ brew install glfw3` it will only install the shared library `libglfw.dylib`, but if I use `$ brew install glfw3 --without-shared-library` then it can install `libglfw3.a`.
