### ISSUE TITLE
How do I detect if the user is hovering over a widget?

### ISSUE THREAD

**Issue by dustContributor** [vurtun/nuklear#485]
Hi! I wanted to implement cursor changing logic to some widgets, like clickable stuff. Say, changing the cursor to the classical "hand" when you're hovering a clickable button, or some clickable text, etc. 

Cursor's aren't something Nuklear deals with but I'd need it to tell me if the widget is being hovered over for me to change the cursor through whatever windowing API I'm using.

**Comment by vurtun** [comment]
> Hi! I wanted to implement cursor changing logic to some widgets, like clickable stuff. Say, changing the cursor to the classical "hand" when you're hovering a clickable button, or some clickable text, etc.

What you a looking for is `nk_widget_is_hovered`:

```c
if (nk_begin(...))
    nk_layout_xxx(...);
    if (nk_widget_is_hovered(...))
        cursor = CURSOR_HAND;
    if (nk_button_xxx(...) 
        printf("button pressed!\n");
} nk_end(...)
```
> Cursor's aren't something Nuklear deals with but I'd need it to tell me if the widget is being hovered over for me to change the cursor through whatever windowing API I'm using.

Not 100% true. Nuklear has cursor handling just no platform depended cursor handling.

**Comment by dustContributor** [comment]
Interesting! I'd rather retain the "hardware cursor" anyway instead of tying it to my framerate but good to know nevertheless.

From what I gather in the sources, nk_widget_is_hovered checks if the mouse is inside the current layout's bounds? So I'd have to put it after defining the layout of any widget of interest right?

**Comment by vurtun** [comment]
> From what I gather in the sources, nk_widget_is_hovered checks if the mouse is inside the current layout's bounds? So I'd have to put it after defining the layout of any widget of interest right?

Hm I would formulate it a little bit differently. A layout has multiple slots for widgets and `nk_widget_is_hovered` needs to be after layout slot definition (happens automatically for `nk_layout_row_static` and `nk_layout_row_dynamic`) and before actually calling your widget.

```c
// Example 1
nk_layout_row_dynamic(ctx, 25, 1);
if (nk_widget_is_mouse_clicked(ctx, NK_BUTTON_LEFT))
    printf("clicked!\n");
nk_property_int(ctx, "Compression:", 0, &property, 100, 10, 1);

// Example 2
nk_layout_row_begin(...); {
    nk_layout_row_push(...);
    if (nk_widget_is_mouse_clicked(ctx, NK_BUTTON_LEFT))
        printf("clicked!\n");
    nk_property_int(ctx, "Compression:", 0, &property, 100, 10, 1);
    nk_layout_row_push(...);
    nk_widget(...);
} nk_layout_row_end(...);
```

**Comment by dustContributor** [comment]
Heh, found a bug? :smile: 

I see, makes sense. This should work, I'll try it out once I have the setup working, I still have to do the legwork of separating a block of text into different kinds (hoverable/clickable is what I wanted for this case). 

Thanks!
