### ISSUE TITLE
Dynamic columns?

### ISSUE THREAD

**Issue by dustContributor** [vurtun/nuklear#487]
Hi again!

I'm trying to specify some text blocks that will have different kinds of text inside the same paragraph.

Something like:

"This is some normal text with **colored text** in between
that could have **many lines of text** in the middle"

My idea to render this was to do it like:

```java
createRow();
  drawNormal("This is some normal text with ");
  drawColored("colored text ");
  drawNormal("in between");
createRow();
  drawNormal("that could have  ");
  drawColored("many lines of text ");
  drawNormal("in the middle");
```

I've managed to do the text wrapping by myself (to avoid the issue of Nuklear having to re-calculate text lines every frame that we've discussed before), but I'm not sure how to do the layouts.

For instance, this would be my text drawing loop (pardon my Java :smile: )
```java
// For each text line.
for ( LineIterator lines : textWrapper ) {
  nk_group_begin( ctx, "somegroup", 0 ); // This is expecting some flags? No idea which.
  // For each segment inside each line.
  while ( lines.hasNext() ) {
    TextSegment str = lines.next();
    switch ( s.kind() ) {
      case NORMAL:
        nk_text( ctx, str, NK_TEXT_LEFT );
        break;
      case COLORED:
        nk_text_colored( ctx, str, NK_TEXT_LEFT, someColor );
        break;
      // These could be a few more.
      default:
        break;
    }
  }
  nk_group_end( ctx );
}
```
Basically, I have each line divided, and inside each line, I have segments of text that have to be drawn in different ways (normally, colored, selectable, etc).

This actually doesn't renders anything and crashes if I scroll down as soon as it tries to clip anything. I don't really know how to use nk_group.

Is there a way to draw the text segments next to eachother without having to specify how many segments/widgets will be in the same row? nk_layout_row_template_push_dynamic puts the text next each-other fine *but* I have to "push" as many columns there will be before issuing the nk_text* calls.

I think I could pre-compute how many segments I'll have in each line just fine, then push as many columns as needed for each row before issuing the nk_text calls, but I was wondering about this sort of dynamic column scenario since I've tried to do it before for other things.

**Comment by dumblob** [comment]
I didn't try this scenario, but I'm feeling sorry for you having to close it before anyone tried to help. The one thing I would say about this is, that using `nk_layout_row_template_push_dynamic` and anything with "row" layouting is in my opinion a wrong and not really functional way of achieving the results you expect.

For text manipulation I would recommend looking at the nuklear source code to find out how word-wrapping is done and trying to implement the necessary functionality you've described in this issue in a similar way.

**Comment by dustContributor** [comment]
Don't worry about it, as you can see the issue was over 1 year old already. In #536 I detailed the solution I came up with. Basically making my own text wrapping (because I had perf issues with Nuklear's) and generating text widgets for each styled segment.
