### ISSUE TITLE
filebrowser example on opengl2(windows)

### ISSUE THREAD

**Issue by techfreakworm** [vurtun/nuklear#490]
Hello, your library was really easy to use once I got the knack of it. Problem is:
`filebrowser.c` example that you provided in `nuklear/example/`, does it only work in OpenGL 3? Since, when I tried to run it with OpenGL 2 code (using `nuklear_glfw_gl2.h` ) after removing OpenGL 3 specific code, it compiles fine but fails at runtime at `glGenerateMipmap(GL_TEXTURE_2D)` in `icon_load` function (got to know using Visual Studio debugger). I checked its documentation on `khronos.org` , it stated it's supported since OpenGL 3 and not before.

But, in that case. I used the same `filebrowser.c` code with OpenGL 2 with same header and same modifications and it worked fine on Linux as well as Mac. Can you give me any pointer to solution? Any help is appreciated.

**Comment by techfreakworm** [comment]
I don't know why and how. I removed:
```
if (glewInit() != GLEW_OK) {
		fprintf(stderr, "Failed to setup GLEW\n");
		exit(1);
	}
```
Adding it back made the GUI work.

**Comment by RicoP** [comment]
I believe glewInit() initializes glew and is necessary for everything to work.
