### ISSUE TITLE
[Question] What is expected from NK_COMMAND_RECT_MULTI_COLOR?

### ISSUE THREAD

**Issue by griebd** [vurtun/nuklear#493]
Hi all, I'm trying to put together a xcb/cairo backend!
BUT I'm in doubt about NK_COMMAND_RECT_MULTI_COLOR...

I know nk_color_picker uses it, so I'm using it to test my implementation. Both the hue and alpha bars are working (at least they look like the opengl demos), BUT  the color matrix is completely wrong/different!!! And that suggests/means that my implementation is not right...

So my question, I don't know if I really understood what to do with the NK_COMMAND_RECT_MULTI_COLOR command.

Thanks for any help!

**Comment by kphillisjr** [comment]
I agree that this needs better documentation, however there is a lot that can be figured out... For example, this command uses the following Struct to render out...
``` C
struct nk_command_rect_multi_color {
    struct nk_command header;
    short x, y;
    unsigned short w, h;
    struct nk_color left;
    struct nk_color top;
    struct nk_color bottom;
    struct nk_color right;
};
```
Using the above information, I have found Two key implementations of this which can be of use... 
**Example 1:** The old LibSDL1.2 w/ SDL_gfx ( https://sourceforge.net/p/sdlgfx/ ) renderer. This was removed a while back shortly after inclusion, and can be found on the following branch... 
https://github.com/glegris/nuklear4j/tree/sdl1.2/demo/sdl1_2
**Example 2:** Any of the 3D sample rendering sample platforms. For the most part this means OpenGL, Direct3D and possibly others. At any rate all of these platforms require that ```
 NK_INCLUDE_VERTEX_BUFFER_OUTPUT ``` be defined before including ```nuklear.h```.

The above examples included some C/C++ code to show how to interpolate the ``` NK_COMMAND_RECT_MULTI_COLOR``` command. The below code is taken from the SDL1.2 sample code that was removed from the main repository...
``` C
static void
interpolate_color(struct nk_color c1, struct nk_color c2, struct nk_color *result, float fraction)
{
    float r = c1.r + (c2.r - c1.r) * fraction;
    float g = c1.g + (c2.g - c1.g) * fraction;
    float b = c1.b + (c2.b - c1.b) * fraction;
    float a = c1.a + (c2.a - c1.a) * fraction;

    result->r = (nk_byte)NK_CLAMP(0, r, 255);
    result->g = (nk_byte)NK_CLAMP(0, g, 255);
    result->b = (nk_byte)NK_CLAMP(0, b, 255);
    result->a = (nk_byte)NK_CLAMP(0, a, 255);
}

static void
nk_sdl_fill_rect_multi_color(SDL_Surface *surface, short x, short y, unsigned short w, unsigned short h,
    struct nk_color left, struct nk_color top,  struct nk_color right, struct nk_color bottom)
{
    struct nk_color X1, X2, Y;
    float fraction_x, fraction_y;
    int i,j;

    for (j = 0; j < h; j++) {
        fraction_y = ((float)j) / h;
        for (i = 0; i < w; i++) {
            fraction_x = ((float)i) / w;
            interpolate_color(left, top, &X1, fraction_x);
            interpolate_color(right, bottom, &X2, fraction_x);
            interpolate_color(X1, X2, &Y, fraction_y);
Y
            pixelRGBA(surface, x + i, y + j, Y.r, Y.g, Y.b, Y.a); 
        }
    }
}

/* In the Render Loop */
        case NK_COMMAND_RECT_MULTI_COLOR: {
            const struct nk_command_rect_multi_color *r = (const struct nk_command_rect_multi_color *)cmd;
            nk_sdl_fill_rect_multi_color(screen_surface, r->x, r->y, r->w, r->h, r->left, r->top, r->right, r->bottom);
} break;
```

**Comment by griebd** [comment]
Thanks, I believe I can make my code working based on this one, I have some question but I will try to solve then by myself before asking again (I think I can solve then now).

As soon as I have it working I will close this issue, ok?

Just so you know, I have never worked with OpenGL or any other of them and wasn't in the mood to learn then now... :wink: I'm trying to implement a backend using XCB/Cairo, it's mostly working already!
My point is I don't like ANY GUI toolkits/frameworks I have found/used so far, the immediate mode GUI sounds like what I would like, so I'm trying it out. (and the X11 example without Cario has to many limitations related to colors/transparency)
Oh, and if someone is thinking about CPU usage, my implementation is mostly waiting for input like in retained mode GUI so CPU usage is quite similar.

**Comment by vurtun** [comment]
> Oh, and if someone is thinking about CPU usage, my implementation is mostly waiting for input like in retained mode GUI so CPU usage is quite similar.

I have a small section inside the documentation talking about it. Beside only updating on input you can also only update on changes. This is based on managing a second buffer and doing a memcmp and then copy the contents into the second buffer and draw:
https://github.com/vurtun/nuklear/blob/master/nuklear.h#L873

**Comment by dumblob** [comment]
> then copy the contents into the second buffer and draw...

Sounds like a good opportunity for an optimization taking advantage of switching pointers instead of copying the whole buffer.

**Comment by vurtun** [comment]
> Sounds like a good opportunity for an optimization taking advantage of switching pointers instead of copying the whole buffer.

Depends. For `nk_init_fixed', 'nk_init_default' and `nk_init` it does not work. State tables, windows and panels are stored at the end of the memory buffer as well. However using `nk_init_custom` uses two allocators. One for drawing commands and the other for the tables,windows and panels. In that case it should be possible to just swap out memory pointers and reset the buffer.

Question is however if it is worth it to add additional complexity. If you combine both update on input and render only on changes the update rate can be significantly cut down. At least  for me on my now 4-5 year laptop with on-board GPU, CPU usage is non-existent. One reason is that the copied buffer is often smaller than 64kb (vertexes would be much worse) and you only copy like what 2-3 times a second tops in heavy use.

**Comment by griebd** [comment]
it works, thanks!
only problem is performance, those loops and simple, direct, Cairo fill (in memory) are taking way too long... but that is another problem! At least now I know what needs to be done...
