### ISSUE TITLE
Cursor over windows hidden with nk_window_show still trigger nk_item_is_any_active

### ISSUE THREAD

**Issue by Predelnik** [vurtun/nuklear#502]
Please correct me if it's intentional, but this seems a little bit strange to me.

**Comment by vurtun** [comment]
Thanks for the issue.
I was not really able to reproduce the problem but my guess is that an invalid condition allows popups to still trigger as active even if window itself is hidden. At least in my test cases it works correct now.

**Comment by Predelnik** [comment]
Thanks! This seems to work fine now. I've decided to close windows instead of hiding them but tested the old version and it works as expected.
