### ISSUE TITLE
Adding window with NK_WINDOW_BACKGROUND blocks active normal window

### ISSUE THREAD

**Issue by Predelnik** [vurtun/nuklear#503]
Once again I'm probably missing something here but the line
https://github.com/vurtun/nuklear/blob/a2472f8c36d77b5bc4a05d858b22bf31c61064e4/nuklear.h#L18471
in adding background window puts current normal top level window into read-only mode and I don't get why it should happen. Maybe I'm missing the meaning of `NK_WINDOW_BACKGROUND` but I thought it just changes the order of drawing and not supposed to block any other windows.

**Comment by vurtun** [comment]
Thanks for the issue.
Sadly the problem was a little bit more complex. While the flag itself is correct the actual window selection did not correctly work with windows having flag `NK_WINDOW_BACKGROUND` set. I pushed a  commit hopefully fixing the issue, but the solution is quite ugly.

**Comment by Predelnik** [comment]
Thank you for working in the issue. I checked patched version and sadly still observe the same behaviour. My case is very simple: I have normal window and it has a button by clicking on which window with `NK_WINDOW_BACKGROUND` is shown, after that button on normal window stops working.

**Comment by vurtun** [comment]
Hm. Sorry but could you create a minimal test case for me to test it. I just used the demo and set one window to background and checked if everything seems to work fine. Basically something I can copy and paste into the demo and debug.

**Comment by Predelnik** [comment]
Sorry it's GDI demo but I've just added "Demo1" window after the first one
https://gist.github.com/Predelnik/a9e4491b8d692fc7feba6093ab1feb3f
Window "Demo" stays completely frozen for me.

**Comment by vurtun** [comment]
Thanks for the simple demo example showcasing the problem and sorry for the delay I was extremely busy the last few weeks, but hopefully finally found the problem and hopefully fixed it.

**Comment by Predelnik** [comment]
Thank you!
