### ISSUE TITLE
How to display chinese text

### ISSUE THREAD

**Issue by pengyz** [vurtun/nuklear#505]
First of all ,I'm very sorry for my poor enginsh.

I try to render chinese text with unklear.

I find a wiki documentation here:
https://github.com/vurtun/nuklear/wiki/UTF-8-Support

and code like this:
````c++
//font baking
    struct nk_font_atlas *atlas = nullptr;
    struct nk_font_config config = nk_font_config(14);
    config.oversample_h = 1;
    config.oversample_v = 1;
//    config.range = nk_font_cyrillic_glyph_ranges();   //this should success with text Кнопка
    config.range = nk_font_chinese_glyph_ranges();
    nk_glfw3_font_stash_begin(&atlas);
    struct nk_font *font = nk_font_atlas_add_from_file(atlas,"../resources/fonts/DejaVuSansMono.ttf",14,&config);
    nk_glfw3_font_stash_end();
   //set the font
    if(font)
        nk_style_set_font(ctx,&font->handle);
````

as the result, It doesn't work. I'm sure the DejaVuSansMono.ttf can display chinese text for my IDE is using it.

Otherwise, I do the same thing as the documenation for test,just like this:
````C++
config.range = nk_font_cyrillic_glyph_ranges(); 
````
then the text "Кнопка" can render properly.

As I'm a beginner with nuklear and OpenGL, I have no idea about it. Is it a bug for nuklear or just for my wrong use of it ?

I need for some help. or is there any more API docs that I can reading for ?

Thanks.

**Comment by vurtun** [comment]
Hey,
the wiki documentation is correct but as far as I remember font `DejaVuSansMono.ttf` does not support chinese characers. Could you try a font you now supports chinese.

**Comment by pengyz** [comment]
Very thanks for your answer. 
I'll try it later.

**Comment by AlechinAlex** [comment]
I haven't found functions nk_font_stash_begin() / nk_font_stash_end() in hrader nuklear_xlib.h for xlib.
How I can load a font (Roboto-Light,ttf for example) into xlib?
Thanks!

**Comment by vurtun** [comment]
Hey @AlechinAlex,
not really the correct issue but whatever. Xlib is a little bit different. If you want to use the nuklear internal font baker along side OpenGL with Xlib you can look at `demo/x11_opengl3`.  If on the other hand you want to use native xlib rendering look inside `demo/x11/nuklear_xlib.h`. It has functions `nk_xfont_create` and `nk_xfont_del` to create and free linux system fonts. The string required to load is from X itself and as far as I know searches inside the system font directory for a matching font. Not quite sure if it is possible to directly specify a path to a font tough.

**Comment by AlechinAlex** [comment]
I want to use native X11 with UTF-8 kyrillic font (Roboto-Light.ttf from Demo folder for example).
I'm add to Demo/X11.main.c next code:

// font baking
struct nk_font_config config = nk_font_config(14);
config.oversample_h = 1;
config.oversample_v = 1;
config.range = nk_font_cyrillic_glyph_ranges();   //this should success with text Кнопка
/----
struct nk_font_atlas atlas;
// ?????    nk_glfw3_font_stash_begin(&atlas);   <--- not present in nuclear_xlib.h
nk_font_atlas_init_default(&atlas); 
nk_font_atlas_begin(&atlas); 
//----
struct nk_font *font = nk_font_atlas_add_from_file(&atlas,"Roboto-Light.ttf",14, &config);
/----
// ?????nk_glfw3_font_stash_end();       <--- not present in nuclear_xlib.h
nk_font_atlas_end(&atlas, font->texture, NULL); 
//---
//set the font
nk_style_set_font(ctx, &font->handle);

Then in main_loop:
if(nk_begin(ctx, "КСАДП", nk_rect(50, 50, 200, 200), NK_WINDOW_BORDER))
raise ASSERT in nuclear.h nk_begin_titled  ctx->style.font->with ".. you gorgot to add a font"

I'm trying debug this code and I'll see ctx->style.font contains only zero fields exept font->config
I think loaded font not successfully "baking".........

**Comment by vurtun** [comment]
> Xlib is a little bit different. If you want to use the nuklear internal font baker along side OpenGL with Xlib you can look at demo/x11_opengl3. If on the other hand you want to use native xlib rendering look inside demo/x11/nuklear_xlib.h. It has functions nk_xfont_create and nk_xfont_del to create and free linux system fonts. The string required to load is from X itself and as far as I know searches inside the system font directory for a matching font. Not quite sure if it is possible to directly specify a path to a font tough.

Please read what I wrote. Xlib works differently at least the demo. It does not use the font baker like all the other demos. It instead uses xlibs internal font system. So if your linux system has a font with kyrillic glyphes you can load them directly via xlib. Please look at my demo code in `demo/x11/`.

**Comment by AlechinAlex** [comment]
Sorry.
your code didn't work for me because font_name in nk_font_create is font_mask, as
"-*-fixed-*-*-*-*-*-*-*-*-*-*-utf8-r" for my
("fixed" didn't work for me).

Thanks!
