### ISSUE TITLE
Is there any explain about nk_property_int function?

### ISSUE THREAD

**Issue by stillwarter** [vurtun/nuklear#506]
I find nothing about it in the comment.
What is this function used for?

**Comment by nayyden** [comment]
Hi,

nk_property_int and nk_property_float render edit field for int and float respectively like this:

![image](https://user-images.githubusercontent.com/325479/29874073-4d9b1060-8d9e-11e7-9d31-4bef3f961511.png)

Example usage: 
``` c
nk_property_int(ctx, "Compression:", 0, &property, 100, 10, 1);
```
It's used quite much in the examples, please check them, they really help to get started.

For example: https://github.com/vurtun/nuklear/blob/9dc7323b748f3956444ddbf1ea7ca661f75379aa/demo/sdl_opengl3/main.c#L162

Best
Nayden

**Comment by stillwarter** [comment]
very thanks!
