### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by newobj** [vurtun/nuklear#515]
Hi there!

Does Nuklear support vertical alignment in any way? Specifically, I want to center things vertically. If it doesn't support it directly, are there some layout recipes I can use to achieve it? I'm pretty new to Nuklear but it seems like I have to be pretty explicit about giving it vertical pixel sizes for layout rows right now.

My specific use case is just the very generic game splash screen: logo image, then a few buttons underneath the logo for various game functions. The overall extents of the logo + buttons should be centered vertically in the screen.

Thanks!
Brian

**Comment by vurtun** [comment]
Hey,
I presume you mean something like this: #512 (The vertical menu). I would recommend reading the documentation for layouting inside the header file. I know RTFM is shitty but sadly if I don't know how it should look like I cannot clarify which of the layouting function you need or would be best. Easiest case you could just center the window itself and use `nk_layout_row_dynamic` or `nk_layout_row_static` and worse case scenario you would have to create an transparent window and place widget by `nk_layout_row_space_xxx` or depending on your problem one of the utility function between.

**Comment by newobj** [comment]
Thanks for the reply! No, I don't really mean that. In the image you posted, what I'm saying is that I would like that vertical menu (or any container full of random widgets) and place it vertically and horizontally centered on the screen. I have read the documentation, and it's really not apparent if there's any support in Nuklear for this. Well, it's apparent that Nuklear does not support vertically centering out of the box. Which suggests that I need to calculate the height of the container somehow and position it at the correct height myself? I guess? But how I calculate the height of the container? (Say, the menu, in this case.)

**Comment by newobj** [comment]
I could simplify this case a lot; how do I put a text label at the exact center of the screeen using nuklear? (e.g., so the CENTER of the label is at the center of the screen, not the "top center" or anything like that.) I imagine that doing the same thing for a "container" would not be much different... ?

**Comment by DeXP** [comment]
@newobj What about Wordlase's [language select menu](https://wordlase.dexp.in/)? Is that what you want?

```c
    if (nk_begin(ctx, WIN_TITLE, nk_rect(0, 0, winWidth, winHeight), NK_WINDOW_NO_SCROLLBAR)) {
        int i;
        /* 0.2 are a space skip on button's left and right, 0.6 - size of the button */
        static const float ratio[] = {0.2f, 0.6f, 0.2f}; 

        /* Just make vertical skip with calculated height of static row  */
        nk_layout_row_static(ctx, (winHeight- (BUTTON_HEIGHT+VSPACE_SKIP)*langCount )/2, 15, 1);
        
        nk_layout_row(ctx, NK_DYNAMIC, BUTTON_HEIGHT, 3, ratio);
        for(i=0; i<langCount; i++){
            nk_spacing(ctx, 1); /* skip 0.2 left */
            if( nk_button_image_label(ctx, image, caption, NK_TEXT_CENTERED) 
            ){
                loadLang(nkcHandle, ctx, i);
            }
            nk_spacing(ctx, 1); /* skip 0.2 right */
        }
    }
    nk_end(ctx);
```
