### ISSUE TITLE
example/canvas.c doesn't compile

### ISSUE THREAD

**Issue by bioglaze** [vurtun/nuklear#525]
I cloned master on 2017-09-23 and ran `make` in `examples` on ElementaryOS and got these errors:

    cc -std=c99 -pedantic -O2 -o bin/file_browser file_browser.c -lglfw -lGL -lm -lGLU -lGLEW
    cc -std=c99 -pedantic -O2 -o bin/extended extended.c -lglfw -lGL -lm -lGLU -lGLEW
    cc -std=c99 -pedantic -O2 -o bin/canvas canvas.c -lglfw -lGL -lm -lGLU -lGLEW
    canvas.c: In function ‘canvas_begin’:
    canvas.c:374:31: error: incompatible type for argument 2 of ‘nk_window_set_bounds’
     nk_window_set_bounds(ctx, nk_rect(x, y, width, height));
                               ^
    In file included from canvas.c:24:0:
    ../nuklear.h:18951:1: note: expected ‘const char *’ but argument is of type ‘struct nk_rect’
    nk_window_set_bounds(struct nk_context *ctx,
     ^
    canvas.c:374:5: error: too few arguments to function ‘nk_window_set_bounds’
     nk_window_set_bounds(ctx, nk_rect(x, y, width, height));
     ^
    In file included from canvas.c:24:0:
    ../nuklear.h:18951:1: note: declared here
     nk_window_set_bounds(struct nk_context *ctx,
     ^
    Makefile:38: recipe for target 'canvas' failed
    make: *** [canvas] Error 1

**Comment by vurtun** [comment]
Hey,
thanks for the issue forgot to update example after previous changes.
Should be fixed now.
