### ISSUE TITLE
Images at DirectX backend

### ISSUE THREAD

**Issue by Vinters** [vurtun/nuklear#540]
Hello,
How to add images support for DirectX9 and DirectX11?
Because there's example only for GL/GLFW
Thank you

**Comment by vurtun** [comment]
Hey @Vinters,
not sure what you mean. Nuklear and no backend does image loading or texture handling. Rather it allows you to use other libraries like `stb_image` and only takes texture handles passed down with `nk_image` into the UI an down the renderer and directly drawn to screen.
