### ISSUE TITLE
void * to int

### ISSUE THREAD

**Issue by mojmir-svoboda** [vurtun/nuklear#551]
hello,
just browsing in sources and i wonder about this:

`typedef union {void *ptr; int id;} nk_handle;`

this works well in 32bit, but in 64bit it strips the upper half off, don't it?
isn't there intptr_t or something like that for this purpose?

best regards,
mojmir

**Comment by vurtun** [comment]
Hey,
please look at the context `nk_handle` is used in. Nuklear at no point accesses the content of a handle. It is just a pass through container for fonts and texture for abstraction purposes to be used for callbacks and rendering backends. Could I have used an `intptr_t` for that as well? Yes and if I would write it now it would be. Sadly changing things retroactively is quite costly.

**Comment by dumblob** [comment]
>this works well in 32bit, but in 64bit it strips the upper half off, don't it?

I'm not sure whether I understand your question. I can though assure you, that union doesn't strip anything under any condition imaginable (at least according to any C standard - even long before C89). Quite the opposite - union might add padding (at the end of the union).

What did you mean by the question?

>isn't there intptr_t or something like that for this purpose?

`intptr_t` doesn't have any relation to `int` (the size is or at least might be different). Also, `intptr_t` is C99 and Nuklear is C89/ANSI_C.
