### ISSUE TITLE
nk_tree_push inside a loop links tabs / nodes

### ISSUE THREAD

**Issue by frguthmann** [vurtun/nuklear#556]
Hey,

It seems impossible to instantiate several tabs or nodes within a loop without having them linked together. Whenever I try to open one of them, they all open. 
I took a quick look at the code and it would seem that you use __LINE__ as a seed for your hash function. That might explain why the loop would link the tabs together.

The only solution I've found so far is to put "nk_tree_push" inside a macro and call that macro several times like this:
MY_MACRO(0);
MY_MACRO(1);
MY_MACRO(2);
It only works if you know exactly how many instances you need. If you want to instantiate a dynamically generated number of those you're screwed. 

Is there any way around that? Or am I just using the library wrong?

**Comment by vurtun** [comment]
Hey,
please have a look at functions: `nk_tree_push_id, nk_tree_push_hashed`. The first one works just like `nk_tree_push` but you can pass your loop counter to make sure you have unique identifiers:

```c
for (int i = 0; i < cnt; ++i) {
    if (nk_tree_push_id(ctx, NK_TREE_NODE, ''Name", &state, i)) {
        /* [...] */
    }
}
```
If that is not enough that have a look at `nk_tree_push_hased`. It takes a hash string and a seed value to generate a unique ID.

**Comment by frguthmann** [comment]
Oh, I see. That works well thank you.
