### ISSUE TITLE
beginner install and first usage.

### ISSUE THREAD

**Issue by gideondsouza** [vurtun/nuklear#557]

**Comment by gideondsouza** [comment]
I know this is a noob question but I'm just getting my feet wet with C, I'd like to know how to just install or compile the source to just build and run the example.If someone could give some _pointers_ I could send a PR to update the readme and/or the docs

**Comment by whkelvin** [comment]
I wrote a quick tutorial. Feel free to visit if you are interested: https://github.com/whkelvin/Nuklear_gui_with_glfw-glad-opengl
