### ISSUE TITLE
NK_WINDOW_MOVABLE flag seems to disable resizing nk_window 

### ISSUE THREAD

**Issue by whkelvin** [vurtun/nuklear#561]
if (nk_begin(context, "", nk_rect(0, 0, width*1/3, nk_window_height),
	NK_WINDOW_BORDER|
        NK_WINDOW_MOVABLE|
        NK_WINDOW_NO_SCROLLBAR|
        NK_WINDOW_BACKGROUND))
	{
		//build gui here
		buildGui(context);
	}
	nk_end(context);

The parameter "width" inside nk_rect is a variable that could be changed at run time. However the width of the nk_window only changes when NK_WINDOW_MOVABLE  is not included in the flags. With the flag included, the width of the nk_window  seems to be fixed to the initial value.

**Comment by vurtun** [comment]
Hey @whkelvin
could you specify exactly what you want to do and if check if instead of directly specifying window position with `nk_begin` you can use `nk_window_set_bounds` for what you want to do.

**Comment by whkelvin** [comment]
Great, thanks!!
