### ISSUE TITLE
License / Copyright issue

### ISSUE THREAD

**Issue by hashar** [vurtun/nuklear#562]
I am trying to package for Debian a game ( https://github.com/cxong/cdogs-sdl/ ) which relies on Nuklear for the GUI. Debian requires all materials to be under a Public Domain or an approved free license.

Looking at `nuklear.h` it has a rather clear license, potentially acceptable by Debian (I haven't checked)
```
LICENSE:
    This software is dual-licensed to the public domain and under the following
    license: you are granted a perpetual, irrevocable license to copy, modify,
    publish and distribute this file as you see fit.
```

But further below:
```
Embeds ProggyClean.ttf font by Tristan Grimmer (MIT license).
 * ProggyClean.ttf
 * Copyright (c) 2004, 2005 Tristan Grimmer
 * MIT license (see License.txt in http://www.upperbounds.net/download/ProggyClean.ttf.zip)
 * Download and more information at http://upperbounds.net
```

I am not sure how we can ship the software as Public Domain license if it embeds a material which is under MIT License. That seems problematic.

Would it be possible to have the font extracted from nuklear.h so one can easily distribute the software under Public License?

There are also a few other suspects:
```
demo/x11_rawfb/main.c: * Copyright (c) 2016-2017 Patrick Rudolph <siro@das-labor.org>
demo/x11_rawfb/nuklear_rawfb.h: * Copyright (c) 2016-2017 Patrick Rudolph <siro@das-labor.org>
demo/x11_rawfb/nuklear_xlib.h: * Copyright (c) 2016-2017 Patrick Rudolph <siro@das-labor.org>
Binary file extra_font/Karla-Regular.ttf matches
Binary file extra_font/Raleway-Bold.ttf matches
Binary file extra_font/kenvector_future.ttf matches
Binary file extra_font/kenvector_future_thin.ttf matches
```

You might want to list that in your Readme.md :)

**Comment by vurtun** [comment]
Hey @hashar,
> I am not sure how we can ship the software as Public Domain license if it embeds a material which is under MIT License. That seems problematic.
Would it be possible to have the font extracted from nuklear.h so one can easily distribute the software under Public License?

I don't want to be an asshole but you already quoted the actual library license:

```c
LICENSE:
    This software is dual-licensed to the public domain and under the following
    license: you are granted a perpetual, irrevocable license to copy, modify,
    publish and distribute this file as you see fit.
```

Specifically the last part should make it obvious that you can change everything you want in nuklear. If you don't want the MIT licensed font just remove all code sections with `NK_INCLUDE_DEFAULT_FONT` defined and use a public domain font or if you only publish a binary just don't define and compile with default font.

**Comment by hashar** [comment]
I did notice the public domain license, my point is that it also include a MIT licensed material which is a bit misleading.

`NK_INCLUDE_DEFAULT_FONT` will make it easy to strip the font. Thanks for the pointer!
