### ISSUE TITLE
Tooltip rendering with holes

### ISSUE THREAD

**Issue by nkindt** [vurtun/nuklear#569]
Tooltips seem to renderer with holes sometimes when width/height of the calculated text has fractions apparently. The tooltip code already contains redundant casts to float so it seems like a cast to int should be there instead to achieve truncation which fixes the issue (or use floor as in the suggested code below).

Before/after image:
![tooltip](https://user-images.githubusercontent.com/10233151/33529930-71f8d82c-d888-11e7-8ede-38bb47f07a62.png)

Code with truncation:
```
/* execute tooltip and fill with text */
    if (nk_tooltip_begin(ctx, (float)floor(text_width))) { /* Make sure we have whole integers */
        nk_layout_row_dynamic(ctx, (float)floor(text_height), 1);
        nk_text(ctx, text, text_len, NK_TEXT_LEFT);
        nk_tooltip_end(ctx);
    }
```

Also is it possible to add a tooltip printf style function? I've been using this code for some time now:
```
NK_API void nk_tooltipf(struct nk_context *ctx, const char *text, ...)
{
    char buf[256];
    va_list args;
    va_start(args, text);
    nk_strfmt(buf, NK_LEN(buf), text, args);
    va_end(args);
    nk_tooltip(ctx, buf);
}
```

Code is much neater this way as opposed to snprintf calls beforehand.

Thanks!

**Comment by vurtun** [comment]
Hey @nkindt,
thanks for the issue and the formatted tooltip idea. I hopefully fixed the gap and added the new formatted string tooltip version if define `NK_INCLUDE_STANDARD_VARARGS` is set.
