### ISSUE TITLE
repeatedly *2: processing cursor data

### ISSUE THREAD

**Issue by hcg2008** [vurtun/nuklear#580]
in func nk_font_atlas_bake():
atlas->custom.w = (NK_CURSOR_DATA_W*2)+1;

and in func nk_font_bake_pack()
custom_space.w = (nk_rp_coord)((custom->w * 2) + 1);

it should be repeated.

**Comment by vurtun** [comment]
Hey @hcg2008,
thanks for your issue and noticing the double space reservation. Should be fixed now.
