### ISSUE TITLE
nk_edit_buffer ignores input when first focused

### ISSUE THREAD

**Issue by borodust** [vurtun/nuklear#582]
When first focused, `nk_edit_buffer` ignores any input. But when focus goes to other widget and returns back, `nk_edit_buffer` works as expected.

Tuned example to reproduce the behavior: https://github.com/borodust/nuklear/commit/31471ea40694b351d2a3a9f290b8b63bf82884d5

Not very useful `.gif` that captures the behavior (first edit field is `nk_edit_buffer`, second - `nk_edit_string_zero_terminated`):
![nk_edit_buffer_refocus](https://i.imgur.com/ivC8ZWV.gif)

**Comment by vurtun** [comment]
Hey @borodust,
thanks for the perfect issue with both minimal demo to reproduce the bug and gif. Hopefully the problem is now fixed.
