### ISSUE TITLE
Password input?

### ISSUE THREAD

**Issue by namazso** [vurtun/nuklear#587]
Could we get a way to make password inputs (inputs where the text inputted is hidden)?
I looked into how text edits work, and found it not easily possible without a lot of changes, so I was wondering if you could add something similar.

**Comment by vurtun** [comment]
Hey @namazso,
Inside `overview.c` is a [hack](https://github.com/vurtun/nuklear/blob/a9e5e7299c19b8a8831a07173211fa8752d0cc8c/demo/overview.c#L549) to achieve password input:

```c
static char pwd[64];
static int pwd_len = 0;
nk_label(ctx, "Password:",  NK_TEXT_LEFT);
{
    int i = 0;
    char buf[64];
    int old_len = pwd_len;
    for (i = 0; i < pwd_len; ++i) buf[i] = '*';
    nk_edit_string(ctx, NK_EDIT_FIELD, buf, &pwd_len, 64, nk_filter_default);
    if (old_len < pwd_len])
         memcpy(&pwd_buf[old_len], &buf[old_len], (nk_size)(pwd_len - old_len));
}
```

**Comment by namazso** [comment]
As you said this is a hack, and not only not nice to use, also has a lot of limitations, most importantly that you cannot delete characters. So if it is possible I'd still like to ask for a "proper" password input

**Comment by namazso** [comment]
Meanwhile I made a better workaround (this is C++ code but obviously portable to C), just gonna leave it here for future reference:
```cpp

class gui_helper
{
public:
	static void password_push(nk_context* ctx)
	{
		auto& cmdbuf = ctx->current->buffer;
		s_password_begin = cmdbuf.last;
	}

	static void password_pop(nk_context* ctx)
	{
		auto& cmdbuf = ctx->current->buffer;
		const auto last = cmdbuf.last;
		const auto buffer = static_cast<nk_byte*>(ctx->memory.memory.ptr);
		for(auto i = s_password_begin;
			i != last;
			i = reinterpret_cast<nk_command*>(buffer + i)->next)
		{
			const auto it = reinterpret_cast<nk_command*>(buffer + i);
			if(it->type == NK_COMMAND_TEXT)
			{
				const auto text_cmd = reinterpret_cast<nk_command_text*>(it);
				for(auto j = 0; j < text_cmd->length; ++j)
					text_cmd->string[j] = '*';
			}
		}
	}
private:
	static nk_size s_password_begin;
};
nk_size gui_helper::s_password_begin = 0;```
using it like:
```cpp
		static char pass[1234];
		gui_helper::password_push(ctx);
		nk_edit_string_zero_terminated(ctx, NK_EDIT_SIMPLE, pass, 1234, nullptr);
		gui_helper::password_pop(ctx);```

**Comment by vurtun** [comment]
> importantly that you cannot delete characters.

Yes it can.

**Comment by namazso** [comment]
Oh, i assume i copypasted it wrong for testing. Still, pretty sure you cannot delete from anywhere but the end though. Anyways, i solved it at the end with another workaround so its not that important now.
