### ISSUE TITLE
multiple includes of nuklear.h causes hundreds of errors

### ISSUE THREAD

**Issue by KingLycosa** [vurtun/nuklear#593]
If i include nuklear.h in more than one file I get 100s of errors spawning from nuklear.h... As soon as I remove the second include it resolves all the errors. Is there anyway to do this? I am trying to add nuklear type variables to a header file and it doesn't want to cooperate.

My project is CPP so it might have something to do with that?

**Comment by vurtun** [comment]
Specifically in what files (.hpp/.cpp) did you include `nuklear.h`? For headers do not define flag `NK_IMPLEMENTATION` or it will try to directly insert the implementation portion into your header and the second including inside a source file will cause errors.
