### ISSUE TITLE
Basic Example Using NanoVG

### ISSUE THREAD

**Issue by zester** [vurtun/nuklear#601]
It would be really cool if nuklear had a really basic example using NanoVG https://github.com/memononen/nanovg

**Comment by vurtun** [comment]
Hey @zester,
I am familiar with nanovg and yes I agree it would be cool. At one point I even had a GLFW [nanovg backend]( https://github.com/vurtun/nuklear/blob/847645a29cbd2e5010f808eab53414e4ee6fa797/demo/nanovg/nanovg.c). You are welcome to provide one if you want.
