### ISSUE TITLE
listbox widget?

### ISSUE THREAD

**Issue by mumin16** [vurtun/nuklear#602]
I need listbox. or always open combobox ... but how?

**Comment by vurtun** [comment]
Hey @mumin16 ,
please take a look at `demo/overview.c`. More precisely: https://github.com/vurtun/nuklear/blob/master/demo/overview.c#L880. There is no list widget per se. Instead you can use existing functionality. 

For example if you want a multi-selectable list you can do:

```c
nk_layout_row_static(ctx,  200, 200, 2);
if (nk_group_begin(ctx, "List", 0)) {
    static int selected[16];
    nk_layout_row_static(ctx, 18, 100, 1);
    for (int i = 0; i < 16; ++i)
        nk_selectable_label(ctx, (selected[i]) ? "Selected": "Unselected", NK_TEXT_CENTERED, &selected[i]);
} nk_group_end(ctx);
```
If you just want a single selectable list you can simplify:

```c
nk_layout_row_static(ctx,  200, 200, 2);
if (nk_group_begin(ctx, "List", 0)) {
    static int selected = -1;
    nk_layout_row_static(ctx, 18, 100, 1);
    for (int i = 0; i < 16; ++i) {
        if (nk_select_label(ctx,  (selected == i) ? "Selected": "Unselected", NK_TEXT_CENTERED);
            selected = (selected == i) ? -1: i;
    }
} nk_group_end(ctx);
```

For more advanced purposes with list made out massive numbers of elements there is `list_view` as well but that shouldn't be needed under normal use cases.
