### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [vurtun/nuklear#605]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by dumblob** [comment]
There are more such managers. Conan is unfortunately one of those bigger ones (yay, Python dependent :open_mouth:).

Anyway, we already [have support](https://github.com/vurtun/nuklear/pull/168 ) for [clib](https://github.com/clibs/clib ) (clib is btw much more KISS and has bigger user-base than Conan judging based on the number of stars on GitHub).

Is there any serious reason to explicitly support Conan?

Btw I find Conan more difficult to support than e.g. *clib*. Also Conan seems to be sponsored or even backed by (dependent upon) an organization calling itself *JFrog Bintray*, which seems to have commercial business around building binary packages from Conan description files.

**Comment by ZaMaZaN4iK** [comment]
Is Python problem for you? :-)

What about Clib on Windows. Sorry, but i didn't find info about this :-(
Also i think judging about technologies based on stars on GitHub is a little bit strange.

>which seems to have commercial business around building binary packages from Conan description files.
No, you are wrong. JFrog just gives Conan place for storing prebuilt binaries for all packages.

BTW, Conan recipe for Nuklear. https://github.com/bincrafters/conan-nuklear/tree/testing/1.0.0

P.S. Do you plan release your library?

**Comment by ras0219-msft** [comment]
On Windows, Nuklear is already available via [Vcpkg](https://github.com/Microsoft/vcpkg/tree/7f104409b6998abeb6593f9f001e2285f57eac4e/ports/nuclear):
```
vcpkg install nuclear:x64-windows
```

(and has no python dependencies)

**Comment by vurtun** [comment]
I have not interest cluttering the main entry point of nuklear with all kind of package managers. I mean seriously. Two header files are required to get nuklear up and running on a given platform with given platform library. At max we are talking three if the `main.c` is copied as well. I don't think that warrants so many package manager hooks.

> Do you plan release your library?

What specifically do you mean with release?

**Comment by dumblob** [comment]
@ZaMaZaN4iK 

>Is Python problem for you? :-)

No. But for Nuklear, I guess, yes.

>What about Clib on Windows. Sorry, but i didn't find info about this :-(

There is nothing specific - just download the exe files (it's always part of the [release](https://github.com/clibs/clib/releases )) and use it straight away. Or did you expect something more complicated :wink:?

>Also i think judging about technologies based on stars on GitHub is a little bit strange.

I'm not at all judging about the technology, but about the user base based on the popularity of the repo.

>>which seems to have commercial business around building binary packages from Conan description files.
>
>No, you are wrong. JFrog just gives Conan place for storing prebuilt binaries for all packages.

Good to know we're on the safe side.

>BTW, Conan recipe for Nuklear. https://github.com/bincrafters/conan-nuklear/tree/testing/1.0.0

Thanks (I hope you'll continuously make sure it's updated and compatible with the latest Nuklear as well as with the latest Conan).
