### ISSUE TITLE
Compiling in 64bit raspberry PI

### ISSUE THREAD

**Issue by ktb92677** [vurtun/nuklear#606]
Hey! I discovered an issue compiling this on a raspberry PI 3 with a 64 bit OS. I had to change the following lines:

typedef NK_SIZE_TYPE nk_size;
typedef NK_POINTER_TYPE nk_ptr;

to say the following:

typedef unsigned long nk_size;
typedef unsigned long nk_ptr;

I believe the compile time statements for finding NK_SIZE_TYPE and NK_POINTER_TYPE on a 64 bit PI isn't working right. thanks all!

**Comment by vurtun** [comment]
Hey @ktb92677 ,
please look at the  `NK_INCUDE_FIXED_TYPES` compile time flag. It specifically defines correct types size for all platforms with header file: `stdint.h`. 

If the define is not set nuklear tries to define the correct types size and hopefully if it is not correct a static compile time error will be generated. So if you don't set it you can directly define each type outside as compile time flags.
