### ISSUE TITLE
Texture matrix

### ISSUE THREAD

**Issue by nkindt** [vurtun/nuklear#608]
I was recently missing a feature to apply arbitrary texture transforms while doing nk_image() calls. Texture transforms would add alot of useful image techniques from scaling, rotation, projection, etc. While i wasn't able to find anything related in nuklear i implemented it on my own. Not sure if it's the most optimal way but it works for me. I would do a pull request but my nuklear headers are bit older due to a problem introduced recently. 

1.
struct nk_image is extended with use_transform (to avoid identity matrix initialization on each nk_image_ call) and the actual transformation matrix:
`struct nk_image {nk_handle handle;unsigned short w,h;unsigned short region[4]; int use_transform; float transform[4][4];};`

2.
struct nk_draw_command is extended with use_texture_matrix (to avoid unnecessary render-API calls) and the actual 4x4 texture matrix:
```c
struct nk_draw_command {
    unsigned int elem_count;
    /* number of elements in the current draw batch */
    struct nk_rect clip_rect;
    /* current screen clipping rectangle */
    nk_handle texture;
    /* current texture to set */
    int use_texture_matrix;
    /* NEW: if texture matrix should be applied */
    float texture_matrix[16];
    /* NEW: full 4x4 texture transform */
#ifdef NK_INCLUDE_COMMAND_USERDATA
    nk_handle userdata;
#endif
};
```
3.
nk_draw_list_push_image receives an extra float pointer of the transformation matrix. All functions not using the texture matrix just pass NULL.
```c
NK_INTERN void
nk_draw_list_push_image(struct nk_draw_list *list, nk_handle texture, float* transform_4x4)
{
    NK_ASSERT(list);
    if (!list) return;
    if (!list->cmd_count) {
        nk_draw_list_push_command(list, nk_null_rect, texture);
    } else {
        struct nk_draw_command *prev = nk_draw_list_command_last(list);
        if (prev->elem_count == 0)
            prev->texture = texture;
        else if (prev->texture.id != texture.id)
            nk_draw_list_push_command(list, prev->clip_rect, texture);
    }
    
    /* NEW: Pass texture matrix to command buffer if present */
    struct nk_draw_command *prev = nk_draw_list_command_last(list);
    prev->use_texture_matrix = transform_4x4 != NULL;
    if(prev->use_texture_matrix)
        NK_MEMCPY(prev->texture_matrix, transform_4x4, sizeof(float) * 16);
}

/* If texture matrix is used: */
nk_draw_list_push_image(list, texture.handle, (float*)texture.transform);
/* otherwise: */
nk_draw_list_push_image(list, font->texture, NULL);
```
4.
All backends need to provide API-specific code to set texture matrices. For the OpenGL backend it could look like this:
```c
        /* iterate over and execute each draw command */
        glMatrixMode(GL_TEXTURE); /* NEW: Switch to texture matrix mode */ 
        offset = (const nk_draw_index*)nk_buffer_memory_const(&ebuf);
        nk_draw_foreach(cmd, &sdl.ctx, &dev->cmds)
        {
            if (!cmd->elem_count) continue;
            glBindTexture(GL_TEXTURE_2D, (GLuint)cmd->texture.id);
            if(cmd->use_texture_matrix) /* NEW: */
            {
                glPushMatrix(); /* NEW: */
                glLoadMatrixf(cmd->texture_matrix); /* NEW: */
            }
            
/* ... */

           glDrawElements(GL_TRIANGLES, (GLsizei)cmd->elem_count, GL_UNSIGNED_SHORT, offset);
            if(cmd->use_texture_matrix) /* NEW: */
                glPopMatrix(); /* NEW: Restore texture matrix for other drawcalls */
            offset += cmd->elem_count;
        }
        glMatrixMode(GL_MODELVIEW); /* NEW: Optionally reset matrix mode */

```
In order to use texture transformations one would set use_transform in nk_image to true and provide the transform as a 4x4 matrix. I.e.:
```c

debugImage = nk_image_id((int)debugTexture.handle);
debugImage.use_transform = 1;
for(int i=0; i<4; ++i)
    for(int j=0; j<4; ++j)
        debugImage.transform[i][j] = (i == j) ? 1.0f : 0.0f;
```

Thanks!

**Comment by nkindt** [comment]
Btw, there are some redundant zero initializations in nk_image calls since the whole struct is already wiped out beforehand. I.e.:

```
NK_API struct nk_image
nk_image_handle(nk_handle handle)
{
    struct nk_image s;
    nk_zero(&s, sizeof(s));
    s.handle = handle;
    s.w = 0; s.h = 0; /* REDUNDANT */
    s.region[0] = 0;  /* REDUNDANT */
    s.region[1] = 0;  /* REDUNDANT */
    s.region[2] = 0;  /* REDUNDANT */
    s.region[3] = 0;  /* REDUNDANT */
    return s;
} 
```

**Comment by vurtun** [comment]
Hey @nkindt ,
while I like the idea I think it is not a good idea for the main branch. Texture matrices are specific to graphics libraries like OpenGL, DirectX, Vulkan, Metal.  I don't want to add something that influences a lot of different systems that is only affecting specific backends. While there is the possibility of adding `#ifdef`s I don't think texture matrices are a good idea to further complicate the build process with.
