### ISSUE TITLE
Black Outline around UI Elements

### ISSUE THREAD

**Issue by theProgrammerDavid** [vurtun/nuklear#610]
![test](https://user-images.githubusercontent.com/35698009/35230821-25ed2544-ffbd-11e7-92dd-48a39017b217.png)
![test](https://user-images.githubusercontent.com/35698009/35231222-37ebd366-ffbe-11e7-9cd7-7ac7b20069b9.png)

I apologize in advance for any future late replies, but I'm a student and my final exams are a month away. I'm kinda new to GUIs and rendering, but the following are from the demos included. The first one is from the folder gdi and the second one is from gdiplus. Are the black...outlines around the UI elements normal ?

**Comment by vurtun** [comment]
Hey @theProgrammerDavid ,
this looks like a bug in the GDI backend. @mmozeiko do you have some time to take a look? Seems like I destroyed something inside the GDI backend.

**Comment by mmozeiko** [comment]
Yeah, I see same thing. git bisected this change to 4020b1bab24f81160603da98fb67d06be7cce9da commit. I guess something is wrong how gdi processes stroked rectangles. Will look into this tomorrow.

**Comment by mmozeiko** [comment]
Sorry for delay, now it should be fixed.

**Comment by vurtun** [comment]
> Sorry for delay, now it should be fixed.
Thanks for your work, sorry for having to rely on you again.
