### ISSUE TITLE
How is the function nk_window_get_bounds implemented?

### ISSUE THREAD

**Issue by vieno-jyoti** [vurtun/nuklear#612]
Hi there.

I am browsing the source file [nuklear.h](https://github.com/vurtun/nuklear/blob/master/nuklear.h), and I can't locate the implementation details of  the function `nk_window_get_bounds`. Trying to find all occurrences of the string "nk_window_get_bounds" - produced only 5 matches, and none of them is the actual implementation.

Maybe I am missing something? Maybe this function is generated dynamically at run-time?

PS: Here are all the places where the string occurs:

[line 1368](https://github.com/vurtun/nuklear/blob/master/nuklear.h#L1368)
```c
/// nk_window_get_bounds                | Returns a rectangle with screen position and size of the currently processed window.
```

and

[line 1503](https://github.com/vurtun/nuklear/blob/master/nuklear.h#L1503)
```c
/*/// #### nk_window_get_bounds
///
/// Returns a rectangle with screen position and size of the currently processed window
/// !!! WARNING
///     Only call this function between calls `nk_begin_xxx` and `nk_end`
/// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~c
/// struct nk_rect nk_window_get_bounds(const struct nk_context *ctx);
/// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
///
/// Parameter   | Description
/// ------------|-----------------------------------------------------------
/// __ctx__     | Must point to an previously initialized `nk_context` struct
///
/// Returns a `nk_rect` struct with window upper left window position and size
*/
NK_API struct nk_rect nk_window_get_bounds(const struct nk_context *ctx);
/*/// #### nk_window_get_bounds
```

**Comment by vurtun** [comment]
Hey @vieno-jyoti ,
not 100% sure what you mean but could it be that you are looking at `nuklear.h` on github? The reason why I am asking is that github is not able to fully show `nuklear.h` with syntax highlighting. To actually see the full file you have to clicked the `raw` button on the top right while looking at the file.

The implementation for `nk_window_get_bounds` can be found at line `19880`.
