### ISSUE TITLE
Question: Is it possible to set background color/transparency of window?

### ISSUE THREAD

**Issue by nickclark2016** [vurtun/nuklear#616]
I am trying to render a transparent window over a scene in a GLFW window.  Is it possible to change the transparency of the window, and if so how?

Thanks in advance.

**Comment by vurtun** [comment]
Hey @nickclark2016,
depends if your backend supports alpha blending. All opengl and directx backends do others like X11, win32 do not.

I guess you only want one window to be transparent not all windows.
I will write up an example out of my head, so see it more like a pointer in the right direction:

```c
nk_begin(...(
    /* some other window */
nk_end(...);

/* transparent window */
struct nk_style *s = &ctx->style;
nk_style_push_color(ctx, &s->window.background, nk_rgba(0,0,0,0));
nk_style_push_style_item(ctx, &s->window.fixed_background, nk_style_item_color(nk_rgba(0,0,0,0));
nk_begin(...);
    /* transparent window content */
nk_end(...);
nk_style_pop_color(ctx);
nk_style_pop_style_item(ctx);

nk_begin(...(
    /* some other window not transparent*/
nk_end(...);
```
If you also want transparent border you also have to push/pop `s->window.border_color`.

**Comment by tuket** [comment]
Hi, is the order of push-pop right?
Shouldn't it be

```cpp
nk_style_push_color(ctx, &s->window.background, nk_rgba(0,0,0,0));
nk_style_push_style_item(ctx, &s->window.fixed_background, nk_style_item_color(nk_rgba(0,0,0,0));
nk_begin(...);
    /* transparent window content */
nk_end(...);
nk_style_pop_style_item(ctx);
nk_style_pop_color(ctx);
```

**Comment by tuket** [comment]
Which is the difference between `backbround` and `fixed_background`?

**Comment by vurtun** [comment]
@tuket  the order does not matter in this particular code snippet. These are two different stacks. One for style items and one for colors. As for the difference. The fixed background one is a hack for my butchered skinning approach. But in general I would set both to transparent to achieve the desired effect.
