### ISSUE TITLE
[feature request]Can I develop nuklear UI by the XML format？

### ISSUE THREAD

**Issue by sleepdexiang** [vurtun/nuklear#624]
hi, I have two questions about nuklear,  
1.Is the API-code the only develop way for UI,  can I develop UI use the XML format?
2.could the widget height support the ratio? so the same UI can support more platform
thanks for you help

**Comment by dumblob** [comment]
To the point (2), please read the threads https://github.com/vurtun/nuklear/issues/123 and https://github.com/vurtun/nuklear/issues/283 through.
