### ISSUE TITLE
Mouse cursor disappears in sdl_opengl2 (mac 10.13.4 Beta (17E150g))

### ISSUE THREAD

**Issue by tommythorn** [vurtun/nuklear#631]
This is an awesome library; makes me want to write GUIs!

I saw it on HN, cloned, and make'd the sdl_opengl2 with zero changes.

I noticed (and reproduced many times) that repeatedly clicking on the text "Compression:" while
subtle moving the mouse cursor will eventually make the mouse cursor disappear and no amount of clicking around will bring it back.  I do realize that this is related to the feature of drag-changing the control, but it still looks like a bug.

**Comment by vurtun** [comment]
Hey @tommythorn ,
thanks for the issue. Behavior should be fixed now in commit: 7e462e7d7cdf61804a3b92308647f90b97d7e383. Cursor hiding while a property is dragged is an optional feature that does not work correctly on some backends so I removed it in almost all of them, but forgot to remove it in the `sdl_opengl2` demo.
