### ISSUE TITLE
GL_RGB Images in canvas invisible

### ISSUE THREAD

**Issue by EvilPudding** [vurtun/nuklear#632]
When using `nk_draw_image` to draw a `nk_image_id` of a `GL_RGB` texture, it comes out invisible because of the enabled `GL_BLEND`, could there be an extra argument so I can send user information to the drawing function to disable blending?

This sounds really easy to fix, but I didn't want to have my project change nuklear code unnecessarily.

**Comment by kphillisjr** [comment]
The best solution is to look into the "NK_INCLUDE_COMMAND_USERDATA"  option. This adds a variable called "userdata" to the following structures...

- nk_command
- nk_draw_command
- nk_draw_list

This variable should be able to minimize the changes to the render loop to allow for proper handling of the GL_RGB Texture type. Also, If your using OpenGL 3.x, Another shader needs to be added to handle the texture that lacks an alpha channel.

**Comment by EvilPudding** [comment]
I did what you said, and changed the render loop to:

```       
 nk_draw_foreach(cmd, &sdl.ctx, &dev->cmds) {
	if (!cmd->elem_count) continue;
	if(cmd->userdata.ptr == (void*)1) glDisable(GL_BLEND);
	glBindTexture(GL_TEXTURE_2D, (GLuint)cmd->texture.id);
	glScissor((GLint)(cmd->clip_rect.x * scale.x),
			(GLint)((height - (GLint)(cmd->clip_rect.y + cmd->clip_rect.h)) * scale.y),
			(GLint)(cmd->clip_rect.w * scale.x),
			(GLint)(cmd->clip_rect.h * scale.y));
	glDrawElements(GL_TRIANGLES, (GLsizei)cmd->elem_count, GL_UNSIGNED_SHORT, offset);
	offset += cmd->elem_count;
	if(cmd->userdata.ptr == (void*)1) glEnable(GL_BLEND);
}
```

Real hackish for now, but it's working without changing the shader.
