### ISSUE TITLE
Widgets are not drawn

### ISSUE THREAD

**Issue by borodust** [vurtun/nuklear#635]
I'm trying to port native Nuklear OpenGL renderer (`NK_INCLUDE_VERTEX_BUFFER_OUTPUT`), but can't figure out why widgets are not drawn inside a window (amongst other issues). I didn't translate Nuklear demo line-to-line, I humbly admit, but tried to stay as close as possible while being target language-friendly. 

What could be wrong? Where should I look first?

Symptoms:
* Rendering actually works (or somewhat works) and a window is shown (see the demo below), input is correctly read and i can move and resize a window around
* Command list (non-opengl one) is actually contains various drawing commands, and when I comment out some widgets it changes its state (less commands getting requested)
* But, unfortunately, nothing is getting drawn inside this window

Demo:
![Demo](https://media.giphy.com/media/YlJxfPtMVOk7BLUenV/giphy.gif)

Code inside begin/end looks like this (yes, lisp):
```lisp
        (%nk:layout-row-static nk-context 30f0 80 1)
        (unless (= (%nk:button-label nk-context "button") 0)
          (format t "~&button pressed"))
        (%nk:layout-row-dynamic nk-context 30f0 2)
        (unless (= (%nk:option-label nk-context "easy" (if (eq level :easy) 1 0)) 0)
          (setf level :easy))
        (unless (= (%nk:option-label nk-context "hard" (if (eq level :hard) 1 0)) 0)
          (setf level :hard)))
```
Which is trying to mimic this demo code:
```c
            nk_layout_row_static(ctx, 30, 80, 1);
            if (nk_button_label(ctx, "button"))
                fprintf(stdout, "button pressed\n");

            nk_layout_row_dynamic(ctx, 30, 2);
            if (nk_option_label(ctx, "easy", op == EASY)) op = EASY;
            if (nk_option_label(ctx, "hard", op == HARD)) op = HARD;
```

**Comment by vurtun** [comment]
Hey @borodust,
I am not an expert in lisp and I did not write the lisp port. Could you validate for me that these widget functions are actually called. Just by seeing the symptoms my first guess would be that since everything else works it could be that `nk_begin` falsely returns `0`. So do you have a condition around `nk_begin` and does it return `1`?

**Comment by borodust** [comment]
Yes, I do have a condition around the widget code and `nk_begin` returns 1. 

As an exepriment, I'll try to plug my old nanovg renderer for nuklear and check what is getting drawn in this case, but I'm quite sure widget functions are getting called, because command list of drawing primitives changes if i comment out some of the functions.

**Comment by borodust** [comment]
So, yes, I've plugged in my nanovg renderer and it works just fine.

Here in the demo I switch between native nuklear renderer and nanovg renderer at runtime:
![different_renderers](https://media.giphy.com/media/Sc59nRs2L9LFmBLiaA/giphy.gif)

That means:
* All logic code does work correctly
* The bug is totally somewhere in my nuklear renderer port, but i'm totatlly lost trying to figure out where the bug could possibly live.

If there is no easy way to figure that out, then, I guess, I would just copy and paste nuklear demo code into the lib and export/wrap a couple of routines to use the renderer from a shared library.

**Comment by borodust** [comment]
I decided to just drop my lisp port of a renderer and integrated renderer from the demo into the [library itself](https://github.com/borodust/bodge-nuklear/blob/master/lib/main.c#L174-L270) (what I mentioned in the last comment). 

Now it all works fine and Common Lisp has yet another bindings for Nuklear :)
Thanks!
