### ISSUE TITLE
Reproducible case where program with nuklear is getting stuck.

### ISSUE THREAD

**Issue by Predelnik** [vurtun/nuklear#637]
Demo with changes (just copy part after `GUI`)
https://gist.github.com/Predelnik/0d1fd0fb2b890fef89501d5a40053cba
Pressing `Show/hide Demo3` button gets program stuck for me iterating over list of commands which has loop in it.
In actual program where I believe I experienced the same issue it gets stuck during `nk_convert` which also continues to reallocate buffer to infinity.

**Comment by vurtun** [comment]
Hey @Predelnik,
thanks for the issue and test case. Will take a look as soon as possible.

**Comment by vurtun** [comment]
Hmm. I tried it using `sdl_opengl3` with OpenGL and I clicked on the `Show/hide` Button and for me everything seems to work fine for me. Am I doing something wrong?

**Comment by Predelnik** [comment]
I've checked it on my virtual machine with kubuntu 17.10 and sdl_opengl3 it reproduced as well.
Just to simplify - here's full modified sdl_opengl3 demo which you can copy & replace entirely:
https://gist.github.com/Predelnik/5b4edb249ca37cfb140ce00625417338

**Comment by ventosus** [comment]
> In actual program where I believe I experienced the same issue it gets stuck during nk_convert which also continues to reallocate buffer to infinity.

I've seen this issue, too in my UIs. It does not always happen, though.

The problem was: It indefinitely hung in nk_convert:nk_foreach because of nk__next not properly iterating with cmd->next==0

**Comment by vurtun** [comment]
Hey @Predelnik,
I tried out your test again and was not able to reproduce the problem. However I also just fixed a similar issue in #647. Could you test again if your problem still persists?

**Comment by Predelnik** [comment]
@vurtun
Thanks, seems to be really fixed with this commit! (I checked that it's reproducible before/ not reproducible after) Great!
