### ISSUE TITLE
discussion: d3d11 demo : how and where is set  cmd->texture.ptr

### ISSUE THREAD

**Issue by vtorri** [vurtun/nuklear#643]
i use your code to port to d3d11 a linux 2D engine. in nuklear_d3d11.h, line 151 one can see: 
        `ID3D11ShaderResourceView *texture_view = (ID3D11ShaderResourceView *)cmd->texture.ptr;`

where is `cmd->texture.ptr ` set ?

thank you
Vincent Torri

**Comment by vurtun** [comment]
Hey @vtorri,
`cmd->texture->ptr` is passed to nuklear from user side by passing in a `nk_image` struct for widget function `nk_image(...)`. The other source of `cmd->texture->ptr` is the font atlas texture generated by `nk_font_atlas` in the backing process.
