### ISSUE TITLE
nk_image_color has been removed?

### ISSUE THREAD

**Issue by executionunit** [vurtun/nuklear#645]
Not sure if this was intentional or not but it's been removed and I find it very useful. I can't see any property API to replace the color, nk_image just renders the image with nk_white color.

I can't track down which revision it's been removed in but it's since 01/18.

**Comment by vurtun** [comment]
Hey @executionunit,
I don't think there is any reason I can think of why it was removed. So I added it back in commit: 20cd35c0fb379df3b8668e6319e87ada5081c99d.
