### ISSUE TITLE
compiler optimizations break layouting

### ISSUE THREAD

**Issue by malytomas** [vurtun/nuklear#648]
Hi, I think this is going to be quite difficult, but I would greatly appreciate if you could have a look at it.

![linux-correct](https://user-images.githubusercontent.com/18198295/37779585-06026a06-2ded-11e8-876a-0c99d6ed2a52.png)
This image shows correct behavior.

![mac-wrong](https://user-images.githubusercontent.com/18198295/37779586-0621290a-2ded-11e8-8bf7-709d569cf7f5.png)
In this image, some of the text is moved to beginning of the line.

The issue only appears when compiling with optimizations (CMAKE_BUILD_TYPE=RELEASE).
It never happened in debug build.

The difficult thing is, I tried to write a smaller program, but I failed to reproduce the issue in it.
The smaller program is here: https://github.com/malytomas/nuklear-issue
The whole program: https://github.com/Melown/vts-browser-cpp/tree/f9b19fe48044f4cb310fe499368c7b230afbdc0f

Further notes:
 - the issue appears with g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
 - also with Apple LLVM version 9.0.0 (clang-900.0.39.2) Target: x86_64-apple-darwin17.3.0
 - however, different labels may be affected on different compilers
 - the issue first appeared when I started using nk_tree_push
 - I tried it with some (much) older commits of nuklear, and the issue was the same, so it is nothing recent
 - valgrind shows no issues

I will try some more debugging, but the optimizations make it difficult.
Anyway, thanks for any ideas.

**Comment by vurtun** [comment]
Hey @malytomas,
indeed this problem sounds a little bit tricky but: 

> the issue first appeared when I started using nk_tree_push

could be a good clue. Does everything work correctly if you remove `nk_tree_push`? Worse case there is some undefined behavior either in my or your code. I will take a look and see what I can find out. Sadly I can promise anything since these kind of bugs are hard to track down.

**Comment by malytomas** [comment]
Ouch. 
You are genius!
It totally did NOT occur to me, that you may not copy the values.
Thank you very much. :D
