### ISSUE TITLE
Full init tutorial ?

### ISSUE THREAD

**Issue by malvinro** [vurtun/nuklear#651]
Hello guys, i'm new to this type of programming and i would like to know if there is some sort of tutorial about how to create a window and implement the nuklear GUI template.

I would like to create a login form, and i can't get nuklear to work with my Visual Studio 2015, do i need to add a window maker library ?

I m pretty sure that i m not the only one who's searching for a full tutorial about how to create a window. I was searching for it for the whole day, can't find smth.

I m getting errors like this:
![image](https://user-images.githubusercontent.com/21250958/37880028-b07d2a3a-308a-11e8-8074-4120f0912094.png)
I included GLFW correctly and copied the demo from your code, this is what i get. :(

**Comment by NeilGraham** [comment]
I'd be interested as well, I personally have no idea how I can start using this, but if I could have some short guide to generating my first page, that would be awesome!

**Comment by vurtun** [comment]
Hey @malvinro,
sorry but I cannot make out your errors from you screenshot. 
I also cannot make out if these are just intellisense errors or actual build errors.

Did you take the whole demo with both `main.c` and `nuklear_glfw_gl3.h`?
Also did you include `nuklear.h` in at least one source file with define `NK_IMPLEMENTATION` defined? Same for `nuklear_glfw_gl3.h`.

```c
/* any .h file */
/* flags */
#include "nuklear.h"

/* one source file */
#define NK_IMPLEMENTATION
#include "nuklear.h"

```

**Comment by lieff** [comment]
Problem also can be in Launch.cpp, demo code assumes pure c, c++ needs porting. Try change extension to Launch.c .

**Comment by malvinro** [comment]
Idk why but now it's working 👍 
Now i have another problem, @vurtun, you could help me with that because i cant rlly understand the library by now.
So ive created an GLFW window, which have the same size as the nukelar form, i made it borderless so it looks clean.
![image](https://user-images.githubusercontent.com/21250958/38266135-873e78ac-3780-11e8-8a31-9a173b2590f4.png)
Now i want to make it movable, i've tried to replace your moving function but couldnt rlly get it working.
Can you help me with this ?

**Comment by malvinro** [comment]
I solved it. Ty
