### ISSUE TITLE
Compile a .c file into a .o, as part of a larger project ?

### ISSUE THREAD

**Issue by zecruel** [vurtun/nuklear#654]
I wanted to compile a .c file into a .o, using `#include nuklear.h` without `#define NK_IMPLEMENTATION`, as part of a larger project.

But when compiling are returned several errors, for example:

```
src/nuklear.h:276:61: error: size of array '_dummy_array405' is negative
   #define NK_STATIC_ASSERT(exp) typedef char NK_UNIQUE_NAME(_dummy_array)[(exp)?1:-1]
```

Is it possible to do it this way? Is there any other alternative?

**Comment by vurtun** [comment]
Hey @zecruel,
the error you got is an specific error generated by nuklear itself. Make sure you either define `NK_INCLUDE_FIXED_TYPES` or set each nuklear specific type to a corresponding C type with required size. The reason why I have these checks is to make sure that nuklear has types with a specific number of bits. Under normal circumstances nuklear tries to set the correct types for itself but it seems that in your case something is not correct.

So to hopefully fix the issue define `NK_INCLUDE_FIXED_TYPES` for both your header include and implementation include:

```c
/* header only */
#define NK_INCLUDE_FIXED_TYPES
#include "nuklear.h"

/* implementation file */
#define NK_INCLUDE_FIXED_TYPES
#define NK_IMPLEMENTATION

```
In general I would recommend adding the same compiler flags to nuklear for the header and implementation. For a more information take a look at the documentation. I documented which compiler flags have what requirement.

**Comment by zecruel** [comment]
Hi @vurtun,
Problem solved.
Nuklear is a great project! Thank you.
