### ISSUE TITLE
dangling pointer problem

### ISSUE THREAD

**Issue by cloudwu** [vurtun/nuklear#656]
I read the nuklear source today, and found a dangling pointer (maybe).

`nk_draw_list_clear` call `nk_buffer_clear(list->buffer);` and `nk_clear` call `nk_draw_list_clear`.
```C
NK_API void
nk_draw_list_clear(struct nk_draw_list *list)
{
   ...
    if (list->vertices)
        nk_buffer_clear(list->vertices);
   ...
}
...

NK_API void
nk_clear(struct nk_context *ctx)
{
   ...
    nk_draw_list_clear(&ctx->draw_list);
   ...
}
```

But list->buffer is set by `nk_draw_list_setup` ,
```C
NK_API void
nk_draw_list_setup(struct nk_draw_list *canvas, const struct nk_convert_config *config,
    struct nk_buffer *cmds, struct nk_buffer *vertices, struct nk_buffer *elements,
    enum nk_anti_aliasing line_aa, enum nk_anti_aliasing shape_aa)
{
    ....
    canvas->vertices = vertices;   // <----- vertices is on stack
    ...
}
...
NK_API nk_flags
nk_convert(struct nk_context *ctx, struct nk_buffer *cmds,
    struct nk_buffer *vertices, struct nk_buffer *elements,
    const struct nk_convert_config *config)
{
    ...
    nk_draw_list_setup(&ctx->draw_list, config, cmds, vertices, elements,
        config->line_AA, config->shape_AA);
    ...
}
```

In the demo https://github.com/vurtun/nuklear/blob/master/demo/d3d9/nuklear_d3d9.h
```C
NK_API void
nk_d3d9_render(enum nk_anti_aliasing AA)
{
  ...
  {
        struct nk_buffer vbuf, ebuf;   // <--- vbuf is on stack
        ....
        nk_buffer_init_default(&vbuf);
        nk_buffer_init_default(&ebuf);
        nk_convert(&d3d9.ctx, &d3d9.cmds, &vbuf, &ebuf, &config);   // <--- set &vbuf to d3d9.ctx
        ....
         nk_buffer_free(&vbuf);
        nk_buffer_free(&ebuf);
  }
  ...
   nk_clear(&d3d9.ctx);   // clear here , but vbuf is out of its lifetime.
}
```

ps. Another problem is that I can't call `nk_convert` twice in one frame, it cause a segmentation fault. The motivation is , if  no new input message, I want to call `nk_convert` again to render the same frame with last one.

**Comment by vurtun** [comment]
Hey @cloudwu,
thanks for the issue.

> I read the nuklear source today, and found a dangling pointer (maybe).

Thanks I will take a look and test it.

> Another problem is that I can't call nk_convert twice in one frame, it cause a segmentation fault. The motivation is , if no new input message, I want to call nk_convert again to render the same frame with last one.

I will try it out. So far I never tried to call `nk_convert` twice on the same frame so will check it out and see if it works. However another solution to your problem can be found in the documentation in menu `Drawing`. Basically you can check each frame for changes like so:

```c
//[... other defines ...]
#define NK_ZERO_COMMAND_MEMORY
#include "nuklear.h"
//
// setup context
struct nk_context ctx;
void *last = calloc(1,64*1024);
void *buf = calloc(1,64*1024);
nk_init_fixed(&ctx, buf, 64*1024);
//
// loop
while (1) {
    // [...input...]
    // [...ui...]
    void *cmds = nk_buffer_memory(&ctx.memory);
    if (memcmp(cmds, last, ctx.memory.allocated)) {
        memcpy(last,cmds,ctx.memory.allocated);
        const struct nk_command *cmd = 0;
        nk_foreach(cmd, &ctx) {
            switch (cmd->type) {
            case NK_COMMAND_LINE:
                your_draw_line_function(...)
                break;
            case NK_COMMAND_RECT
                your_draw_rect_function(...)
                break;
            case ...:
                // [...]
            }
        }
    }
    nk_clear(&ctx);
}
nk_free(&ctx);
```
While this particular version uses fixed memory the same pattern works for dynamic memory allocation as well (`nk_init_default, nk_init, nk_init_custom`). Important here is that `#define NK_ZERO_COMMAND_MEMORY` is defined before including `nuklear.h` to make sure that no padding bits cause problems.
