### ISSUE TITLE
Contextual is activated with another window on top (Bug)

### ISSUE THREAD

**Issue by EvilPudding** [vurtun/nuklear#657]
I've noticed when you have two windows one on top of the other, if you click within the bounds of a button from the window bellow, it doesn't activate, but if you right-click within the bounds of a `nk_contextual` from the window bellow, it gets activated.

**Comment by vurtun** [comment]
Hey @EvilPudding,
please create a minimal test case for me. Preferable using one of my demos and maybe a few screenshots showcasing the steps to reproduce it. Otherwise I have no idea how to reproduce it in a timely fashion.

**Comment by EvilPudding** [comment]
```c
int test_nuklear_bug(struct nk_context *ctx)
{
	if (nk_begin(ctx, "window1",
			nk_rect(10, 10, 230, 280),
			NK_WINDOW_BORDER|NK_WINDOW_MOVABLE|NK_WINDOW_SCALABLE|
			NK_WINDOW_CLOSABLE|NK_WINDOW_MINIMIZABLE|NK_WINDOW_TITLE))
	{
		struct nk_rect bounds = nk_window_get_bounds(ctx);
		if(nk_contextual_begin(ctx, 0, nk_vec2(150, 300), bounds))
		{

			nk_layout_row_dynamic(ctx, 25, 1);
			if(nk_contextual_item_label(ctx, "button", NK_TEXT_CENTERED))
			{
				printf("click\n");
			}
			nk_contextual_end(ctx);
		}
	}
	nk_end(ctx);
	if (nk_begin(ctx, "window2",
			nk_rect(30, 30, 230, 280),
			NK_WINDOW_BORDER|NK_WINDOW_MOVABLE|NK_WINDOW_SCALABLE|
			NK_WINDOW_CLOSABLE|NK_WINDOW_MINIMIZABLE|NK_WINDOW_TITLE))
	{ }
	nk_end(ctx);
	return 1;
}
```
If you right-click the second window, which is on top, the contextual opens.

![image](https://user-images.githubusercontent.com/7356051/38309458-07173ef6-3812-11e8-86d4-17c6a9de1972.png)
