### ISSUE TITLE
Knowing if an event has been captured or not

### ISSUE THREAD

**Issue by MickaelSERENO** [vurtun/nuklear#669]
Hi,

First thank you for your library, it is quite useful !
I wanted to know, is there a way to know if an input has been captured by a context or not ? Since we use nuklear with another render system, it may be useful to know if an input is for the UI or not.

Thank you !

**Comment by vurtun** [comment]
Hey @MickaelSERENO,
please have a look if function `int nk_item_is_any_active(struct nk_context*);` fits your bill. If I remember correctly it checks the input state of the last frame. So you have to call it after running all nuklear UI code to check.

**Comment by MickaelSERENO** [comment]
Indeed, I haven't seen this function. Thank you !
