### ISSUE TITLE
Is there currently a way to make buttons inactive/disabled?

### ISSUE THREAD

**Issue by pragmascript** [vurtun/nuklear#673]
Is there currently a way to make buttons inactive/disabled,
so they are grayed out and non interactable instead of just making them invisible / not rendering them.

**Comment by vurtun** [comment]
Hey @pragmascript,
this: #213 could be interesting. Rereading the problem I still am of the opinion that fitting the functionality to turn widget inactive should not be added as parameter into each widget. However at least for some widgets it may be a possible to have something like:

```c
/* sometimes disabled */
if (some_state)
    nk_button_disable(ctx, ...)
if (nk_button_label(...)) {
    /* Do some stuff */
}
if (nk_button_label(...)) {
    /* Do some stuff */
}
if (some_state)
    nk_button_enable(...)

/* always enabled */
if (nk_button_label(...)) {
    /* Do some stuff */
}
```
 The enable and disable function would then just execute the style pushing and popng as well as setting the panel to read only.

**Comment by pragmascript** [comment]
Thanks for the answer I will look into #213, another option could be a global flag on the context e.g. which is shared among all widgets e.g.:
```csharp
int was_active = nk_get_active(ctx);
nk_set_active(ctx, nk_false);
/* place some inactive widgets...*/
if (nk_button_label(...)) {
    /* Do some stuff */
}
nk_set_active(ctx, was_active);
```
