### ISSUE TITLE
Problem with the pop-up window

### ISSUE THREAD

**Issue by olegk0** [vurtun/nuklear#674]
Hi
If after right-clicking and pop-up window - we close it by clicking outside the window - everything is ok.
But if we close the window explicitly or implicitly calling nk_contextual_close (), then we can open a new pop-up window only in the same place where we called the previous one.

I made a change in the function nk_contextual_begin ...
```c
**** cute from*****
    /* check if currently active contextual is active */
    popup = win->popup.win;
    is_open = (popup && win->popup.type == NK_PANEL_CONTEXTUAL);
    is_clicked = nk_input_mouse_clicked(&ctx->input, NK_BUTTON_RIGHT, trigger_bounds);
    if (win->popup.active_con && win->popup.con_count != win->popup.active_con)
        return 0;
//*********** add from
    if(!is_open && win->popup.active_con)
	win->popup.active_con = 0;
//*********** add to
    if ((is_clicked && is_open && !is_active) || (!is_open && !is_active && !is_clicked))
        return 0;
    /* calculate contextual position on click */
**** cute to*****
```
and the problem disappeared from me

sorry - English is not my native language

PS: You can reproduce the problem using a standard demo file overview.c
section Popup
1. call popup by Right click on  "Right click me for menu"
2. click About item
3. close About window by click on [X]
4. try call popup on red color button --- and nothing

**Comment by vurtun** [comment]
Hey @olegk0,
thanks for the issue, description to reproduce the problem and fix. The problem is now hopefully fixed.
