### ISSUE TITLE
Combo Style

### ISSUE THREAD

**Issue by jbmcgee** [vurtun/nuklear#679]
Trying to set the color of the background of labels in the combo box, but haven't been successful. Below is basically what I'm doing.

```
nk_style_from_table(ctx, table);


nk_style_push_color(ctx, &style->combo.label_normal, nk_rgba(255, 0, 0, 255));
nk_style_push_style_item(ctx, &style->combolabel_normal, nk_style_item_color(nk_rgba(255, 0, 0, 255)));

selected = nk_combo(...);

nk_style_pop_color(ctx);
nk_style_pop_style_item(ctx)
```

**Comment by vurtun** [comment]
Hey @jbmcgee,
do you mean the color of the selected combo box label or the labels inside the combo popup?

**Comment by jbmcgee** [comment]
@vurtun The labels inside the combo popup.

**Comment by vurtun** [comment]
The labels inside the combo box use `&style->contextual_button` for some reason. So you can try and modify it.
