### ISSUE TITLE
pre-baking font for embedded evice

### ISSUE THREAD

**Issue by diggit** [vurtun/nuklear#680]
Hi @vurtun, I want to use your library in embedded device. I'd like to use nuklear's font baking, but resources are limited and you mentioned separate font baking in #87.

> ... (You could also bake the font separately)

So here is small program to generate bitmap  (not sure about terminology) on which `img` points. Can I somehow obtain individual characters positions and their dimensions in this bitmap?

Or is this a wrong approach and there is better way?

```c
#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#define NK_IMPLEMENTATION

#include "../nuklear/nuklear.h"


int main(void)
{
	int img_width;
	int img_height;
	struct nk_font_atlas atlas;
	nk_font_atlas_init_default(&atlas);
	nk_font_atlas_begin(&atlas);
	struct nk_font *font = nk_font_atlas_add_from_file(&atlas, "../nuklear/extra_font/Roboto-Regular.ttf", 20, 0);
	const void* img = nk_font_atlas_bake(&atlas, &img_width, &img_height, NK_FONT_ATLAS_ALPHA8);
	nk_font_atlas_end(&atlas, nk_handle_id(0), 0);

	//save img contents somewhere else

	nk_font_atlas_clear(&atlas);
}
```

**Comment by vurtun** [comment]
You would have to iterate over each glyph inside `nk_font`. Each glyph has the codepoint, advance, and position inside the texture atlas stored. You could write each of them out and read them back in later.
