### ISSUE TITLE
How to create a text input box

### ISSUE THREAD

**Issue by mathewcook633** [vurtun/nuklear#683]
I see that editbox in note but can't seem anyway to be able to create a box to allow someone to enter text in there. 
Is this still possible if so how? Thanks :)

**Comment by trexxet** [comment]
```c
// somewhere out of cycle
char buf[256] = {0};
// in window
nk_edit_string_zero_terminated (ctx, NK_EDIT_FIELD, buf, sizeof(buf) - 1, nk_filter_default);
if (nk_button_label (ctx, "Done"))
	printf ("%s\n", buf);
```
![image](https://user-images.githubusercontent.com/4649497/39671756-06eca8ac-5127-11e8-95e1-e93d924a8ad5.png)

**Comment by EvilPudding** [comment]
Always check the `overview.c`, it contains a working example of what you require.
