### ISSUE TITLE
Better looking font rendering

### ISSUE THREAD

**Issue by guillaumechereau** [vurtun/nuklear#69]
The default font rendering used in the demos look quite blurry.
Is there a way to get pixel perfect font?

**Comment by vurtun** [comment]
I fixed the issue and the default font should now be pixel perfect.

**Comment by Temtaime** [comment]
![image](https://user-images.githubusercontent.com/7421889/68228327-4ffce900-0006-11ea-994c-fac70b7075b6.png)
This is roboto regular 14. And it looks really awful.
Built-in font is pixel perfect, yes, but it doesn't support any other languages.
Is there something i can do?
Previously i used sdl_ttf to render fonts and it was really beautiful.

**Comment by prust** [comment]
@Temtaime: I'm using a high-DPI monitor and had to set `oversample_h` and `oversample_v` to a higher number in order to get non-blurry fonts:

```c
  struct nk_font_config config = nk_font_config(title_size);
  config.oversample_h = 4;
  config.oversample_v = 4;
  struct nk_font *museo_title = nk_font_atlas_add_from_file(atlas, "./MuseoSans_100.ttf", title_size, &config);
```

**Comment by Temtaime** [comment]
@prust Thanks, but it doesn't make much difference. It's unreadable anyway.
