### ISSUE TITLE
how to scroll to bottom of a nk_edit_buffer widget

### ISSUE THREAD

**Issue by trlsmax** [vurtun/nuklear#691]
Hi,
I want to use a nk_edit_buffer widget as a message output console, but I can't find
a way to scroll to bottom automatically.

Is there a way to do that ?
Thanks.

**Comment by vurtun** [comment]
No sure what you need, but did you take a look at the `NK_EDIT_GOTO_END_ON_ACTIVATE` flag. As soon as an edit field is activated it should directly jump to the end of the buffer. If you want to do it manually then I would recommend at finding out how it was implemented and manually add a function to do it for you.

**Comment by trlsmax** [comment]
Thank you for you tips, but I'm not sure if I did it wrong, it still not work.

What I want to do is display the messages come from serial port on the edit
and scroll to the end when new messages display.

At line 22691 of nuklear.h:
```
        if (flags & NK_EDIT_GOTO_END_ON_ACTIVATE) {
            edit->cursor = edit->string.len;
            in = 0;
        }
```

my code is :
```
//init 
struct nk_text_edit com_msg;
nk_textedit_init_default(&com_msg);

//render
static const nk_flags flags = NK_EDIT_BOX|NK_EDIT_GOTO_END_ON_ACTIVATE;
struct nk_vec2 win_size = nk_window_get_content_region_size(ctx);
nk_layout_row_dynamic(ctx, win_size.y - 45, 1);
nk_edit_buffer(ctx, flags, &com_msg, nk_filter_default);

//insert message
nk_str_append_str_char(&(com_msg.string), cmd_str);
com_msg.cursor = com_msg.string.len;
```
