### ISSUE TITLE
How fix (or silent) warnings?

### ISSUE THREAD

**Issue by zecruel** [vurtun/nuklear#696]
Hello,

How to fix the following warnings:

src/nuklear.h: In function 'nk_labelf_colored':
src/nuklear.h:19176:5: warning: implicit declaration of function 'nk_labelfv_colored' [-Wimplicit-function-declaration]
     nk_labelfv_colored(ctx, flags, color, fmt, args);
     ^
src/nuklear.h: In function 'nk_labelf_colored_wrap':
src/nuklear.h:19185:5: warning: implicit declaration of function 'nk_labelfv_colored_wrap' [-Wimplicit-function-declaration]
     nk_labelfv_colored_wrap(ctx, color, fmt, args);
     ^
src/nuklear.h: In function 'nk_labelf':
src/nuklear.h:19193:5: warning: implicit declaration of function 'nk_labelfv' [-Wimplicit-function-declaration]
     nk_labelfv(ctx, flags, fmt, args);
     ^
src/nuklear.h: In function 'nk_labelf_wrap':
src/nuklear.h:19201:5: warning: implicit declaration of function 'nk_labelfv_wrap' [-Wimplicit-function-declaration]
     nk_labelfv_wrap(ctx, fmt, args);
     ^
src/nuklear.h: At top level:
src/nuklear.h:19205:1: warning: conflicting types for 'nk_labelfv_colored'
 nk_labelfv_colored(struct nk_context *ctx, nk_flags flags,
 ^
src/nuklear.h:19176:5: note: previous implicit declaration of 'nk_labelfv_colored' was here
     nk_labelfv_colored(ctx, flags, color, fmt, args);
     ^
src/nuklear.h:19214:1: warning: conflicting types for 'nk_labelfv_colored_wrap'
 nk_labelfv_colored_wrap(struct nk_context *ctx, struct nk_color color,
 ^
src/nuklear.h:19185:5: note: previous implicit declaration of 'nk_labelfv_colored_wrap' was here
     nk_labelfv_colored_wrap(ctx, color, fmt, args);
     ^
src/nuklear.h:19223:1: warning: conflicting types for 'nk_labelfv'
 nk_labelfv(struct nk_context *ctx, nk_flags flags, const char *fmt, va_list args)
 ^
src/nuklear.h:19193:5: note: previous implicit declaration of 'nk_labelfv' was here
     nk_labelfv(ctx, flags, fmt, args);
     ^
src/nuklear.h:19231:1: warning: conflicting types for 'nk_labelfv_wrap'
 nk_labelfv_wrap(struct nk_context *ctx, const char *fmt, va_list args)
 ^
src/nuklear.h:19201:5: note: previous implicit declaration of 'nk_labelfv_wrap' was here
     nk_labelfv_wrap(ctx, fmt, args);
     ^
src/nuklear.h: In function 'nk_tooltipf':
src/nuklear.h:25177:5: warning: implicit declaration of function 'nk_tooltipfv' [-Wimplicit-function-declaration]
     nk_tooltipfv(ctx, fmt, args);
     ^
src/nuklear.h: At top level:
src/nuklear.h:25181:1: warning: conflicting types for 'nk_tooltipfv'
 nk_tooltipfv(struct nk_context *ctx, const char *fmt, va_list args)
 ^
src/nuklear.h:25177:5: note: previous implicit declaration of 'nk_tooltipfv' was here
     nk_tooltipfv(ctx, fmt, args);
     ^

Thanks,

Ezequiel

**Comment by vurtun** [comment]
Hey. This looks like you don't have the same flags for the header and implementation. Could you make sure that you always provided the same flags.

**Comment by zecruel** [comment]
That's right! I'm a little ashamed ... Thank you.
