### ISSUE TITLE
Example fail with "XConvertSelection" (undefined reference to symbol)

### ISSUE THREAD

**Issue by lealinux** [vurtun/nuklear#70]
Hello,
We try to compile example and, we have this error : 

```
nuklear/example# make
rm -f bin/node_editor
clang -std=c99 -pedantic -O2 -o bin/node_editor node_editor.c -lglfw3 -lGL -lm -lGLU -lGLEW -I/usr/local/include -L/usr/local/lib
/usr/bin/ld: /usr/local/lib/libglfw3.a(x11_window.c.o): undefined reference to symbol 'XConvertSelection'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [node_editor] Error 1
```

We have lib glfw 3.1.2-1  (librairies and headers). Tested with github version and release version (3.1.2)

Sincerely,

**Comment by vurtun** [comment]
First thanks for the issue. Quick two questions before I dig deeper. First did you try building with flag:   -lX11. It looks to me like you use a static library of glfw and I don't know if this includes xlib. If that did not work does compiling and running the glfw demo work?

**Comment by mlabbe** [comment]
Hey,

I'm having this issue, too, compiling the files in `example`.  I compiled glfw3 with no custom flags on Linux.

The fix for me was to specify the glfw dependencies in the Makefile:

    LIBS = -lGL -lm -lGLU -lGLEW `pkg-config glfw3 --static --libs`

`pkg-config glfw3 --static --libs` is what I added to to line 13 and it compiled.
