### ISSUE TITLE
Draw Line interface

### ISSUE THREAD

**Issue by SairesArt** [vurtun/nuklear#704]
I'm looking to drawing lines à la Photoshop selection tools inside a window on top of a nk_image.
nk_draw_list is hidden as a part of the nk_context, so using nk_draw_list_path_line_to without diving deep into nuklear's implementation becomes impossible for C virgins.

Is there a way / could a line drawing command be implemented for easy use inside your GUI implementation?
By extension I also need the ability to draw bézier cruves. How should I go about implementing this, could you point me into a direction or a resource?

**Comment by vurtun** [comment]
You can just use the command buffer API instead. It is the abstraction used by nuklear itself to draw. The command buffer itself can then be converted to vertexes buffers.

In the documentation (in section drawing) I have an example on how to do custom drawing.
