### ISSUE TITLE
Dynamic layouting makes gaps between widgets

### ISSUE THREAD

**Issue by Lusted4ever** [vurtun/nuklear#707]
i'm making simple gui with fully window-relative positioning and i have to(connect) place widgets closely to each other. The problem is that, sometimes(depends on the window size) there is 1pixel gap between them. Is there any solutions?

**Comment by vurtun** [comment]
That sound like a rounding error. The problem is that nuklear uses float values that will be converted to integer. The problem is that just mindlessly converted from float to int can cause holes/gaps. However unless you provide more information I cannot pin point the problem.

**Comment by Lusted4ever** [comment]
For example:

```
		int i;		

		#define s ctx->style	
		s.button.border = s.button.rounding = 0;
		s.window.spacing  = nk_vec2(0, 0);
		#undef s

		nk_layout_row_dynamic(ctx, 50, 7);
		for (i = 0; i < 7; i++)
			nk_button_color(ctx, nk_rgb(0,255,0));
```


This code actually causes gaps if window gets resized.

**Comment by Lusted4ever** [comment]
Guess i already fixed that out. Sure, that was a floating point error. 

Solution was pretty stupid: i've just added fraction of widget position to the border length. So, it now predict gaps. But i need to ensure if everything works right, before pulling a patch.
