### ISSUE TITLE
Reduce all structs to under 20 elements for Scala Native compatibility?

### ISSUE THREAD

**Issue by sorenbug** [vurtun/nuklear#722]
Scala Native (as of 0.3.8) still uses different classes for different struct sizes, from 0 to 22. This makes these two structs an issue currently:

 * `nk_style_slider`
 * `nk_style_window`

Other structs over 20 in size are:

 * `nk_style_selectable`
 * `nk_style_scrollbar`
 * `nk_style_edit`
 * `nk_style`

My proposed solution is to break similar values (i.e. ones that correspond to sets/vectors/points) into their own structs, but I don't know how feasible this is.

**Comment by dumblob** [comment]
I'm not a Scala expert, but there shouldn't be any huge issues with "22" in Scala any more. But in any case, the more common approaches how to overcome this older and really weird limitation are listed e.g. on https://stackoverflow.com/questions/20258417/how-to-get-around-the-scala-case-class-limit-of-22-fields

**Comment by sorenbug** [comment]
@dumblob Scala Native defines structs as `CStruct{N}` with each internal type being generic. For example:

    type nk_buffer = CStruct9[
      Ptr[nk_buffer_marker],
      nk_allocator,
      nk_allocation_type,
      nk_memory,
      CFloat,
      nk_size,
      nk_size,
      nk_size,
      nk_size
    ]

In Scala, `ClassName[T, U, V]` means `T`, `U`, and `V` are generic types of class `ClassName`. Scala Native only defines structs up to `CStruct22`. [I have a project which has attempted to write bindings](https://gitlab.com/srnb/snuklear), which has been generated by a binding generator, but it fails to compile when encountering `CStruct25` and `CStruct30`.

**Comment by sorenbug** [comment]
Note that the issue which proposes to solve this problem is in Scala Native's backlog. https://github.com/scala-native/scala-native/issues/897

**Comment by dumblob** [comment]
@sorenbug thanks for the pointers. To me it seems though, that this limitation is quite specific and changing Nuklear would affect way more users than writing a shim for this for the few Scala Native users.

Do you see it the same way as I do, @sorenbug?

**Comment by sorenbug** [comment]
Yeah, I do. I was talking to my dad about this and he raised the same
point. I think what I'll do is go into the binding generator and turn all
structs into byte arrays and wrap them.

dumblob <notifications@github.com> schrieb am Mo., 6. Aug. 2018, 10:59:

**Comment by dumblob** [comment]
Good, then don't forget to make a pull request with a link to your bindings in the [README.md](https://github.com/vurtun/nuklear#bindings ) file :wink:.
