### ISSUE TITLE
help on make my first helloworld example

### ISSUE THREAD

**Issue by ASHIT-AXAR** [vurtun/nuklear#740]
hello
i'm struggling to create a simple helloworld example for the whole day. (still unable to get things working)  
can anybody guide me what tools and dependencies is needed and how to build a helloworld, step by step. please.
(OpenGL ? or SDL ? or GLFW ? which should i download ?)
i'm in windows7 and downloaded and installed MinGW (both 32 and 64)
what are all the compile and build commands i need to type in the command prompt ?
what files are needed to be in the helloworld folder ?
my issue is setting things up for the first time.
any help appreciated.

**Comment by kphillisjr** [comment]
To make things Easier, I recommend looking at the following demos that are intended for use on Windows... 
- Direct3D 9.0 - https://github.com/vurtun/nuklear/tree/master/demo/d3d9
- Direct3D 11.0 - https://github.com/vurtun/nuklear/tree/master/demo/d3d11
- GDI - https://github.com/vurtun/nuklear/tree/master/demo/gdi
- GDI+ - https://github.com/vurtun/nuklear/tree/master/demo/gdip


Now if your insistent on using OpenGL, You have two main choices for windows... GLFW version 3.x ( http://www.glfw.org/ ) or SDL 2.x ( http://libsdl.org/ ). The Demos involving GLFW3/libSDL2 require first getting the examples included with these programs compiling/running. 

Also as a quick tip, I highly recommend looking at the cmake ( https://cmake.org/ ) utility when trying to build programs with mingw.

**Comment by ASHIT-AXAR** [comment]
thank you @kphillisjr 
no, i don't insist on some special tool. i was using C# so far (you know, press a button and hey, here is your app :see_no_evil: . this is why i'm a little strange with these tools :grimacing: ). recently i installed ubuntu beside window7 (dual boot), and this lead me to search for something crossplatform? 
ok for now, i will try those links to see what can i do
thank you.

**Comment by vtorri** [comment]
to compile the d3d11 demo with MSYS2 + mingw-w64 : 

go to the directory demo/d3d11, then 

gcc -s -O2 -o nuklear.exe main.c -L /opt/mingw32/i686-w64-mingw32/lib -ld3d11 -ldxguid

where /opt/mingw32/i686-w64-mingw32/lib is the directory where libd3d11.a nad libdxguid.a are located

**Comment by ASHIT-AXAR** [comment]
thank you @vtorri 
this is a great help. i'm gonna use MinGW more (i found it both on windows and ubuntu).
which one do you recommend to use ? (opengl ? sdl ? or ?)

**Comment by vtorri** [comment]
cross-platform : opengl (maybe adding a vulkan demo would be nice). I would prefer opengl compared to sdl.

**Comment by kphillisjr** [comment]
@vtorri - The libSDL and GLFW demos are a cross-platform examples that are as close to write once run anywhere when dealing with OpenGL. This is because libSDL and GLFW contain all the code for window creation and OpenGL Context management.

**Comment by ASHIT-AXAR** [comment]
ya finally !! :v: :v:
i just could run d3d11 with visual studio 12 compiler .
that's a good starting point, i'll continue on this for a while.
no luck with opengl(glfw?glu?glew?) and MinGW(codeblocks+mingw: the only thing i'm sure is installed correctly as it's a one click setup :grin: ) yet, but i'm still trying. 
thank you for your time guys :pray:
