### ISSUE TITLE
[request] Add Raspberry Pi accelerated Open GL output (8$)

### ISSUE THREAD

**Issue by DeXP** [vurtun/nuklear#748]
[sdl_opengles2](https://github.com/vurtun/nuklear/tree/master/demo/sdl_opengles2) already supports Open GL ES 2 and Web GL. It can be compiled on Raspberry Pi (Raspbian Linux), but gives black square only. Please fix it to have an ability to have accelerated Open GL ES output on Raspberry Pi.

[8$ bounty](https://www.bountysource.com/issues/63962582-request-add-raspberry-pi-accelerated-open-gl-output)

**Comment by alvaropg** [comment]
I have not experimented problems with OpenGL ES 2 in a Raspberry Pi 3. Just make sure that you compile against the Broadcom libraries in /opt (if you are using Raspbian). You can use pkg-config to ensure:

$ PKG_CONFIG_PATH=/opt/vc/lib/pkgconfig/ pkg-config --cflags bcm_host brcmglesv2

I hope it helps!

**Comment by DeXP** [comment]
@cyclopsian, I have Raspberry Pi 3, most updated raspbian:
```bash
$ ./bin/demo
[GL]: failed to compile vertex shader: 
demo: nuklear_sdl_gles2.h:125: nk_sdl_device_create: Assertion `status == GL_TRUE' failed.
Aborted
```

**Comment by cyclopsian** [comment]
@DeXP That is strange, the error message is coming up blank. I would try to see if you can run some other OpenGL programs such as the hello_triangle one in the demo directory ([see instructions here](https://www.raspberrypi.org/documentation/usage/demos/). If those work then it's possible the issue is with your version of SDL.

**Comment by DeXP** [comment]
@cyclopsian Yep, hello_triangle just works: shows spinnig textured cube, no additional info in the console. I've installed SD2 development package form apt, official repos (just typed something like `aptitude install libsdl2-dev` in the console). Could it be wrong somehow?

**Comment by cyclopsian** [comment]
@DeXP Upon inspection it looks like the version of SDL2 in the raspbian repo is *not* properly compiled with Raspberry Pi Support. I was able to get it to work, but I compiled my own SDL2. If you do that it should automatically build the RPI video driver.

**Comment by DeXP** [comment]
@cyclopsian I did it, mostly according to https://choccyhobnob.com/raspberry-pi/sdl2-2-0-8-on-raspberry-pi/ :
`$ ./configure --disable-pulseaudio --disable-esd --disable-video-mir --disable-video-wayland --host=arm-raspberry-linux-gnueabihf`

```bash
SDL2 Configure Summary:
Building Shared Libraries
Building Static Libraries
Enabled modules : atomic audio video render events joystick haptic sensor power filesystem threads timers file loadso cpuinfo assembly
Assembly Math   :
Audio drivers   : disk dummy oss alsa(dynamic) nas(dynamic)
Video drivers   : dummy rpi x11(dynamic) opengl opengl_es1 opengl_es2 vulkan
X11 libraries   : xcursor xdbe xinerama xinput2 xinput2_multitouch xrandr xscrnsaver xshape xvidmode
Input drivers   : linuxev linuxkd
Using libsamplerate : NO
Using libudev       : YES
Using dbus          : NO
Using ime           : YES
Using ibus          : NO
Using fcitx         : NO
```

Then compiled demo with usage of SDL2 from `/usr/local/lib`:

```bash
$ cc main.c -std=c99 -pedantic -O2 -o bin/demo `PKG_CONFIG_PATH=/opt/vc/lib/pkgconfig/ pkg-config --cflags --libs bcm_host brcmglesv2` -L/usr/local/lib -lSDL2 -lm -Wl,-rpath=/usr/local/lib
$ ldd bin/demo
	linux-vdso.so.1 (0x7ed41000)
	/usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76ed9000)
	libbrcmGLESv2.so => /opt/vc/lib/libbrcmGLESv2.so (0x76e9c000)
	libbcm_host.so => /opt/vc/lib/libbcm_host.so (0x76e75000)
	libvcos.so => /opt/vc/lib/libvcos.so (0x76e5b000)
	libvchiq_arm.so => /opt/vc/lib/libvchiq_arm.so (0x76e45000)
	libSDL2-2.0.so.0 => /usr/local/lib/libSDL2-2.0.so.0 (0x76d2d000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76cae000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76c85000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76b46000)
	libbrcmEGL.so => /opt/vc/lib/libbrcmEGL.so (0x76b0d000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76afa000)
	librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0x76ae3000)
	/lib/ld-linux-armhf.so.3 (0x76eef000)
```
The result is the same:
```
$ ./demo
[GL]: failed to compile vertex shader: 
demo: nuklear_sdl_gles2.h:125: nk_sdl_device_create: Assertion `status == GL_TRUE' failed.
Aborted
```

**Comment by DeXP** [comment]
I get it working, finally! Yep, the problem was in a SDL's videodriver. And yes, default version in a Raspbian's repo do not supports `rpi` driver. So SDL have to be compiled.

However, default `x11` driver is not working for accelerated Open GL ES2 too. There are two ways to solve this:

1) Compile SDL without X11 support: *--disable-video-x11* configure option.

2) Set `SDL_VIDEODRIVER` environment variable before each run to `rpi`: `export SDL_VIDEODRIVER=rpi`

@cyclopsian you gived me the key to solve the issue. Can you claim fixed the issue on BountySource? Otherwise I will move the funds to [Mac Request](https://github.com/vurtun/nuklear/issues/747).

**Comment by cyclopsian** [comment]
@DeXP Thanks so much, glad to hear it worked! I started a solution on BountySource, I believe that means you can close the issue now and I will be assigned the bounty.

**Comment by DeXP** [comment]
Yep, solved

**Comment by ktb92677** [comment]
Hey guys, sorry to revive a dead topic like this but does anyone here know why my instance is fairly laggy? I am measuring it takes around 36ms per render cycle to show on the screen. This is worse than 30fps. Any help would be greatly appreciated!

**Comment by ktb92677** [comment]
FYI I have narrowed down the problematic lines. They are as follows:

```
glBufferData(GL_ARRAY_BUFFER, max_vertex_buffer, NULL, GL_STREAM_DRAW);
glBufferData(GL_ELEMENT_ARRAY_BUFFER, max_element_buffer, NULL, GL_STREAM_DRAW);
```

Those two lines take 10ms and 24ms respectively. If anyone who knows a lot of Opengles2 it would be great if you could chime in as I really want to bring the FPS closer to 60 if possible.

**Comment by cyclopsian** [comment]
@ktb92677 If you want to know more about the topic, emscripten has some docs on optimizing GLES (WebGL is an implementation of the GLES API). Particularly this section which is relevant: https://emscripten.org/docs/optimizing/Optimizing-WebGL.html#gpu-driver-friendly-memory-access-behavior

>- Prefer calling glBufferSubData() and glTexSubImage2D/3D() when updating buffer texture data, even when the whole contents of the texture or the buffer changes. If the size of a buffer would shrink, do not eagerly re-create the storage, but simply ignore the excess size.
>- For dynamic vertex buffer data, consider double- or even triple-buffering VBOs each frame, to avoid uploading a VBO that is still in use. Prefer using GL_DYNAMIC vertex buffers over GL_STREAM.

This may or may not help depending on the device & driver you're using.

**Comment by ktb92677** [comment]
For anyone else stumbling across this sometime in the future here was the solution:

Adjusting these lines:

```
#define MAX_VERTEX_MEMORY 512 * 1024
#define MAX_ELEMENT_MEMORY 128 * 1024
```

To this:

```
#define MAX_VERTEX_MEMORY 128 * 1024
#define MAX_ELEMENT_MEMORY 32 * 1024
```

Solved the performance issues and now the FPS is sitting comfortably at 60FPS.

**Comment by ktb92677** [comment]
@cyclopsian any chance you can help me with this issue:

What I would like to do is within the same instance of the program fully initialize and delete an SDL+GLES instance twice within the run time of the same program. I have adapted the code base posted above to simply call the contents of main() twice with a slight pause in between. However on the second run the following assert fails:

```
glShaderSource(dev->vert_shdr, 1, &vertex_shader, 0);
    glShaderSource(dev->frag_shdr, 1, &fragment_shader, 0);
    glCompileShader(dev->vert_shdr);
    glCompileShader(dev->frag_shdr);
    glGetShaderiv(dev->vert_shdr, GL_COMPILE_STATUS, &status);
    assert(status == GL_TRUE);
```

I used the following code to print the error:

```
if (status != GL_TRUE) {
                GLint maxLength;
        glGetShaderiv(dev->vert_shdr, GL_INFO_LOG_LENGTH, &maxLength);

                GLchar infoLog[maxLength];

                memset(&infoLog, 0, maxLength);

                glGetShaderInfoLog(dev->vert_shdr, maxLength, &maxLength, infoLog);

                printf("error: %s\n", infoLog);
        }
```

maxLength is zero after glGetShaderiv returns. Also if I manually set maxLength to a larger number glGetShaderInfoLog doesn't even touch infoLog. It leaves it completely empty. Any help would be greatly appreciated

**Comment by dumblob** [comment]
~~~c
#define MAX_VERTEX_MEMORY 128 * 1024
#define MAX_ELEMENT_MEMORY 32 * 1024
~~~
I think this deserves PR - will you make one?
