### ISSUE TITLE
OpenGL Scaling bug

### ISSUE THREAD

**Issue by SairesArt** [vurtun/nuklear#755]
I'm having a strange bug occur when scaling an image. (GLFW, Opengl2)
I'm zooming in and out of an image by scaling the nk_rect of nk_draw_image(). Although the same happens when scaling via nk_layout_row_static. Once one of the dimensions goes over 8192 it strangely "shifts" out of view to a side. But after a certain range it recovers to how it should look! (See attached gif) This happens with all images.
I'm at a loss on how to debug this, since the numbers produced by my code show no shifting of any sort.
The bug only present when using the GPU.
It does not occur when setting LIBGL_ALWAYS_SOFTWARE=1 and using the CPU.

Can this be fixed or is it unreachable, due to being GPU side? Am I implementing the zooming wrong?
![openglbug](https://user-images.githubusercontent.com/10562480/47031852-1c3bf080-d171-11e8-8c29-596c14a0ebd2.gif)

Also: Also even with Software rendering I can't have an nk_image dimension bigger than 65536, then the image dissapears or warps heavily. Is this an inherent limitation of OpenGL?

**Comment by nkindt** [comment]
You can check the supported texture size via (after OpenGL context initialization):
`glGetIntegerv(GL_MAX_TEXTURE_SIZE, ...)`

If the size smaller then what you target then you might need to resort to tiling (multiple textures with different picture parts).

**Comment by SairesArt** [comment]
> `glGetIntegerv(GL_MAX_TEXTURE_SIZE, ...)`
Yes, I'm aware, that the limit corresponds to my 8192 max texture limit.
I didn't think the translation to opengl would result in constant rescaling, but a camera movement.

So scaling an image with nk_layout_row_static to implement zoom is the wrong thing to do.
Guess I'll crop against ctx->current.layout.clip in ram and then scale.
