### ISSUE TITLE
Make a window created by nk_begin click-throughable

### ISSUE THREAD

**Issue by Hecklezz** [vurtun/nuklear#768]
I am trying to make it so something that is drawn, whether it be on the canvas or not completely ignores mouse input and clicks through it onto what is behind. Flags I have tried and a few others I believe: NK_WINDOW_NOT_INTERACTIVE, NK_WINDOW_NO_INPUT.

Am I doing something wrong or is it just not possible to have windows click-throughable?

**Comment by exphck** [comment]
Are you using nuklear as internal(dll)? I'm having the same problem

**Comment by Hecklezz** [comment]
No, I am not. I am just running it as a usual application.

**Comment by Hecklezz** [comment]
Sorry my fault, what I had to do was, use WS_EX_TRANSPARENT when creating the window.
