### ISSUE TITLE
UTF-8 encoding functions do not account for overlong-encoded code points

### ISSUE THREAD

**Issue by knight666** [vurtun/nuklear#78]
Specifically, `nk_utf_decode` naively assumes that:
- A control byte indicating a certain length means those bytes are available.
- An encoded code point never tries to encode a code point below or above its determined range.
- 7- and 8-byte encoded code points are valid.

`nk_utf_encode` assumes that values above 0x10FFFF are valid Unicode.

See here for examples of dangerous strings:

https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt

I would strongly advise the author(s) to take a look at [utf8rewind](https://bitbucket.org/knight666/utf8rewind), which passes the tests in the file I've linked and has almost 3000 unit, integration and performance tests.

**Comment by vurtun** [comment]
Thanks for the issue. In long term you are definitely right and I probably will have to update it. utf8rewind look goods and I will definitely use it for reference. Quick reassurance: `nk_utf_encode` and `nk_utf_decode` is basically your `codepoint_read` and `codepoint_write` or does it require more than that?

**Comment by knight666** [comment]
That is correct, `codepoint_read` is comparable to `nk_utf_decode` and `codepoint_write` is similar to `nk_utf_encode`.

There are a lot of tests covering these functions though: https://bitbucket.org/knight666/utf8rewind/src/4b48f694c6b77f8cbfa46522dc84fba1d7bf48b3/source/tests/suite-codepoint-read.cpp?at=default&fileviewer=file-view-default and https://bitbucket.org/knight666/utf8rewind/src/4b48f694c6b77f8cbfa46522dc84fba1d7bf48b3/source/tests/suite-codepoint-write.cpp?at=default&fileviewer=file-view-default

The problem with copying my implementations over is that you're missing out on these automated tests, which means you still can't guarantee that the same problems won't crop up again. The way I see it, you have three options:

* Copy my implementation. This is allowed by the license, if you credit me. This means you'll be covered by my tests, but not your own. Bugs may still be present.

* Write tests for your current functions and make them pass. The safest, but slowest option. You'll be covered by tests, but writing hundreds of tests is seriously brainless and painful work.

* Change your library to allow for dependencies. The drastic option. If you rewrite the library to use source files and compile to a dynamic library, you can use `utf8rewind` as a dependency. Obviously, this goes against the current philosophy of the project.

**Comment by vurtun** [comment]
Will see what I do.

**Comment by wasamasa** [comment]
I wonder whether [Bjoern Hoehrmann's UTF-8 DFA decoder](http://bjoern.hoehrmann.de/utf-8/decoder/dfa/) does any better.  It's even smaller than the existing implementation, flexible and MIT-licensed.
