### ISSUE TITLE
How to create a chat box?

### ISSUE THREAD

**Issue by keharriso** [vurtun/nuklear#781]
What I want:
* One message box above that scrolls independently.
* One input box below, anchored to the bottom of the window with a fixed height.
* The input box gets focused by the enter key and sends messages with the enter key when it's already  focused.
* New messages get added to the bottom of the message box and cause the message box to scroll to the bottom.
* Messages longer than the width of the window get wrapped seamlessly (not all messages have the same height).

The problems I've solved:
* Split the message box and input box into separate windows.
* Auto-focus the input box with nk_edit_focus
* Detect if the input box is active with the return value of the edit function.
* Use a loop to display all messages as labels.

The problems I haven't solved yet:
* Auto-scrolling the message box.
* Wrapping messages seamlessly.

Any help here?

**Comment by ChrisJackH** [comment]
I just recently needed a way to automatically have a nk_text_edit scroll to bottom on manual inserts.  https://github.com/vurtun/nuklear/issues/835

Did you solve any of these issues yourself?

**Comment by keharriso** [comment]
#802 solved this, but there is still the flicker problem mentioned in #326. I may try to solve this myself.

**Comment by dumblob** [comment]
@keharriso thanks for the info, glad you've solved most of it. Feel free to post your solution to #326 if you'll find one satisfying your needs.
