### ISSUE TITLE
Use Nuklear for web - through canvas

### ISSUE THREAD

**Issue by dumblob** [vurtun/nuklear#79]
Nowadays, web sites are not any more documents, but rather pretty complex UI applications. On the other hand, it's extremely difficult to get it working on all screen sizes and DPIs. With Nuklear it would be piece of cake.

I was thinking about compiling Nuklear to JS using [Emscripten](https://kripken.github.io/emscripten-site/docs/introducing_emscripten/about_emscripten.html) and drawing everything immediately to HTML5 canvas. The only question is performance. But I'm pretty certain, it'll be sufficient and we'll finally have a proper tool for building UIs on the screwed web. Also for future, it'll be (significantly?) more performant thanks to [WebAssembly](https://webassembly.github.io/), which allows highly optimized compilation from C.

Anyone has any hands-on experience?

**Comment by mmozeiko** [comment]
I haven't tried, but dear imgui has pull request with example for Emscripten (using SDL2): https://github.com/ocornut/imgui/pull/336
You could try porting source to work with nuklear.

**Comment by glegris** [comment]
I got the [SDL1.2 demo](https://github.com/vurtun/nuklear/tree/master/demo/sdl1_2) (SDL + SDL_gfx) work with Emscripten with very few modifications. Essentially I replaced the main function by emscripten_set_main_loop to avoid to block the browser thread. I didn't try with SDL/OpenGL yet.

If @vurtun is ok, I could do a pull request to add this in the demo directory.

**Comment by dumblob** [comment]
@glegris could you please make a separate gist first? I'll have time first in 3 weeks, but I would very much like to take a look at it.

**Comment by dumblob** [comment]
First fully functional prototype using WebGL and offering an online demo: https://github.com/vurtun/nuklear/pull/164 .

Now only a pure canvas solution (without WebGL and without glfw3) is missing.
