### ISSUE TITLE
nuklear_d3d11

### ISSUE THREAD

**Issue by alxbrn** [vurtun/nuklear#797]
I'm attempting to include the nuklear_d3d11.h into my project, but i'm getting a bunch of errors when attempting to compile...

`
identifier "ID3D11DeviceContext_IASetInputLayout" is undefined
identifier "ID3D11DeviceContext_IASetVertexBuffers" is undefined
and so on...
`

<img width="720" alt="bf06e02fa2a4e5b49c1ac2d36e5de254" src="https://user-images.githubusercontent.com/39629240/52351339-d9a56900-2a2a-11e9-8a46-1c8cffc7bead.png">

I might just be missing something simple, but a guiding hand would be appreciated.

**Comment by TooLazyToComeUpWithUsername** [comment]
Hello @alxbrn, have you found a solution? I am having the exact same issue.
