### ISSUE TITLE
Is there any way to sync scrollbars on different windows or nk_edit_string widgets?

### ISSUE THREAD

**Issue by BestMordaEver** [vurtun/nuklear#821]
I need to keep two nk_edit_string_zero_terminated widgets' scrollbars synced. They have the same height and the lines in a first widget are generated as they are put into the second. But when I run out of space on the second widget, it starts to scroll down on it, without scrolling down on the first one (as expected). Is there any way to synchronize those scrollbars?

**Comment by irtusb** [comment]
there is a [open pull request](https://github.com/vurtun/nuklear/pull/802) implementing the functions you need

**Comment by BestMordaEver** [comment]
I see. Which one do I use though? There're methods for groups, windows and pop-ups. Does text edit qualify as window?

**Comment by irtusb** [comment]
no idea, never tried it, but you can experiment with text edit directly or through a scrollable container

**Comment by BestMordaEver** [comment]
It doesn't allow you to change the scroll position in text edit and it's mostly because text edit on itself doesn't save it's scroll position when unfocused. But wrapping it in group and increasing size of the text edits did the trick, thank you.
