### ISSUE TITLE
Direct3D

### ISSUE THREAD

**Issue by kateon11** [vurtun/nuklear#83]
Any chance of adding some directx9/11 demos?

**Comment by vurtun** [comment]
I don't have a windows system and so far did not have a lot of luck using a VM and my knowledge using DirectX is quite limited. While it is on my list of things I would love to provide at the moment I first have to fix more urgent bugs.

**Comment by mmozeiko** [comment]
I've made Direct3D 11 demo. It's available in #103 pull request.
