### ISSUE TITLE
help on 9 sliced buttons

### ISSUE THREAD

**Issue by GreatIndieDeveloper** [vurtun/nuklear#833]
i want to make a 9 sliced Button in nuklear but i don't know where to start and pointers would be very helpful

**Comment by GreatIndieDeveloper** [comment]
forget about it i done it successfully

**Comment by dumblob** [comment]
Congrats. Any link to the solution you used?

**Comment by GreatIndieDeveloper** [comment]
i used a little bit of a dumb solution XD you can look in here : https://github.com/GreatIndieDeveloper/StrawEngine-Core/blob/master/Engine/Utils/nuklear.h 

i only do it for buttons for now so look at nk_draw_button() function and you will see my changes i know my code isn't great but i just did this quickly and gonna improve on it

**Comment by GreatIndieDeveloper** [comment]
by the way any advice to improve on the approach would be really appreciated
