### ISSUE TITLE
[SOLVED]best question ever about show widgets

### ISSUE THREAD

**Issue by lynxcode** [vurtun/nuklear#855]
hello how to it show widgets or button or windows? Is it use opengl or x org?

**Comment by dumblob** [comment]
Choose your favorite backend in [`demo/`](https://github.com/vurtun/nuklear/tree/master/demo ) and just run make to compile a demo binary. Or write your own backend - it's super easy as you can see in the demos.

**Comment by lynxcode** [comment]
so thanks, I will close it. sooon
