### ISSUE TITLE
Error: sizeof of array 'nk__check_...' is negative.

### ISSUE THREAD

**Issue by leonardosnt** [vurtun/nuklear#86]
![](http://i.imgur.com/wR8klwt.png)
![](http://i.imgur.com/WKKcw6Q.png)

I've tried with GCC and TIM-GCC.

**Comment by vurtun** [comment]
These checks are there to make sure that all types have the correct size. To fix it you can either define `NK_INCLUDE_FIXED_TYPES` which pulls in <stdint.h> and selects corrects types for you. Or if you don't want that you could directly define types.

**Comment by leonardosnt** [comment]
Thanks :)
