### ISSUE TITLE
New tag on StackOverflow

### ISSUE THREAD

**Issue by JamesTheHacker** [vurtun/nuklear#863]
Hey folks,

I hope you don't mind but I've created a new tag on StackOverflow for Nuklear related questions: https://stackoverflow.com/questions/tagged/nuklear. And here is the info page: https://stackoverflow.com/tags/nuklear/info

I'm not sure if anybody on the team has enough points to edit the description or the wiki page. If not let me know and I will make changes to the tag description and wiki to your liking.

**Comment by dumblob** [comment]
Thanks @JamesTheHacker . I'm not aware of anyone having the opportunity to edit the SO wiki, so feel free to do that. Then feel free to close this informative GitHub issue :wink:.
