### ISSUE TITLE
Assertion 'g->parent' fails in nk_group_scrolled_end(nk_context*) when creating a group within a group

### ISSUE THREAD

**Issue by BenjiBoy926** [vurtun/nuklear#865]
I am trying to use the nuklear library to layout a group with many rows, where one of the columns in each row is itself a group, like so:

![Wifi-screen-layout-diagram](https://user-images.githubusercontent.com/44412116/59724949-a648c700-91e0-11e9-9ca5-e6502284acf8.png)

But when I run the program, I get the following assertion:

`void nk_group_scrolled_end(nk_context*): Assertion 'g->parent' failed`

This assertion only appears to trigger for subgroups that are being setup outside of the main group's boundary.  The loop I'm using to layout the rows gets to loop 7 before triggering the assertion.  It might also be interesting to note that the rect of the group widget while out-of-bounds seems off.  Here's the data I collected:

```
Rendering wifi screen wifi #0
Current rect in wifi screen: 848.000000, 346.000000, 40.000000, 52.000000
Rendering wifi screen wifi #1
Current rect in wifi screen: 848.000000, 398.000000, 40.000000, 52.000000
Rendering wifi screen wifi #2
Current rect in wifi screen: 848.000000, 450.000000, 40.000000, 52.000000
Rendering wifi screen wifi #3
Current rect in wifi screen: 848.000000, 502.000000, 40.000000, 52.000000
Rendering wifi screen wifi #4
Current rect in wifi screen: 848.000000, 554.000000, 40.000000, 52.000000
Rendering wifi screen wifi #5
Current rect in wifi screen: 848.000000, 606.000000, 40.000000, 52.000000

// HERE: the rect takes a big leap off to the left and the dimensions get way bigger
Rendering wifi screen wifi #6
Current rect in wifi screen: 760.000000, 864.000000, 100.000000, 130.000000
Rendering wifi screen wifi #7
Current rect in wifi screen: 760.000000, 994.000000, 100.000000, 130.000000
```

I attempted to fix this by doing:

```c
struct nk_rect r;
enum nk_widget_layout_states state = nk_widget(&r, ctx);
if (state == NK_WIDGET_VALID) {
    // Render the row
}
```

But for some reason this prevents *all* of the rows from rendering.  (Perhaps I'm not using the function properly?)

This assertion doesn't trigger at all if I nest groups like this in a main group where the main group doesn't have a scrollbar.  This makes sense since the assertion triggered in `void nk_group_scrolled(nk_context*)`, which would probably only be called for a group with a scrollbar.

Here is the code that triggers the assertion:
```c
void Render_Main_Window_WIFI_SCREEN(WIFI_SCREEN* wifi_screen, GUI* gui) {
	//...etc

	// Start "main group" in the diagram
	if (
	Start_Group_With_Buffer(&wifi_screen->wifiConnectionGroup,
	gui->NK_Context, "wifi screen connections", NK_WINDOW_BORDER)) {
		// Only display wifis if wifi utility is not busy
		if(wifi_screen->data.state == WIFI_UTIL_IDLE) {

                        // Layout each of the rows in the main group
			for(uint8_t i = 0; i < wifi_screen->data.wifi_arr_size; i++) {
				Layout_Row_Custom(
				gui->NK_Context, Breadth(Ratio_Of_Total(0.2)), 3,
				Breadth(Ratio_Of_Total(0.3)), Breadth(Ratio_Of_Opposite(0.77)),
				Buffer_And_Breadth(Ratio_Of_Total(0.05),
				Ratio_Of_Remainder(1)));

                                // ASSERTION TRIGGER
				Render_Wifi_Connection_WIFI_SCREEN(wifi_screen, gui, i);
			}
		}
	}
	nk_group_end(gui->NK_Context);

        //...etc
}

void Render_Wifi_Connection_WIFI_SCREEN(
WIFI_SCREEN* wifi_screen, GUI* gui, uint8_t index) {
	// Render percentageLabel
	Render_Label_With_Buffer(
	&wifi_screen->percentageLabel, gui->NK_Context,
	string(to_string(wifi_screen->data.wifi_arr[index].signal_strength) +
	"%").c_str(), NK_TEXT_CENTERED);

	// Render lock symbol if the wifi is secure
	if(wifi_screen->data.wifi_arr[index].type == WIFI_ELEMENT_TYPE_WPA) {

                // ASSERTION TRIGGER
		Render_Image(&wifi_screen->lockSymbol, gui->NK_Context);
	}
	else {
		nk_label(gui->NK_Context, "", 0);
		nk_label(gui->NK_Context, "", 0);
	}
        // ...etc
}

void Render_Image(IMAGE* image, struct nk_context* ctx) {
	Check_And_Load_Image_In_Current_Rect(image, ctx);

        // ASSERTION TRIGGER
        // HERE is the subgroup from the diagram
	if (nk_group_begin(ctx, "image panel", NK_WINDOW_NO_SCROLLBAR)) {

		// Layout the row with a left buffer and upper buffer
		// to push the image into the center of the column
		Layout_Row_Single(
		ctx, Buffer_And_Breadth(
		Ratio_Of_Total((1.0 - image->heightRatio) / 2.0),
		Ratio_Of_Total(image->heightRatio)),
		Buffer_And_Breadth(
		Ratio_Of_Total((1.0 - image->widthRatio) / 2.0),
		Ratio_Of_Total(image->widthRatio)));

		nk_label(ctx, "", 0);
		nk_image(ctx, nk_image_ptr(&image->image));
	}

	nk_group_end(ctx);
}
```
I've tried really hard to test all of my own personal code surrounding the issue but I can't find fault with my own code.  If someone knows the nuklear library better than I do and can help me find out what's going wrong, that would be much appreciated

**Comment by BenjiBoy926** [comment]
So just in case someone else ran into this issue, I'll go ahead and answer my own question!

The problem is `Render_Image` at the end.  Apparently, `nk_group_end(ctx)` needs to be *inside* that `if (nk_group_begin(...))` call, like this:

```c
if (nk_group_begin(...)) {
    // Code stuffs
    nk_group_end(ctx);
}
// NOT HERE!
// nk_group_end(ctx);
```

This explains why the program crashed only for groups outside main group panel - in these cases, `nk_group_begin(...)` must have returned false, but in any case `nk_group_end(ctx)` still got called when it wasn't supposed to.

I have to say it's a little unfortunate that group begin/end has to be different from window begin/end, because in window begin/end you have to call `nk_end(ctx)` in any case, even if `nk_begin(...)` returned false.  We should consider putting very explicit comments about this - if they already exist, I certainly haven't been able to find them

**Comment by dumblob** [comment]
>I have to say it's a little unfortunate that group begin/end has to be different from window begin/end...

I share your concerns.

>We should consider putting very explicit comments about this...

Pulls are welcome :wink:.
