### ISSUE TITLE
It can be use for ARM cortex m4 microcontroller?

### ISSUE THREAD

**Issue by skylin008** [vurtun/nuklear#87]
It can be use for ARM cortex m4 microcontroller?

**Comment by mmozeiko** [comment]
Yes, it can. You will just need to plug in your own rendering code. See under demo folder how is done with OpenGL or just plain xlib and adjust to your needs.

For more information see #77 issue.

**Comment by vurtun** [comment]
In addition to what @mmozeiko said if you hit memory constraints I am definitely willing to help out and investigate how to save some memory. So far I did not test how far I can down size allocated memory and binary size so there is no guide or steps to follow so far. The biggest problem would be font baking which takes a lot of memory and is not really suitable for microcontroller. So you probably would have to use your own font implementation. (You could also bake the font separately).
