### ISSUE TITLE
x11_xft resize issue

### ISSUE THREAD

**Issue by Lory171** [vurtun/nuklear#870]
Using the X11 backend with XFT fonts from `demo/x11_xft`, when you resize the window the font disappear. This happen because we are creating a new drawable surface for the resized window, but we are not updating the reference in `XftDraw * ftdraw`.

Adding the following code to the end of function `nk_xsurf_resize` in `nuklear_xlib.h` fix the issue.
`#ifdef NK_XLIB_USE_XFT`
	`XftDrawChange(surf->ftdraw, surf->drawable);`
`#endif`
	`return;`

**Comment by dumblob** [comment]
Yeah, just make a pull and I'll happily merge it :wink:.

**Comment by Lory171** [comment]
#871
