### ISSUE TITLE
OpenGL rendering produces ugly font

### ISSUE THREAD

**Issue by mmozeiko** [vurtun/nuklear#88]
All examples and GL based demos for me produces pretty awful font.

See this screenshot:
![screenshot](http://i.imgur.com/RkFANAx.png)
This is from example/overview.c demo on Linux with Iris Pro 5200. And I get same output also on Windows with Nvidia 970.

Is this expected? Because fonts in screenshots on nuklear github page looks much prettier.

**Comment by fr500** [comment]
It may just be the font, I changed main.c on the example to use Roboto and got much better results.
I also changed GL_LINEAR to GL_NEAREST

It's still getting a bit cutout towards the right side though

**Comment by vurtun** [comment]
The default font is not really meant to look good and more to just have something that works out of the box. That being that something is bugged in my font code see issues #68 #69 as well. I commited some heavy change to this library before release and probably introduced a bug into the font code. It is on top of my todo list and I will fix it as soon as possible.

**Comment by xdevelnet** [comment]
is it possible to build examples with xlib/xcb as backend, not with GL/GL* ?
Thank you.

**Comment by vurtun** [comment]
@xdevelnet sorry but could you create a new issue and I will see what I can do for you since this is about something else.

@mmozeiko and @fr500  Could you test again if the font bug is now fixed? At least for me it seems better.

**Comment by xdevelnet** [comment]
@vurtun Done

**Comment by fr500** [comment]
looks a bit better but some characters are still off by one pixel to the right?
What commit fixed this btw?

**Comment by vurtun** [comment]
Commit: https://github.com/vurtun/nuklear/commit/18b93fcc8affebf902b9542ed07352a3d41d98ab
I failed inside the condition and it compiled to true.

**Comment by mmozeiko** [comment]
Only a bit bitter. Some characters look awful. Like 'e' character. Look at dear imgui screenshots in their github page for comparison.

![screenshot](http://i.imgur.com/RRT9Gkj.png)

**Comment by vurtun** [comment]
Do you mean the blurriness? I can fix that. But them problem I am currently working on is that some pixel seem to be cut of.

**Comment by vurtun** [comment]
@mmozeiko Is it now better? I used the correct oversample and size and it hopefully should now be pixel perfect.

**Comment by sol50** [comment]
It would be great to be able to let FreeType do the font rendering. It is very portable, so maybe just some hooks are needed for external text rendering?

**Comment by vurtun** [comment]
You can!. You do not have to use my font implementation (for both vertex buffer output or shapes). Please have a look inside the library I have some documentation about font handling. If you have any problems or don't know how to do it create an issue and I will help out.

**Comment by mmozeiko** [comment]
@vurtun It's not pixel perfect. Now it doesn't cut off last column, but it is still much blurrier than it should be.

![screenshot](http://i.imgur.com/c7N72VD.png)

@sol50 You can use FreeType if you want, this library offers you the ability to use whatever font rendering you want. Or event depend on OS rendering. But by default it shouldn't depend on heavy external libraries. That's the point of single-header file libraries (like stb_image.h and others - you wouldn't want it to depend on libpng or libjpeg).

**Comment by vurtun** [comment]
This is how it looks for me at least inside the demo:
![test](https://cloud.githubusercontent.com/assets/8057201/14684164/d2d11e16-072e-11e6-8ff0-f77c0492c1fc.png)

**Comment by mmozeiko** [comment]
Oh, demo/glfw for me really looks good. Exactly as your screenshot. So that is fine.
My screenshot was from overview example.

**Comment by vurtun** [comment]
Sorry I only checked inside the demos. For overview.c you have to set the pixel font height for the default font to 13. For different fonts you have to tweak oversampling and the default font is set to 13.

**Comment by mmozeiko** [comment]
I see. Changing it to 13 gives perfect font rendering. Thanks for the support!

![screenshot](http://i.imgur.com/GorMgl6.png)
