### ISSUE TITLE
How to nuklear in x64?

### ISSUE THREAD

**Issue by nnjap** [vurtun/nuklear#883]
Hi, im new in c, but realy enjoyed nuklear ui.
Im make ui using gdip demo, but my app contains to many huge arrays and it does not compile in x86 mode.
How can I compile in x64 this using the gdip? Or do I need to change the rendering API? And which one to choose?
Thanks.

**Comment by dumblob** [comment]
Hi @nnjap, glad to hear you're enjoying Nuklear. I'm not sure though I understand what you mean. What are e.g. those "huge arrays" you're referring to? What does it mean "it does not compile in x86 mode" etc.?

Note, I'm not aware of any such limitations of Nuklear, so I'm rather expecting something peculiar in the code you're trying to compile. You can also post your code to pastebin or some snippets directly here in comments.

**Comment by nnjap** [comment]
Hi @dumblob, im solved my problem. It' not a joke, but i forgot recompile my x86 dll's for 64 xd...
Also, are there any ways to hide nuklear console from user or not? This is not so important, I just would like to.
Ps. Maybe i found a way to make nuklear a little better.
I changed sthis strings in nuklear core to make combobox more dinamicly:
`if (nk_combo_begin_label(ctx, items[selected], size)) {
        nk_layout_row_dynamic(ctx, (float)item_height, 1);
        for (i = 0; i < count; ++i) {
            if (!strcmp(items[i], "NULL") == 0)
            {
                if (nk_combo_item_label(ctx, items[i], NK_TEXT_LEFT))
                    selected = i;
            }
        }
        nk_combo_end(ctx);
    }`
It works very well in my c case with static arrays length.

**Comment by dumblob** [comment]
>Also, are there any ways to hide nuklear console from user or not?

Which console are you referring to? There is no console in Nuklear as of my best knowledge.

>`if (nk_combo_begin_label(ctx, items[selected], size)) { nk_layout_row_dynamic(ctx, (float)item_height, 1); for (i = 0; i < count; ++i) { if (!strcmp(items[i], "NULL") == 0) { if (nk_combo_item_label(ctx, items[i], NK_TEXT_LEFT)) selected = i; } } nk_combo_end(ctx); }`

Could you be more specific? Which lines of `nuklear.h` are you referring to? Or at least which function?

**Comment by nnjap** [comment]
> Which console are you referring to? There is no console in Nuklear as of my best knowledge.
I'm talking about this: imgur.com/a/0SXQv0c
> Could you be more specific? Which lines of `nuklear.h` are you referring to? Or at least which function?
Sry, I changed the nuklear.h line in nk_combo function. (this is the 25177 line).

**Comment by dumblob** [comment]
>I'm talking about this: imgur.com/a/0SXQv0c

Aha, well, I'm not aware such second window coming from the [backend](). My first guess would be you've chosen `terminal application` from the two major choices (`terminal application`, `window application`) when compiling the source.

>Sry, I changed the nuklear.h line in nk_combo function. (this is the 25177 line).

I'll take a look and will try to understand what was the purpose of this edition of yours :wink:.
