### ISSUE TITLE
Assertion failed with demos and examples

### ISSUE THREAD

**Issue by dannysuen** [vurtun/nuklear#89]
```
danny@Danny-Y500:~/Developer/nuklear/demo/glfw/bin$ ./demo 
demo: ./nuklear_glfw.c:77: void nk_glfw3_device_create(): Assertion `status == 1' failed.
Aborted (core dumped)

```

**Comment by fr500** [comment]
That's not really an issue, that just means it's failing to compile the shader, maybe your GPU doesn't support the GL feature set required

**Comment by angusholder** [comment]
You could try changing [line 36](https://github.com/vurtun/nuklear/blob/master/demo/glfw/nuklear_glfw.c#L36) to:

    #define NK_SHADER_VERSION "#version 130\n"

It appears that your graphics driver doesn't support OpenGLES 3.0, so this makes it use an older version of the GLSL which should still run fine.
