### ISSUE TITLE
Documentation link to the rawgit.com is Supposed to stop Working in 2019_10

### ISSUE THREAD

**Issue by martinvahi** [vurtun/nuklear#901]
According to the 

https://rawgit.com/
(archival copy: https://archive.is/Yjblg )

the rawgit.com service will be shut down in 2019_10. 
As of 2019_09_12 the rawgit.com service owner recommends the following
alternatives:

https://www.jsdelivr.com/rawgit
https://pages.github.com/
https://codesandbox.io/
https://unpkg.com/

**Comment by eax0r** [comment]
Merged with #908. :blush:

**Comment by dumblob** [comment]
Fixed. Thank you all!
