### ISSUE TITLE
(Question) images in nuklear

### ISSUE THREAD

**Issue by alxbrn** [vurtun/nuklear#914]
Not much a issue, more a question. I have been using nuklear for a while now, but I have never seen a way to implement a image in nuklear. Is this possible?

(I want to load a image either from a url or a local file either from a resource file or bitmap)

**Comment by molecularentropy** [comment]
It's definitely possible. Have a look at the x11_opengl2_tex demo.

**Comment by eax0r** [comment]
@alxbrn Did you try `nk_draw_image`, I mean this is pretty straightforward.
