### ISSUE TITLE
Is it possible to build examples with X11 as backend?

### ISSUE THREAD

**Issue by xdevelnet** [vurtun/nuklear#92]
...but not as GL/GL*?

Thank you.

P.S. After some code reviewing, I figured out that it's not trivial. At least, for me.

**Comment by vurtun** [comment]
A previous version already used all the example code with X11 except `extended.c` (xlib cannot draw scaled images) and some parts of `overview.c` (color picker). 
If you want I can upload the them to gist for you?.

**Comment by xdevelnet** [comment]
Wow, that would be nice!

**Comment by vurtun** [comment]
OK I was able to convert `overview.c`, `node_editor.c` and `calculator.c`. `style.c` is independent and `extended.c` and `file_browser.c` use images with alpha blending which I tried to emulate in xlib some time ago but it did not work out (to slow):

1.) Overview: https://gist.github.com/vurtun/fb6fe165308837024854bdfe00151383
2.) Node editor: https://gist.github.com/vurtun/cbe6da3ecaf9ba93dbedc520d783b9dd
3.) Calculator: https://gist.github.com/vurtun/7621dd3625a3e88d6c792ae06118eb7e

**Comment by xdevelnet** [comment]
Tnx a lot!

The only one reason why I request this is to throw away redundant GL dependencies and make examples (for me) less useless.

I just want to add few things:
1)
>#include \<time.h>

2) need std=gnu99 or some special macro definitions, otherwise struct timespec won't work
3) For some reason it still creates big window, and then application window inside it.

I was looking for good toolkit (qt is fat and need c++, gtk is just ugly), but still didn't find it.

Huh. Nevermind.

Tnx anyway :smile: 

Regards, Xdevelnet

**Comment by mmozeiko** [comment]
If you want C++ imgui library check out dear imgui: https://github.com/ocornut/imgui

**Comment by xdevelnet** [comment]
@mmozeiko No, I do NOT want C++. Thank you.

**Comment by mmozeiko** [comment]
Oh, sorry I misunderstood what you wrote.
