### ISSUE TITLE
Please assign a license

### ISSUE THREAD

**Issue by brianbruggeman** [vurtun/nuklear#94]
Apache 2.0 is best if you want commercial use.

**Comment by gingerBill** [comment]
It's "licensed" under public domain. This means it doesn't "need" a license.

**Comment by Juanlu001** [comment]
The notion of PD is problematic since law is not uniform across countries. Sorry not to provide a reference, I cannot find any convincing one right now.

**Comment by nabijaczleweli** [comment]
http://stackoverflow.com/a/13669816/2851815

**Comment by sol50** [comment]
Yes please, I am not allowed to public domain software because of U.S law related to copyright.

**Comment by vurtun** [comment]
Like I wrote it is dual licensed:
> This software is dual-licensed to the public domain and under the following license: you are granted a perpetual, irrevocable license to copy, modify, publish and distribute this file as you see fit.

See the reasoning here: https://github.com/nothings/stb/blob/master/docs/why_public_domain.md
You also can create derivative work by modifying one character, and then license that however
you like. (like zlib or BSD license).

**Comment by paulsapps** [comment]
"public domain" IS a license though. No license means actual no mention at all of a license, so saying its copyrighted under US law seems incorrect.

**Comment by Leandros** [comment]
@sol50 IANAL, but US copyright laws have a public domain clause, and it's perfectly fine for you to use public domain software in the US. That doesn't apply to all countries though, Germany is a prominent example of being a little difficult with public domain.

**Comment by bmastenbrook** [comment]
License issues are boring and frequently contentious, so I hesitate to wade in here. I'd just like to point out that if the intention is to dedicate the work to the public domain, and to provide the broadest possible license in jurisdictions where that is not possible, you might want to consider using CC0, which was drafted specifically to do that. Stating that the work is CC0 and providing a link to https://creativecommons.org/publicdomain/zero/1.0/ is usually a lot shorter than legalese anyway.

**Comment by HackIT** [comment]
It **ALREADY** have a **LICENSE**, please don't enumerate... It's done.
