### ISSUE TITLE
Calculator example - moving cursor to the end of the text field and typing causes crash

### ISSUE THREAD

**Issue by 0----0** [vurtun/nuklear#97]
Using keyboard navigation or mouse clicks, it's possible to move the cursor past the last digit in the text field.  When the cursor is in this state, it appears smaller than normal.  Upon typing a number, the application crashes with the following message.
```
calculator: ../nuklear.h:13105: nk_do_edit: Assertion `cursor_ptr' failed.
```
Image of the cursor past the last digit in the text field.  While it is in this state, typing a number on the keyboard will cause a crash.
![http://i.imgur.com/0FBRxeM.png](http://i.imgur.com/0FBRxeM.png)

**Comment by vurtun** [comment]
Thanks for the issue. I hope it is now fixed.
